### ISSUE TITLE
Posunutí děr ve sloupcích pro GPS anténu

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#103]
Z nějakého důvodu jsou ve sloupcích posunuté otvory oproti pozici sloupků. 

![image](https://user-images.githubusercontent.com/1194177/37312669-3e9c802a-264c-11e8-8e90-e5c1009216ee.png)

**Comment by Elizaa62** [comment]
Nevím z jakého důvodu byly ty otvory mimo. Zavedla jsem si pro pomoc nové globální proměnné pro GPS, protože jsem se v těch číslech nemohla vyznat a otvory jsem srovnala. Myslím si, že už je to teď správně. 

Dále jsem si všimla, že mi nesedí ani otvory pro připevnění akumulátoru, tak jsem je taky srovnala. 

Koukni na to :)

**Comment by kaklik** [comment]
Zkusim vytisknout samostatně ten díl na kterém ty sloupky jsou a vyměnit ho za ten vytištěný.
