### ISSUE TITLE
Tolerance zámků na krytech

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#104]
Vypadá to, že na krytech je nějaký zmatek v tolerancích zámků v ose X.  Zřejmě je to způsobené tím, že  mezi díly C a D se mění orientace zámků na krytech.  Proto nejde všechny zámky posunout o toleranci k jedné straně. 
Momentální situace je taková, že přední zámky nemají žádnou toleranci.  A zadní zřejmě správnou. 

![image](https://user-images.githubusercontent.com/1194177/37337340-3a9ddea2-26b4-11e8-8008-677408cf8e36.png)

Tolerance jsou zřejmě také ovlivněny tím, že kryt se dělí na díly o global_clearance/2 kratší. Což efektivně snižuje velikost tolerance pro zámky.  Předpokládám, že se to tak dělá proto, aby na dílech nezůstávaly zbytky lemů.  
https://github.com/Elizaa62/Components/blob/42c76f9549a1f40cb9dd012df800e1bedf3af764/src/666_1025.scad#L457

Toho lze ale dosáhnout i použitím velmi malého posunutí dělení třeba global_clearance/100, jako je to u spodního krytu.

https://github.com/Elizaa62/Components/blob/42c76f9549a1f40cb9dd012df800e1bedf3af764/src/666_1029.scad#L432

Také jsem si všiml, že spodní kryt používá pro délku zámků parametr "lock_length", ale horní kryt má pevně nastaveno "hull_wall_thickness*4". Tohle by se myslím mělo sjednotit.

**Comment by Elizaa62** [comment]
Horní kryt už také používá pro délku zámků parametr "lock_length".  

U předních zámků jsem opravila tu toleranci. Tak se prosím koukni, zda to je správně. 

Poté to dělení s "global_clearance/100".. u horního krytu jsem to dala místo "global_clearance/2". Před tím to "global_clearance/2" jsem ani nevěděla, že to tam je. Nejspíše jsi to tam vkládal ty a já si nevšimla :)

**Comment by kaklik** [comment]
Jsou  ty tolerance určitě opravené dobře?  Protože mě se nezdá to, že jak u předních, tak i u zadních zámků krytu je teď přidaná tolerance  + global_clearance/2. 
Myslím si ale, že díky tomu, že mezi díly C a D se zámky otáčí, tak se musí změnit i znaménko tolerance, ne?

**Comment by kaklik** [comment]
Tak už asi vidím, jak ty tolerance jsou vyřešené. 
Jenom mi ještě není jasné, jestli  přidání + global_clearance/2 na tomhle řádku je záměr?
https://github.com/Elizaa62/Components/blob/7b8f4cc0fb2d71bdaa4c620749f6f2d9c76078c9/src/666_1025.scad#L395

Je mi to podezřelé proto, protože na tomhle řádku pro dělení následujících dílů to naopak už není: 
https://github.com/Elizaa62/Components/blob/7b8f4cc0fb2d71bdaa4c620749f6f2d9c76078c9/src/666_1025.scad#L456

A myslím si, že je původní důvod přidání téhle tolerance to, aby na dělení dílů nezůstávaly zbytky lemů.  To by ale teď mělo řešit to zmenšení dílu o "global_clearance/100".

**Comment by Elizaa62** [comment]
Já si nevzpomínám, že bych tam tu toleranci do řádku 395 přidávala. Protože je mi jasné, že to odstraňuje ten zbytek lemu, ale vážně si neuvědomuji, že bych to tam dávala. Každopádně v tom translate se to odstraní a ponechá se tolerance global_clearance/100 pouze u toho cube. Bude to tak správně?

Zmenšení dílu o global_clearance/100? Teď tomu asi nerozumím. Tohle se zapisovalo v tom Cube.. 
        https://github.com/Elizaa62/Components/blob/7b8f4cc0fb2d71bdaa4c620749f6f2d9c76078c9/src/666_1025.scad#L396            

Tak teď tomu trochu nerozumím.

Jsem blbá.. už to vidím.. jsem tam viděla plus místo minus.

Opraveno :)

**Comment by kaklik** [comment]
Paráda, až to sem nahraješ, tak myslím že je to snad vyřešené. :)

**Comment by Elizaa62** [comment]
Nahráno :)

**Comment by kaklik** [comment]
Potřeboval bych, aby byly na krytech opravené i ty další záležitosti, aby mělo smysl zkoušet tisknout nové kryty.

**Comment by Elizaa62** [comment]
Tak ty zámky by měly být vytvořeny už správně.

**Comment by kaklik** [comment]
Ano to asi jsou.  Ale mě se nechce znova tisknout kryty, když na nich je potřeba opravit i ty další issues.

**Comment by kaklik** [comment]
Zatím to zavírám, pravděpodobně je to vyřešené a seznam bude přehlednější.
