### ISSUE TITLE
Vytvořit funkci která umožní získat úhel a vzdálenost povrchu aerodynamického profilu

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#106]
Pro vyřešení úkolů  #94, #87, #78, #62 a možná #26  je potřeba vědět vzdálenost povrchu a úhel kapky v definovaném bodě. Aby bylo možné na povrch přesně umisťovat otvory a další elementy.

**Comment by kaklik** [comment]
upravil jsem knihovnu naca4.scad tak aby poskytovala funkce 
-"surface_distance", pro zjištění vzdálenosti povrchu profilu od jeho osy 
- "surface_angle", pro zjištění úhlu povrchu vůči ose profilu. 

Tyto dvě nové funkce jsem vyzkoušel  tak, že jsem vytvořil příklad https://github.com/kaklik/Components/blob/master/src/naca4_test.scad

Který poskytuje takovýto výsledek.

![image](https://user-images.githubusercontent.com/1194177/37684272-ccf030ee-2c8f-11e8-9cba-b97edfa4415a.png)

Nyní je potřeba to implementovat do ostatních částí modelů.

Současná fuknce "trailing_edge_angle" se tak může zrušit.

**Comment by Elizaa62** [comment]
Chápu to teda dobře tak, že všude v modelech, kde se vyskytuje funkce "trailing_edge_angle" ji mám nahradit funkcí "surface_angle"?

**Comment by Elizaa62** [comment]
Pokusila jsem se do horního krytu vložit funkci "surface_angle", ale celý ten model se mi rozbil. Nejprve v dílu 666_1025 zmizel kus držáku na kryt pylonu  a když jsem provedla změnu i v dílu 888_1000, tak se mi rozbila celá kapka.

**Comment by kaklik** [comment]
Na díly s dutým profilem, jako je třeba držák krytu pylonu jsem už před tím vytvořil novou funkci, která generuje duté profily hollow_airfoil.  Kromě toho, že ti vytvoří profil rovnou o požadované tloušťce stěny, tak je i o něco rychlejší.  

Zkusim to opravit a lépe okomentovat.
