### ISSUE TITLE
Zajištění vrtacích přípravků proti otočení

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#109]
Zjistil jsem, že je potíž zajistit, aby se během vrtání přípravek neotočil, ale přitom šel nasadit na trubku.  

Napadá mě to vyřešit tak, že by kostka přípravku byla třeba do 2/3 proříznutá a na kraji by byl šroub, kterým by kostka šla stáhnout ve vyrovnané pozici na stole. 
Takže by se postupovalo tak, že se přípravky nasadí na trubku, na stole se vyrovnají. Utáhnou se zajišťovací šrouby. Na vrtačce se vyvrtají díry, povolí se zajišťovací šrouby a sundají přípravky.

**Comment by Elizaa62** [comment]
U dílu vrtacího přípravku pro díl 666_1026 vytvořen prořez a otvor pro zajišťovací šroub.

Koukni na to, zda to tak může být, a já to pak vytvořím u ostatních vrtacích přípravků.

**Comment by kaklik** [comment]
Ano, tohle je možná i ještě lepší řešení, než jsem původně myslel já. Je to lepší proto, protože je to symetrické. :) 
Ale zas to vyžaduje utažení dvou šroubů. Ty matky by to ale asi chtělo zapustit více, aby tam nebyly takové nároky na přesnou délku šroubu. 

Můžeš mi prosím udělat u některého přípravku i variantu, kde ten stahovací šroub bude jenom na jedné straně. A prořez pro stažení bude třeba do 2/3 šířky přípravku, ale přes celou jeho výšku? Takže asymetricky.  Vyzkouším jaký je to rozdíl.

**Comment by Elizaa62** [comment]
Máš to vytvořené u přípravku k dílu 666_1028. Snad jsem to pochopila správně.

**Comment by kaklik** [comment]
Pochopila jsi to úplně správně. :)

**Comment by kaklik** [comment]
Teď jsem tam ještě opravil to, aby šroub nezasahoval do trubky.  A aby prořez začínal až těsně u stěny trubky - to kvůli tomu, aby se nebortilo dno přípravku při stahování šroubem.

Předchozí stav
![vrtaci_pripravek](https://user-images.githubusercontent.com/1194177/37955670-89a6e142-31a9-11e8-9b39-ca9dc9c5346f.png)

Po úpravě: 
![image](https://user-images.githubusercontent.com/1194177/37955763-c5f45c92-31a9-11e8-8e41-1387af179bf2.png)

Byla to už jenom jednoduchá úprava, kdy jsem jenom zmenil parametry modelu.

Zkusím to vytisknout a vyzkoušet. Pak napíšu co s tím dál.

**Comment by Elizaa62** [comment]
Koukala jsem na ten změněný přípravek a všimla jsem si, že jsi šířku toho prořezu změnil
![image](https://user-images.githubusercontent.com/31339298/38046198-52df5f92-32bf-11e8-8ec4-529edab441e1.png)

Mám to změnit i u těch ostatních přípravků?

**Comment by kaklik** [comment]
Ano, nastavil jsem to podle global_clearance, protože mi to připadá logičtější. Šířka prořezu by totiž při ideální přesnosti výroby mohla být nulová. Taková situace ale nenastane, protože základní tolerance výroby odpovídá parametru global_clearance. 
Šířku prořezu jsem tak nastavil na trojnásobek základní tolerance podle [pravidla 3-sigma](https://cs.wikipedia.org/wiki/Pravidlo_t%C5%99%C3%AD_sigma).

Myslím si, že správné je to takto nastavit i v ostatních přípravcích.

**Comment by Elizaa62** [comment]
Tys sice nastavil šířku 3*global_clearance, ale už jsi to neposunul doprostřed. Tak jsem to opravila a šířka prořezů a je opravena i u ostatních vrtacích přípravků.

**Comment by kaklik** [comment]
Ano, to je chyba, že jsem to neudělal. Je super, že jsi si toho všimla a opravila jsi to. :) 
Myslím, že ty přípravky, teď vypadají tak, jak jsem si představoval, že by to mohlo fungovat. Takže to teď zavřu.
