### ISSUE TITLE
Šrouby pro připevnění k podložce

### ISSUE THREAD

**Issue by Elizaa62** [Elizaa62/Components#114]
Vytvořila jsem dva nové moduly:
- module screw_top (position_number,draft)
- module screw_bottom (position_number, draft)

U obou je podmínka if, jak jsme vytvořili spolu. Navíc jsem k tomu přidala funkci for a doplnila jsem i posunutí a otočení. 

Moduly jsou vytvořené v dílu 666_1027. Tak se prosím podívej, zda to tak může být.

**Comment by kaklik** [comment]
Super, myslím že ty moduly jsou vytvořené skoro přesně tak, jak jsem navrhoval. :)

Jenom ta funkce for požitá nějak zvláštně, že nerozumím jak to může fungovat, asi bych to potřeboval vysvětlit. 
Zároveň je tam tahle složitá podmínka  

    if (position_number > 1 && position_number < 5)

Která by asi vyžadovala nějaký komentář, protože nevím co má udělat. 

Původně jsem čekal, že ten for bude v tom hlavnim modelu.  A tím se nahradí tohle opakování modulů

                %screw_top (1, draft);
            mirror([0,0,1])
                %screw_top (1, draft);

        //část B
               	%screw_top (2, draft);
            mirror([0,0,1])
               	%screw_top (2, draft);

        //část C
                %screw_top (3, draft);
            mirror([0,0,1])
                %screw_top (3, draft);

        //část D        
                %screw_top (4, draft);
            mirror([0,0,1])
                %screw_top (4, draft);

                %screw_top (5, draft);
            mirror([0,0,1])
                %screw_top (5, draft);

V principu něčím jako tohle 

    for (a = top_screw_position)
    {
            screw_top (a, draft);
            mirror([0,0,1])
                crew_top (a, draft);
    }

Opakování se proto vytvoří právě tím forem.

**Comment by Elizaa62** [comment]
if (position_number > 1 && position_number < 5)

-> to znamená, že v pozici 2,3, a 4 se ten šroub neotáčí podle surface_angle, protože je na podložce rovná hrana a taky se neposouvá o distance, protože je tam ta rovná hrana. Tak jsem tam nechala pevné posunutí -hull_z_size/2. 

a ta funkce for... nevěděla jsem jak s ní pracovat, tak jsem ji tam nějak vložila a začalo to fungovat.

A jak jsem ti říkala včera.. vždycky to udělám tak, aby mi ty funkce nějak fungovaly. A jelikož netuším, že se to dá udělat, tak jak jsi napsal, tak jsem to tak neudělala.

**Comment by kaklik** [comment]
aha, tak to mi teď ten if dává docela smysl.  Je to složitá podmínka a bez tohoto vysvětlení je těžko pochopitelná.  Mám do toho kódu tuhle vysětlující poznámku zkopírovat?  A nebo si to tam raději dopíšeš ty? 

a to vysvětlení for cyklu stačí tedy takové jako jsem napsal? A nebo je ještě něco dalšího, co víš, že potřebuješ vědět?

**Comment by Elizaa62** [comment]
Budu se tomu zase věnovat zítra. Zatím asi stačí, jak jsi to napsal. Kdyby něco, tak napíšu.

**Comment by Elizaa62** [comment]
Cyklus šroubových spojení je už dávno vytvořené
![image](https://user-images.githubusercontent.com/31339298/38582070-eaf8cc10-3d0e-11e8-9606-cb8b832952ee.png)

Je to tak správně?

**Comment by kaklik** [comment]
Aha, já si toho nevšiml. 
Jo tohle vypadá správně. :)  Je to jedno z možných řešení.
