### ISSUE TITLE
Otočení šroubů pro připevnění akumulátorů

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#115]
Při montáži akumulátorů jsem zjistil, že se na šroub docela těžko nasazuje matka, když šroub vede zhora dolu. 
Když se šroub otočí, tak zas nedrží v díře dokud se na něj matka nenasadí.
Lepší by proto bylo, kdyby šroub byl v podložce zdola nahoru a byl chycený matkou, podobně jako na následující fotografii. 

![20180406_181125](https://user-images.githubusercontent.com/1194177/38452487-6c8fa9dc-3a45-11e8-8420-7da1881b8bee.jpg)

Akorát matka by byla zapuštěná v podložce. Pak by se na šrouby nasadil třmen 888_1001 a přitáhl se další matkou.  Zapuštění pro matku na patce třmenu je proto potřeba zrušit, aby se matkou dalo pro dotažení otáčet.

**Comment by Elizaa62** [comment]
Vytvořeno.

**Comment by kaklik** [comment]
Ano, takhle jsem si to představoval.  Jenom mi připadá, že ta horní matka je zapuštěná nějak moc hluboko. Čekal jsem, že bude akorát tak, aby nepřečnívala přes povrch. Díval jsem se do kódu, jestli tam uvidím něco jako Nut_height_M3,  ale nic takového jsem tam nenašel. Takže to nedovedu sám rychle opravit.

**Comment by Elizaa62** [comment]
Je to zadané posunutím v ose Y o 1.5*main_tube_diameter. Musíš to v tom případě posunout nahoru o tloušťku podložky a odečteš od toho výšku matky asi ještě s nějakou tolerancí, aby bylo zaručeno, že ta matka nebude vyčnívat.

**Comment by Elizaa62** [comment]
Opravila jsem to.

**Comment by Elizaa62** [comment]
výška dílu 666_1027

![image](https://user-images.githubusercontent.com/31339298/38693708-0dd789b8-3e88-11e8-899d-1c84a19ed96d.png)

**Comment by kaklik** [comment]
Vypadá to jako vyřešené.
