### ISSUE TITLE
Šroubový spoj - horní kryt.

### ISSUE THREAD

**Issue by Elizaa62** [Elizaa62/Components#116]
Vylepšila jsem ten spoj tak, jak jsme se domluvili. Problém je v tom, že ten kryt spoje nemohu zapustit ještě více, protože by jinak nebyl kolem celého spoje. 

Tak se na to prosím koukni a případně napiš další námitky.

**Comment by kaklik** [comment]
Vypadá to mnohem lépe. :) Zkusím to zase vytisknout.

**Comment by kaklik** [comment]
Tak to i funguje :)

![20180411_140106](https://user-images.githubusercontent.com/1194177/38618943-4bdfc902-3d9b-11e8-934b-2c0fd94e49e4.jpg)

Dotisknu další díly krytu a bude zas lepší prototyp.
