### ISSUE TITLE
Vyztužení dílu A spodního krytu

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#117]
Již před časem jsem do horního krytu umístil výztuhu, která zlepšuje tisknutelnost viz obrázek: 
![image](https://user-images.githubusercontent.com/1194177/38624366-319f77ec-3da8-11e8-93a6-ebfe849fa646.png)

Bylo by zřejmě potřeba podobnou výztuhu dát i do spodního krytu, aby se při tisku nebortil.  V případě spodního krytu je pravděpodobné, že by tam těchto výztuh mělo být více než jen dvě.

**Comment by Elizaa62** [comment]
Výztuhy vytvořeny.

**Comment by kaklik** [comment]
Jsou tam drobné chyby, které brání tomu, aby mělo smysl to zkušebně tisknout.

- [x] Potřeboval bych, aby výztuha končila přesně v rohu modelu.  To znamená, aby podepírala model při tisku až do poslední chvíle. (do nejvyššího bodu)
- [x]  Výztuha by měla končit přesně vlemu a nepřesahovat jej. 

![image](https://user-images.githubusercontent.com/1194177/38744452-244c97a0-3f42-11e8-9211-3119f64af8e9.png)

- [x]  Také je třeba odstranit přesah do vybrání pro podvozkovou trubku
![image](https://user-images.githubusercontent.com/1194177/38744230-80ecac26-3f41-11e8-97a9-af3176089b5f.png)

**Comment by Elizaa62** [comment]
Opravila jsem chyby a trochu změnila pozice ostatních výztuh.

**Comment by kaklik** [comment]
Zkusím to vytisknout.

**Comment by kaklik** [comment]
Tak výztuhy kvalitě tisku pomohly. A model je teď i výrazně pevnější.

![20180418_101153](https://user-images.githubusercontent.com/1194177/38920664-123d9c98-42f4-11e8-9dd7-271c4315e786.jpg)

Nějak se ale rozbila ta tisková podpora u podvozkové nohy.  Snažil jsem se to opravovat, protože na začátku to nefungovalo vůbec.  Teď to ale taky není úplně ideální nad otvorem pro nohu přibyl nějaký materiál, který tam být nemá. 

![20180418_101128](https://user-images.githubusercontent.com/1194177/38920948-cd2d0020-42f4-11e8-9fec-1cae01eb183e.jpg)

Díky tomu tisk na téhle straně nedopadne až tak dobře, jak by mohl.  Díky těm změnám ti ale na to vytvořím pull-request.

**Comment by Elizaa62** [comment]
Chyba vznikla tím, že čtverec pro přidání výztuh byl veliký místo main_tube_outer_diameter 2*main_tube_outer_diameter. Chybu jsem odstranila.

Je u tohohle dílu ještě nějaká chyba, kterou se mám zabývat?

**Comment by kaklik** [comment]
Zkusím to vytisknout a dám vědět. Ale v tuto chvíli si myslím, že není. :)

**Comment by kaklik** [comment]
Tak myslím, že to zafungovalo parádně. Díl se vytiskl mnohem lépe než minule. :) 

![20180627_164624](https://user-images.githubusercontent.com/1194177/41984410-e8fcdc6c-7a30-11e8-8226-5f00674659e5.jpg)
