### ISSUE TITLE
Svrtávací přípravek pro otvory pod podložkou

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#118]
Pro vyvrtání všech šroubů umístěných  pod podložkou by se hodil přípravek, který by to umožňoval.  Ten by se na hlavní trubku asi měl nasazovat tak, že trubka bude srovnaná s přední hranou přípravku. 
Odpadlo by tím použití více přípravků a odměřování jejich pozic. 

Zřejmě musí být tvořen několika díly, které se slepí do jednoho celku. Podobně jako podložka.

**Comment by Elizaa62** [comment]
Mohl bys mi to nějak prosím vysvětlit? Nerozumím vůbec tomu, co mám dělat.

**Comment by kaklik** [comment]
V podélné trubce je v přední části, tam kde je podložka docela hodně děr, které musí být všechny v přesných vzdálenostech a navíc souosé. Na tyto díry se montují různé díly, držák motoru, spojky, podložka a podobně. 
Potřeboval bych jednu vrtací šablonu, která se nasune na trubku a jenom se podle ní všechny díry vyvrtají. 

Teď je to vyřešené tak, že máme několik vrtacích přípravků, což je hodně užitečné na opravy, ale na výrobu je to hrozně pracné.

**Comment by Elizaa62** [comment]
Vytvořila jsem nový díl 888_1014. Je to začátek svrtávacího přípravku.

**Comment by kaklik** [comment]
Ano, je to správně.  Nemusí tam ale být ta celá část pro vertikální trubku. Stačí jenom ty otvory na šrouby pro spojku 666_1017.

**Comment by kaklik** [comment]
Všiml jsem si, že v přední části jsou otvory kolmo na ostatní otvory v hlavní trubce. 

![image](https://user-images.githubusercontent.com/1194177/41232173-cd01ec80-6d85-11e8-9d4d-f4d20275a9bf.png)

To je správně? 

Potom přípravek neobsahuje dělení, aby šel vytisknout v omezených tiskových rozměrech.

**Comment by Elizaa62** [comment]
Tohle ještě není hotové.

**Comment by Elizaa62** [comment]
Opraveno. Přidala jsem dělení pro tisk.
