### ISSUE TITLE
Ohybací přípravek na podvozkové trubky

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#119]
Přípravek na ohýbání trubek bych si představoval asi jako desku opatřenou rádiusy, které je potřeba naohýbat. 

Nejdřív se asi budou ohýbat ohyby 2 a 3.  A až po nich se ohnou konce trubky ohyby 1 a 4. 

S ohyby 1 a 4 bude pravděpodobně největší komplikace, protože je potřeba, aby výsledek byl kolmý na osu ohybů 2 a 3. Je možné, že to bude potřeba zařídit nějakou další deskou, která se přes pant připojí k té první.  

Je zřejmě potřeba postupovat v těchto krocích: 

- [x] Vytvoření rádiusů pro ohyby 2 a 3 na rovné desce
- [ ] Otestování ohybů ohnutím trubky
- [ ] Doplnění přípravku o komponenty potřebné pro ohyby 1 a 4.

**Comment by kaklik** [comment]
K radiusům pro ohyby budou potřeba ještě rovné segmenty. Které budou sloužit k přidržení trubky před rádiusem

**Comment by Elizaa62** [comment]
Vytvořila jsem díl 888_1011. Zatím je to pokus o radius 2 a to sešikmení trubky pod úhlem. Ale upozorňuji dopředu, že je to jen hrubá verze. Nemám slovosled srovnaný.

**Comment by kaklik** [comment]
Myslím, že tak nějak by to být mohlo. :)

**Comment by kaklik** [comment]
Prohlížel jsem si aktuální stav a myslím že by mohlo stačit, aby ta trubka při ohybání byla přidržená jenom drážkou do poloviny průměru trubky.  Odstranil by se tím současný problém s modelováním rovných boků, které stejně bude dost problém vytisknout.

**Comment by Elizaa62** [comment]
Vyrobila jsem přípravek pro ohýbání podvozkových trubek (soubor 888_1011.scad). Přípravek jsem vyrobila jak pro podvozkovou trubku levou, tak pravou. Neumím si totiž představit, zda by ten jeden přípravek byl možný použít i pro druhou stranu.  Přípravek je vyroben pro ohyby 2 a 3 a vyvýšený modrý kus je pro ohyb 1 a 4.  Drážku jsem vyrobila hlubokou půlku průměru trubky.

Akorát nerozumím tomu druhému bodu. Otestování ohybu ohnutím trubky. To myslíš jako vytisknout přípravek a fyzicky ohnout trubku?

**Comment by kaklik** [comment]
Ano, je určitě správně mít přípravek pro levou a pravou podvozkovou nohu zvlášť. 
Druhý bod jsem myslel tak, že se přípravkem skutečně pokusíme vytvořit nějaký první ohyb na trubce. Předpokládal jsem že to zkusím já pokud mi s tím nebudeš chtít pomoct. :) 

Tenhle přípravek je ale dost jiný než to, co jsem tam viděl ještě před několika dny. Potřeboval bych zřejmě vysvětlit, jak se to použije k ohnutí trubky. 

![image](https://user-images.githubusercontent.com/1194177/40077896-4818273a-5883-11e8-9196-f3851cc6581b.png)

U té předchozí verze jsem si dovedl představit, že se trubka ohne okolo válce, který odpovídal rádiusu potřebného ohybu. Chyběla tam pouze drážka do které by se trubka při ohybu postupně ohýbala.
Tady tomu nerozumím. 
Nebo jsi to teď myslela jenom jako kontrolní přípravek, tak že ohyb je správný, když trubka zapadne do drážky?

**Comment by Elizaa62** [comment]
Vždyť to je stejný systém, akorát je to přesnější. Protože ta konstrukce s tím válcem byla taková od oka. Pokud se ti tohle nelíbí, tak to opět předělám do té původní verze.
Nebo to zkusím vymyslet ještě nějak jinak..

**Comment by Elizaa62** [comment]
Ten přípravek na trubky jsem začala dělat tak jak byl předtím. Akorát jsem si našla trochu jiný postup. Takto zkusím večer dodělat.

**Comment by Elizaa62** [comment]
Nechala jsem ten přípravek v dílu 888_1011 a vytvořila jsem nový soubor 888_1013. Vím, je to komplikované a asi ti to přijde nepřehledné, ale mě to takhle pomáhá, když je to zvlášť.. Pak to můžu dát časem do stejného souboru, nebo to nějak sjednotit.

V tom novém souboru 888_1013. Základní model je 888_1013. Díl 888_1013_A je taková mnou vymyšlená upínka, která má zobáček. Je zasunuta do dílu 888_1013 a zároveň spojena tím zobáčkem s kvádříkem na dílu 888_1013, co je hned na začátku. Dle mého názoru by to mohlo fungovat jako držák trubky, aby při ohýbání nevyjela z drážky. Ale nejsem si jistá, zda by se to nevysunulo... Je to jen pokus. Čekám na námitky :) Kdyby ti tenhle způsob přišel dobrý, tak bych to potom ještě rozšířila dál. Jinak ten díl 888_1013_A by se musel tisknout samostatně. 

Pak díl 888_1013_B je vlastně intersection dílu 888_1013 na základní tisknutelnou velikost.

**Comment by kaklik** [comment]
Ten přípravek je čím dál tím lepší. Budu k tomu ale mít připomínky, protože mě napadá lepší řešení. :)
Například přesunutím drážky pro trubku zespodu na bok ohybu se dá zlepšit zajištění trubky před ohýbáním. Protože trubka pak může být zajištěna jednoduchým výstupkem ze základny v rovné části bez ohybu.

**Comment by Elizaa62** [comment]
Drážky jsem pro trubku jsem přesunula do boku do spodní části tvarovací části. 

Zkusila jsem vymyslet nový systém  upínek. Systém upínání si představuji tak, že až se trubka vloží do drážky, tak do otvoru v základní kostce vloží upínka 888_1013_A, která by tam tu trubku v drážce měla přidržet. Protože si myslím, že když vytvořím pevné výstupky na základní části, tak si nedokážu představit, jak chceš trubku do drážky dostat. 

Ale pokud by ti tenhle opět můj divný inovativní způsob nevyhovoval, tak to předělám :).

**Comment by kaklik** [comment]
Myslím že mi to úplně vyhovuje. :)  
Vyndavací upínka je dobrý nápad, protože ta trubka by tam sice šla vložit, protože by se dala v rovném stavu nasunout do drážky. Ale pak by po ohnutí zřejmě už nešla vyndat a to mi úplně nedošlo. :)
Takže tam upínky nech tak jak je máš, jenom je udělej masivnější, protože takhle dimenzované by se při ohýbání asi ulomily. :)

Ještě teď přemýšlím nad tiskem. Nešlo by tu základnu nějak snížit a udělat jí rovnou místo zkosené? Ušetřilo by se tím hodně tiskového času.  Taky by asi bylo dobré, aby v základně byly díry na zapuštěné šrouby, kterým to přišroubuji na nějakou desku.

**Comment by Elizaa62** [comment]
Takže :D do přípravku jsem vytvořila zbytek upínek a udělala jsem je masivnější, jak sis přál. 

Základnu jsem udělala rovnou, ale ještě jsem ji vyvýšila kvůli své nové inovaci, a přidala jsem otvory na čtyři šrouby o velikosti M3.

Dále jsem připravky ozrcadlila pro levou podvozkovou trubku.

A teď další inovace :D díl 888_1013_F.. Je to pro ohyb 1 a pro ten úhel. Je to přípravek, který se bude tisknout samostatně a na díl 888_1013_B se přidělá šrouby. Doufám, že by to mohlo fungovat.

To je zatím vše, co jsem zvládla vytvořit.

**Comment by kaklik** [comment]
Myslím, že ta část pro ohyby 2 a 3 už bude fungovat :)  
Prohlédl jsem si podrobněji ten díl F pro ohyb 1 a myslím si, že ten by bylo potřeba vylepšit. Protože tak jak je konstruovaný zřejmě nepůjde ohnout trubka do toho žlábku. 

Navrhoval bych pro ohyby 1 a 4 vytvořit separátní přípravek. Do kterého se dá podvozková noha už s vytvořenými ohyby 2 a 3. Pak by se ohyby 1 a 4 vytvořily najednou ohnutím celé trubky. (Doufám, že to půjde, protože ohnout dvě trubka najednou může být dost těžké)

Tím pádem se může podstatně zmenšit tloušťka základny pro přípravek na ohyby 2 a 3. Takže se to bude podstatně lépe a rychleji tisknout. 

Samostatné přípravky pro ohyb 1 a 4 pak mohou být zase šroubovací naležato na desku. Takže taky nebudou muset být tak masivní.  Navíc nepotřebují svorky, protože mohou držet rovnou část trubky proti desce a trubka se prostě zasune mezi ně a desku.  Pak se celá noha ohne nahoru od desky a zas se vyndá.

**Comment by Elizaa62** [comment]
Vytvořila jsem nový přípravek pro ohyb 1 a 4. Podle toho, co teď čtu, tak asi zase bude špatně.

**Comment by kaklik** [comment]
K tomu, aby to bylo dobře stačí ty ohyby otočit o 90 stupňů a posunout tak, aby trubka byla při ohýbání zapřená o desku. Celé kvůli tomu, aby bylo možné přípravky našroubovat na dřevěnou desku.  A zasunout do nich polotovar nohy s ohyby 2 a 3. Pak se polotovar ručně ohne od desky a tím vzniknou najednou oba ohyby 1 a 4.

**Comment by Elizaa62** [comment]
Upravila jsem přípravek pro ohyb 2 a 3 a o 90°jsem otočila přípravek pro ohyb 1 a 4. Přípravky pro ohyb 1 a  4 mají kódy G, H, I, J.

**Comment by kaklik** [comment]
Díval jsem se na tohle

![image](https://user-images.githubusercontent.com/1194177/41103150-ba489654-6a68-11e8-8774-c82df069a9da.png)

Je to zas trochu lepší.  Akorát ty ohybací přípravky pro ohyby 1 a 4 nebudu mít čím přišroubovat na desku. 
Myslel jsem to tak, že trubka bude před ohybem držená deskou. To znamená, že trubka musí být strčená mezi desku a přípravek a pak se ohne tak, že se celá podvozková noha ohne nahoru směrem od desky. 

Aby se to vyřešilo, tak stačí kostku s dírami pro šrouby posunout na protější stranu přípravku a trubku do přípravku zapustit, tolik že nebude přečnívat přes přípravek.  Pak to půjde přišroubovat a trubka tam přitom půjde zatrčit a ohnout.

**Comment by Elizaa62** [comment]
Opraveno.

**Comment by kaklik** [comment]
Paráda.  To by myslím mohlo fungovat, zkusím to vytisknout a uvidíme. :)

![image](https://user-images.githubusercontent.com/1194177/41410904-4b85bf4e-6fdb-11e8-9c69-d75e917461da.png)

**Comment by Elizaa62** [comment]
Jak to vypadá? :)

**Comment by kaklik** [comment]
Já to minulý týden vytiskl, pak ještě trochu upravil a zase vytiskl. 
O víkendu jsem to ale nedokázal vyzkoušet. Složit všechno v jednom člověku je hodně náročné. 

Vyrobil jsem teď pull-request  #140 , který zahrnuje moje změny.

**Comment by kaklik** [comment]
Zjistil jsem že do ohýbacího přípravku podvozkové nohy nejde zasunout trubka.  Důvod je ten, že drážka pro ohyb obepíná víc než polovinu průměru trubky. 

![image](https://user-images.githubusercontent.com/1194177/43407598-75c479ae-941f-11e8-8c88-ab5dddb668bb.png)

Zřejmě se musí zapuštění trubky nějak posunout, aby to tak nebylo.

**Comment by kaklik** [comment]
Zde se sice trochu změnil tvar podvozkových trubek, ale potřeba ohybacího přípravku zůstala zachována.

**Comment by Elizaa62** [comment]
Máš nějaké rozměry k novému ohýbání podvozkových trubek?

**Comment by kaklik** [comment]
Rozměry bohužel nemáme, protože jsem to řešil hodně operativně a prostě jsem ty trubky ručně ohnul.  Ale myslím si, že délka trubky měřená od ohybu pasujícího do příčné trubky na konec na který je namontovaný kolečko je 180 mm. 

Přesné rozměry by ale měly vypadnout z opravené sestavy  #166 Protože když vírník bude stát na kolečkách, tak horizontální trubka má být vodorovně.

**Comment by Elizaa62** [comment]
Mohl bys mi prosím poskytnout nějaký obrázek toho, jak jsou nyní zohýbané ty podvozkové trubky? Abych si mohla udělat nějakou představu o tom, jak mám ten přípravek vyřešit?

**Comment by kaklik** [comment]
![20190127_165946](https://user-images.githubusercontent.com/1194177/52168536-c5602400-272b-11e9-9714-bd129d8d37c7.jpg)
![20190127_165853](https://user-images.githubusercontent.com/1194177/52168551-d872f400-272b-11e9-826f-005b4fafc8ed.jpg)

**Comment by kaklik** [comment]
Outdated.
