### ISSUE TITLE
Doplnění krytu serv na ocasní plochy 666_1028

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#120]
Na ocasní plochy by bylo vhodné doplnit směrové kormidlo.  Představuji si to tak, že se z té [vertikální části ](https://github.com/Elizaa62/Components/blob/666ccad877da8d21d0e17a7196edd2776f502717/src/666_1028.scad#L99)dílu 1028 vydělí menší část. 
Která bude uchycená na čepech, takže s ní půjde otáčet.  Otáčení bude zajišťovat [servo BMS-106HV](http://www.blue-bird-model.com/products_detail/56.htm), zapuštěné ve zbývající ploše směrovky.  Spojení serva a směrového kormidla vyřeší pevné táhlo otočně spojující páky na směrovém kormidlu a na servu.

![Servo použité pro ovládání](https://www.jino.cz/data/productslists/1/plp/14967/click/5a757e31bc18f.jpg)

Trochu jsem hledal jestli nenajdu fotografii takového řešení, ale nic vhodného jsem nenašel.  Takže jsem se to pokusil alespoň zjednodušeně nakreslit: 

![smerovka](https://user-images.githubusercontent.com/1194177/39072042-820b436c-44e9-11e8-84ec-833658b12f00.jpg)

Jsou to různé pohledy.  Otočná část je v tomhle případě vyklopená, aby bylo vidět, jak se to asi má hýbat. 
Servo je umístěné uvnitř vertikální nepohyblivé části směrovky.  Páka serva je prostrčená štěrbinou skrz vnitřní stranu směrovky. Servo je uchyceno v rámečku vymodelovaném uvnitř profilu směrovky.  Celý otvor pro servo pak překrývá nacvaknutý kryt.

Protože je to složitá úprava, tak to bude chtít rozdělit na několik dílčích kroků: 

- [x] Oddělení otočné části směrovky
- [x] Usazení na čepy, aby se mohla otáčet
- [x] Vymodelování páky za kterou bude servo tahat
- [ ] Doplnění výklenku a rámečku na umístění serva uvnitř profilu
- [ ] Vytvoření průchodů pro kabelový svazek

**Navrhuji to realizovat jako úplně nový díl do nového souboru, aby jsme nerozbili ten stávající funkční.**

**Comment by kaklik** [comment]
Trochu jsem hledal jestli náhodou už neexistuje hotový model pro uchycení serva, který by bylo možné rovnou použít a nic jsem nenašel. 
Způsob montáže by ale myslím měl vypadat nějak takhle: 

![](https://images2.sw-cdn.net/product/picture/710x528_1406507_1251797_1459320195.jpg)

**Comment by Elizaa62** [comment]
Vytvořila jsem v dílu 666_1028 otvor pro směrovku.

Směrovku samotnou jsem vytvořila v dílu 888_1010.scad. Je zadefinovaná globálními parametry začínající "Rudder..."

**Comment by kaklik** [comment]
Další krok je vytvoření otvorů a závěsů pro čepy na kterých se bude oddělený díl otáčet.  Asi bych navrhoval řešení, že čep se zasune jeden skrz díru přes celou délku směrovku až dolu.  Protože když se použije [uhlíková tyčka](https://www.peckamodel.cz/produkt/stavebni-materialy-a-modelarska-guma/uhlikove-kulatiny/61012-uhlikova-kulatina-1-2-mm), tak hmotnost bude zanedbatelná a možná se to nebude muset ani lepit.

Potom je potřeba na otočnou část vymyslet páku.  Netisknuté provedení vypadá nějak takhle: 
![](https://kolmanl.info/images/img_7176.jpg)
V našem případě to bude asi nějaký šikmý tvar, aby to šlo tisknout jako výstupek. Celá tahle mechanizace by asi měla být z té strany, co je trojúhelník pro spojení s hlavní trubkou, aby byla menší, šance, že to někdo utrhne.

**Comment by kaklik** [comment]
Našel jsem rozměrový výkres serva 

![](http://www.blue-bird-model.com/upload/201706051340179w3uc3.png)

Taky jsem zkoušel hledat jestli neexistuje náhodou rovnou jeho model do OpensCADu, ale žádný jsem nenašel.  Objevil jsem ale model podobného serva, tak z něj snad půjde vyjít a upravit jej. 

![image](https://user-images.githubusercontent.com/1194177/39074022-223fe65c-44f0-11e8-80ef-ecf8f7f9bf43.png)

Model jsem zatím přidal k sobě do repozitáře.
https://github.com/kaklik/Components/blob/master/src/lib/servo.scad

**Comment by Elizaa62** [comment]
Vytvořila jsem nový soubor 888_1012.scad. Je zde vyrobeno servo 888_1012_A a upevnění serva 888_1012_B a 888_1012_C. 

V souboru 888_1010.scad jsem znázornila otvor a servo.

**Comment by kaklik** [comment]
Ano! :)  Líbí se mi, jak jsi vymyslela to řešení šikmé páky pro připojení serva přes táhlo na pohyblivou část. 
Také je fajn, že jsi vytvořila takhle detailní model serva a rámeček pro jeho uchycení. :)
U toho modelu 888_1010 mě nenapadlo, že by servo mohlo být umístěné takhle.  Protože na servu bude na hřídeli nasazená páka (je jich v balení serva několik druhů), tak servo může být utopené uvnitř profilu, aby nad povrch vyčnívala jenom páka. Tloušťka profilu se dá klidně zvětšit, aby servo mohlo být zapuštěné celou svojí šířkou..

**Comment by Elizaa62** [comment]
Já pochopila, že to servo chceš takto umístit, z té skici, cos mi kreslit na papír. Je tady někde výše zobrazená.

**Comment by kaklik** [comment]
Taky by to servo tak mohlo být, ale lepší by bylo ho zapustit, aby se snížil aerodynamický odpor. Asi jsem tu skicu měl nakreslit lépe.

**Comment by Elizaa62** [comment]
Pochopila jsem z té skici, že to servo má být celé zapuštěné. Ale problém je v tom, že to nepůjde. Tloušťka serva je větší než tloušťka dílu, kam se má servo zapustit.

**Comment by kaklik** [comment]
To vím, ale tu tloušťku dílu si definujeme my. To znamená, že tloušťku dílu lze zvětšit tak, aby servo zapuštěné bylo.

**Comment by kaklik** [comment]
Na otočné uchycení směrovky jsem objednal tohle: http://www.pkmodelar.cz/stavebni-materialy-uhlik-tycky/uhlikova-tycka-2-0mm-1m-a1030 

Táhlo mám v plánu vyrobit z tohoto: http://www.pkmodelar.cz/stavebni-materialy-uhlik-tycky/uhlikova-tycka-3-0mm-1m-a1040 v kombinaci se závitovou koncovkou: http://www.pkmodelar.cz/stavebni-materialy-koncovky-tahel-na-uhlikova-tahla/zavitova-koncovka-hlinik-m2-uhlik-3mm-5-gf-2103-001

Výhoda tohoto řešení je, že pak jdou použít páky s ložisky: http://www.pkmodelar.cz/prislusenstvi-letadla-bizuterie-paky/2233-paka-mala-s-lozis-2ks-dlouha-1mp0020  a závitová koncovka umožňuje přesné doladění délky táhla.

**Comment by Elizaa62** [comment]
Zvětšila jsem tloušťku dílu z  naca = 0005 na naca = 00010 a zapustila servo v celé jeho výšce. Mohl bys prosím zkontrolovat, zda to zvětšení tloušťky a zapuštění serva je v pořádku?

**Comment by kaklik** [comment]
Ano, řekl bych, že je to tak správně. :)  Jenom v tom profilu chybí okénko na táhlo a páku serva.

**Comment by Elizaa62** [comment]
Myslíš v tom profilu, jak je v něm umístěno to servo?

Takže v tom profilu mám vytvořit okénko, do kterého se vloží držáček se servem? Ten držáček se bude šroubovat k tomu profilu? 

Okénko na táhlo.. To mám chápat tak, že to táhlo je připojené z jedné strany na to servo za tenhle výstupek jak jsem zobrazila na obrázku? Takže to okénko bude vlastně vedle okénka pro servo?

![image](https://user-images.githubusercontent.com/31339298/40602256-3f64e05e-6258-11e8-8cb7-518a23a6ec0c.png)

Okénko na páku serva se myslí kde?

A ještě k tomu přidělání té směrovky.. Jak tam tedy mám přesně udělat ty otvory? Popravdě, už si moc nepamatuji, jak jsme se přesně domlouvali na tom upevnění...

Vím, že tyhle dotazy jsou nejspíš úplně zcestné, ale potřebuju to pochopit, abych to udělala skoro správně a nemuseli jsme to několikrát předělávat.

**Comment by kaklik** [comment]
V pořádku, pokusim se to vysvětlit. :) 

Ano, v profilu ve kterém je umístěno servo je potřeba okénko jak na páku serva a z druhé strany na celé servo.

Ano, páka se nasazuje na tu otočnou hřídel serva, kterou si na obrázku znázornila šipkou. 
Okénko na táhlo a okénko na páku je jedno a to samé. (Je to prostě horizontální štěrbina ve které se pohybuje páka serva)

Uchycení otočné části směrovky:  To bude vyřešené uhlíkovou kulatinou průměru 2mm, která povede přes vertikálně celou výšku směrovky. Na ní se bude otáčet pohyblivá část.

Celé se to bude skládat tak, že: 

1.  Vezme se servo, na něj se nasadí páka a pojistí šroubem (páka je v balení serva)
2.  Vezmou se vytištěné díly a do nich se nasadí servo, případně se nasadí do držáku serva a celé se to zasune do pevné části směrovky, tak že páka nasazená na servo se prostrčí skrz okénko na protější straně než ze které se vkládá servo. (servo se vkládá z vnější strany směrovky)
3. servo a držák serva se zajistí šrouby, tak aby servo bylo pevně uchycené ve směrovce. 
4. na část páky která vyčnívá se nasadí vidlička a táhlo. 
5. pohyblivá část směrovky se vloží do výřezu v pevné části a shora se do vertikálního otvoru nasune kulatina, která se prostrčí skrz pohyblivou část až dolu.
6. táhlo se sešroubuje s pákou na pohyblivé části směrovky.

**Comment by kaklik** [comment]
![tahlo_1](https://user-images.githubusercontent.com/1194177/40657048-b850a1b2-6346-11e8-832c-10632ea128be.jpg)
Páka kormidla musí být na kormidlo namontována tak, aby osa čepu táhla procházela osou otáčení kormidla (osou pantu).

**Comment by kaklik** [comment]
V noci jsem snížil tloušťku profilu ve kterém je uložené servo z 10% na 9% a některé pevné hodnoty jsem nahradil výpočtem.  Sloučil jsem otočnou a pevnou část směrovky do souboru 666_1028, abych mohl měnit parametry najednou. 
Teď se tiskne první výtisk na kterém zjistím co všechno nesedí.

**Comment by kaklik** [comment]
Tak jsem složil výsledek z prvních vytištěných dílů. A uvědomil jsem si, že je to vlastně docela dobré. :)

Ta otočná část směrovky funguje jak má. Servo se sice sotva vejde do svého výklenku, ale šlo to poladit pilníkem (chybělo asi jenom 0.4mm na výšku pro páku serva).

Pak jsem zjistil, že vytištěná páka na pohyblivém dílu asi nebude dobrý nápad, Protože tisk nedosahuje potřebné kvality.  Vyřeší se to tak, že se tam našroubuje páka, která se dá koupit jako díl:

![](http://www.pkmodelar.cz/_shopimg/13/6507/big/0.jpg)

Má to tu výhodu, že je to výrazně přesnější díl a navíc je tam ložisko.  Jenom musím nějak zjistit rozměry, aby se pro to dala ta směrovka lépe připravit. 

**Rámeček pro servo by zřejmě měl být součástí přímo toho výklenku pro servo v pevné části. Ta druhá část by se vytiskla separátně a přiklopilo by se s ní servo potom, co se umístí do výklenku.**

**Comment by kaklik** [comment]
Tak při pokusech se startem a přistáním se ukazuje, že ocasní plochy jsou docela spotřební materiál.  Z toho zřejmě vyplývá, že by montáž serva měla být co nejjednodušší. 
A současné řešení, které jsem použil - zalepení serva tavným lepidlem není vůbec dobrý nápad..

**Comment by kaklik** [comment]
![20180611_142650](https://user-images.githubusercontent.com/1194177/41231730-5b6fc2dc-6d84-11e8-9517-f0894ee21355.jpg)


Pro shrnutí je potřeba

1. Překontrolovat rozměry rámečku pro servo
2. Rámeček integrovat do pevné části směrovky, zvětšit současný montážní otvor minimálně o 1mm směrem nahoru. 
3. Víčko rámečku upravit tak, aby kopírovalo tvar směrovky. 
4. Vytvořit kanálky v profilu pro protažení přívodního kabelu od serva do hlavní trubky.

**Comment by Elizaa62** [comment]
Pokusila jsem se překontrolovat rozměry pro servo. Mělo by to snad sedět do rámečku. 

Rámeček jsem vložila do otvoru ve směrovce tak, aby se tisk dohromady s ocasní plochou. Akorát jak myslíš to zvětšení o 1 mm nahoru? Chceš to celé posunout výš, tak aby bylo ve dně více materiálu?

**Comment by kaklik** [comment]
S tím zvětšením to myslím tak, že v současném modelu musím vždycky v horní části otvoru pro servo nahoře pilníkem vykousat kus materiálu, abych tam to servo byl schopen vložit i s pákou. Na následující fotce je to vidět jako ten ošklivý zub v horní části výklenku: 

![20180612_122045](https://user-images.githubusercontent.com/1194177/41290531-74a86eec-6e4d-11e8-954f-34409a737e69.jpg)

**Comment by kaklik** [comment]
Díval jsem se na aktuální rámeček pro servo v souboru 888_1012. Vidím tam tohle:

![image](https://user-images.githubusercontent.com/1194177/41341934-4914559e-6efb-11e8-847b-5a5873dc7743.png)

Přijde mi, že tam není vyřešená ta primární příčina, proč servo do rámečku nepasuje, a to ta, že v rámečku jsou některé části serva zapuštěné a jiné nejsou.  
Ještě to můžu zkusit vytisknout, ale myslím si, že to bude hodně podobné minulému výsledku.

**Comment by Elizaa62** [comment]
Takže pokud to dobře chápu, tak chceš ten hlavní otvor v rámečku mít menší a do toho rámečku má být zapuštěný i ta hlavní část toho serva?

**Comment by kaklik** [comment]
Myslím že ne,  použití toho rámečku vadí to, co je vidět na téhle části obrázku: 

![image](https://user-images.githubusercontent.com/1194177/41358923-acd6fff4-6f29-11e8-8c9f-d9234ff90e85.png)
 
Servo je placaté, ale víčko rámečku je na některých místech vybrané pro zapuštění serva a jinde (ve vetšině plochy), není. To způsobuje, že servo do rámečku nejde zacvaknout, protože chybí  tloušťka rámečku, která není vybraná pro servo do stěny. To je zas vidět na fotce rámečku se servem výše.

**Comment by kaklik** [comment]
Ještě bych chtěl dodat, že víčko, kterým se má servo zakrýt po umístění do směrovky musí mít logicky tvar povrchu té směrovky. Protože výsledkem má být, že víčko serva se ve směrovce "ztratí".

**Comment by Elizaa62** [comment]
Přidala jsem na net díl 888_3014.scad. Je to snaha o víčko pro servo. Prosím o vytisknutí a vyzkoušení, zda víčko pasuje.

**Comment by kaklik** [comment]
Jo to vypadá, že by  mohlo pasovat. Akorát nevim, jak to mám vytisknout, protože to není ani z jedné strany placaté a na hraně to asi stát nebude.  :)

**Comment by kaklik** [comment]
Aby to šlo vytisknout, tak je na jednu stranu potřeba vymyslet nějaký lem za který to během tisku bude držet na podložce.

**Comment by Elizaa62** [comment]
Přidala jsem podpěry pro tisk.

**Comment by kaklik** [comment]
Tak takhle konstruované víčko vypadá, že vytisknout jde. :) 

![vicko](https://user-images.githubusercontent.com/1194177/53960618-0363b580-40e7-11e9-8cce-ad92e8d28c6b.jpg)

Jestli i pasuje ale nevyzkouším, protože k němu zřejmě ještě není vymodelovaný protikus v dílu 666_1028. 
Mohu akorát ještě zkusit, jesti se mezi dva šrouby vejde servo.

**Comment by kaklik** [comment]
Tak bych řekl, že podpěry pro tisk překáží vodu vodičů ze serva a víčko tak zřejmě nepůjde domáčknout. 

![servo_vicko](https://user-images.githubusercontent.com/1194177/54154748-eb6f9700-4442-11e9-84ea-1a3a4064c071.JPG)

**Comment by kaklik** [comment]
Našel jsem variantu serva, která má montážní otvory naplocho. Myslím, že by to mohlo zjednodušit konstrukci modelu a usnadnit montáž. 


![](https://www.jino.cz/data/productslists/1/plp/15195/click/5ba5fd41ecc5f.jpg)

Víčko montážního otvoru pak může využívat úplně stejné šrouby, které budou držet servo.

**Comment by Elizaa62** [comment]
Já jsem původně plánovala, že by se ty podpory nějak vylomily... Že by tam nezůstávaly... 

Jsi si jistý, že to servo patří takto? Nepatří to servo náhodou opačně? Nezkoušel jsi to? Já si tím teď totiž nejsem jistá...

V případě serva s plochými montážními otvory:
-> to má stejné rozměry? Případně stačí jen umístění šroubů pro upevnění serva, abych mohla předělat víčko a na montáž serva i připevnění víčka se použily stejné šrouby.

**Comment by kaklik** [comment]
Mě se z toho vytištěného modelu ty podpěry tentokrát nedaří vylomit. Drží tam tolik, že bych pravděpodobně poškodil ten model. 
Je možné, že kdyby se mi je odsud podařilo dostat, tak by to pasovalo více. Navíc by servo tam pravděpodobně skutečně šlo dát vzhůro nohama, než je na té fotce. 

Servo s plochými montážními otvory má stejné rozměry. Liší se pouze těmi uchy pro přichycení šrouby. Výkres, který jsem k tomu našel vypadá takhle: 

![](https://www.hyperflight.co.uk/img/p/blue-bird-bms-115hv-servo-10-2kg-cm-0-10s-21-0g-13mm-40.jpg)

 Některé kóty tam sice chybí. Ale očekávám, že ty uši jsou zarovnané se středovou osou serva a ve stejné výšce jako ty původní horizontální montážní otvory.

**Comment by kaklik** [comment]
Tak jsem ta dvě serva dal k sobě a vyfotil, aby byl vidět rozdíl mezi nimi. 

![DSC02469](https://user-images.githubusercontent.com/1194177/57195612-0519f000-6f55-11e9-8e54-38c6b9821607.JPG)

![DSC02470](https://user-images.githubusercontent.com/1194177/57195616-0ba86780-6f55-11e9-8a3d-bb37aef163b0.JPG)

![DSC02471](https://user-images.githubusercontent.com/1194177/57195622-14993900-6f55-11e9-8d56-0a545ba2271d.JPG)
