### ISSUE TITLE
Připevnění dílu 666_1032 k vertikální trubce

### ISSUE THREAD

**Issue by Elizaa62** [Elizaa62/Components#122]
V dílu 666_1032 jsem vytvořila nějaký pokus o připevnění k vertikální trubce. Je to otvor velikosti M4 a na každé straně je kužel. V jednom je otvor pro matku a ve druhém otvor pro hlavu šroubu.

**Comment by kaklik** [comment]
Myslím, že je to v principu dobré řešení. Jenom by to bylo potřeba nějak uzpůsobit, aby šrouby nerozmáčkly kryt, když se stáhnou k trubce.

**Comment by Elizaa62** [comment]
Opraveno.

**Comment by kaklik** [comment]
Myslím, že to funguje jak se dalo předpokládat.

![20180427_080053](https://user-images.githubusercontent.com/1194177/39349245-87db060e-49fa-11e8-8ead-bbaf5f1cba54.jpg)
