### ISSUE TITLE
Vyvažovací přípravek na rotorové listy

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#125]
Výchozí představa o fungování přípravku je taková, že rotorový list se bude v přípravku posouvat tak dlouho až bude vyvážený. Osa přípravku pak umožňuje na listu vytvořit značku.  Otočením listu symetricky o 45stupnu na druhou stranu a opětovným nalezením rovnováhy lze najít polohu těžiště ve dvou osách.

![image](https://user-images.githubusercontent.com/1194177/39089029-c63e39e8-45bd-11e8-9bfd-1003ffe23ad2.png)

Přípravek má několik hlavních dílů. Základnu s bublinkovou vodováhou, kolébku pro upnutí listu a posuvné fixační členy. Kolébka se na základně otáčí na hrotech, které dosedají do výřezů v základně.

![Základna vyvažovacího přípravku](https://user-images.githubusercontent.com/1194177/39125310-cf249a60-46fe-11e8-84ad-08cc5d1516c4.jpg)

![Detail hrotu na dosedací ploše základny](https://user-images.githubusercontent.com/1194177/39143448-3ac3f20a-472e-11e8-85c4-acba7e681b0b.jpg)

Kolébka do které se upíná list má dva tvarové posuvné členy, které slouží k zafixování listu. V ose přípravku jsou dva šrouby, kterými lze posuvné členy zafixovat a zároveň slouží k nasunutí měřítka, umožňujícího vytvořit na listu rysku. 
![Kolébka pro upnutí listu](https://user-images.githubusercontent.com/1194177/39125328-dc00ab02-46fe-11e8-8fcd-41ee6aaeade3.jpg)

**Comment by kaklik** [comment]
Vytvořil jsem dva trojúhelníky na zafixování pozice listu. 

![888_1009](https://user-images.githubusercontent.com/1194177/39157919-78430df8-475d-11e8-8c57-43eb4b027917.png)

**Comment by Elizaa62** [comment]
A kam jsi to dal? Je to potřeba vyzkoušet jako celek, protože se obávám, že se ten list do toho přípravku nevejde.

**Comment by Elizaa62** [comment]
Vložila jsem na ten tu základnu a kolébku.
