### ISSUE TITLE
Otvory pro spojky trubek v podložce

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#129]
Při skládání prvního kusu jsem narazil na komplikaci, že šrouby ve spojkách 666_1004 přesahují přes obrys spojky. Díky tomu podložka nešla nasadit na sešroubovanou kostru z trubek. Šrouby, které jsem použil byly DIN912 M3x35.
Zajímavé je, že přesahovaly symericky jak hlavičkou, tak i koncem šroubu přes matku. Vyřešil jsem to tak, že jsem do podložky pilníkem vypiloval drážky, v otvorech pro spojky.  Takže přesahující šrouby byly v drážce, podložka pak už šla na spojky nasadit.

U spojky 666_1017 byla situace jiná. Tam jsem sice použil stejné šrouby, ale výsledek byl takový, že hlava šroubu zapadla přesně do šestihranného zapuštění tak, že nepřečnívala přes povrch. Šroub ale v důsledku toho více přečníval na druhé straně za matkou. Tady jsem to vyřešil tak, že jsem šroub ubrousil na délku, která je zároveň s matkou. 

Správné řešení celé situace zřejmě je:

- [x] Sjednotit hloubku šestihranného zapuštění na všech spojkách tak, aby do něj vždy zapadla celá hlavička šroubu.
- [x] Vymyslet, jak by šlo zajistit, aby do spojek pasovaly šrouby v délkách, které se vyrábí.

**Comment by kaklik** [comment]
Ty délky šroubů by zřejmě šlo vyřešit tak, že se podle vypočteného rozměru spojky (Tak jak to funguje teď) odhadne nejbližší násobek 5ti. 
Šrouby se v těchto délkách vyrábí s odstupem 5mm viz: https://www.valentazt.cz/imbusove-srouby.html
A rozměr spojky se pak upraví do nejbližšího násobku.

**Comment by Elizaa62** [comment]
K bodu 1: Zapuštění jsem u spojek zkontrolovala a nikde problém nevidím. Dle mého názoru je problém v tom, zda sis zkontroloval výšku hlavičky šroubu s hodnotou, která je v Parameters.scad. Hodnota Nut_height_M3 musí být větší než hodnota výšky hlavičky šroubu. Pokud není, tak je jasné, že hlavička bude přečnívat.

**Comment by kaklik** [comment]
Takže myslíš, že je možné, že bych měl vytištěné různé díly v různých verzích s různým nastavením výšky Nut_height_M3 ? No asi se to stát mohlo, v tom případě bude u nových dílů hlavička zapuštěná celá a bude přečnívat šroub na druhé straně, jak se to stalo u spojky pro vertikální trubku, která byla tištěná jako poslední.

**Comment by Elizaa62** [comment]
To je možné, protože vím, že už jsem jednou kontrolovala zapuštění tak aby bylo všude stejné. Tak je pravděpodobné, že máš vytištěné ještě staré verze. Protože teď při kontrole nebylo k opravě skoro nic. 

A musí se zkontrolovat výška Nut_height_M3, protože jak koukám na ten odkaz https://www.valentazt.cz/imbusove-srouby.html, tak hodnota "k", což je výška hlavičky šroubu, je u šroubu M3 3 mm a my máme v Parameters.scad pro Nut_height_M3 hodnotu 2,7 mm. Takže i kdybys teď vytiskl novou spojku, tak hlavička bude přečnívat u M3 o 0,3 mm.

**Comment by kaklik** [comment]
Tady je zřejmě asi ještě rozdíl v tom, že hlavička a matka má vlastně jinou výšku, ale to není potřeba řešit, protože ty 0.3mm se ztratí. Ten díl se totiž při dotažení šroubu poměrně výrazně zdeformuje, takže hlavička reálně nepřečnívá. 
Na straně matky je to ale opačně, tam naopak s větším dotažením šroub více vyčnívá. Což znamená že díl musí být zřejmě o nějakou malou toleranci širší, než je celková délka šroubu.

**Comment by Elizaa62** [comment]
K té délce šroubů. Délka šroubu se skládá z délky šroubu + výšky hlavičky. Pro ilustraci na spojce 666_1004. Šířka této spojky je main_tube_outer_diameter + 2*coupling_wall_thickness = 25,4 + 2*(25,4/5) = 35,56.

![image](https://user-images.githubusercontent.com/31339298/40346278-96899b9c-5d9c-11e8-882c-5b3d99061df0.png)

Tento obrázek znázorňuje rozměry na šroubu. 

Pro spojku 666_1004, která je široká 35,56 mm, potřebuješ šroub o délce 32,56. Protože musíš od šířky odečíst výšku hlavičky 3 mm pro M3, která má být ve spojce zapuštěná. Zde bude zapotřebí šroub M3x35 a šířka spojky se bude muset zvětšit tak, aby byla 35+3 = 38 mm. Když budeš chtít použít šroub M3x30, tak se spojka bude muset zmenšit na 30+3 = 33 mm. 

U dalších spojek budou samozřejmě rozměry nejspíš jiné. Ilustrovala jsem to jenom na této. 

Tak navrhni, jak to mám změnit. Protože v případě, že se bude muset měnit šířka spojek kvůli šroubům, tak to znamená změny i v ostatních modelech.

**Comment by kaklik** [comment]
Ano, je to přesně tak.  Uvědomuji si že je to poměrně velká změna, protože se projeví na poměrně hodně místech.  Je to ale potřeba změnit, protože šrouby s délkou 32,56 mm nedovedu koupit.
Navrhoval bych postup rozměr spojky spočítat rovnou v souboru parameters.scad  a z vypočtené šířky spojky udělat proměnnou, která bude společná pro všechny soubory, kde se se šířkou spojky počítá. 

### Návrh způsobu výpočtu

Šířka spojky musí odpovídat rozměrům trubky, kterou je potřebné použít, proto první odhad šířky spojky je: 
main_tube_outer_diameter + 2*coupling_wall_thickness = 25,4 + 2(25,4/5) = 35,56.

Výška hlavičky šroubu je screw_head_height_M3  proto délka šroubu je: 
main_tube_outer_diameter + 2*coupling_wall_thickness - screw_head_height_M3 = 25,4 + 2(25,4/5) - 3 = 32,56 mm

Šrouby se ale prodávají v rozestupech  délky 5 mm je proto potřeba najít nejbližší větší délku šroubu. K tomu se použije matematická funkce [ceil](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/Mathematical_Functions#ceil), což je opak floor.  Nejbližší délka šroubu se pak spočítá takhle: 

32,56 / 5 = 6,512

ceil(6,512) = 7

coupling_screw_length = 7 * 5 = 35

coupling_width = coupling_screw_length + screw_head_height_M3 = 38 

Použil jsem tu přímo čísla, aby  bylo vidět co to má dělat,  ale reálně to budou všechno proměnné.
Zároveň jsem zavedl novou proměnnou screw_head_height_M3 = 3 mm (podle tabulek) 
Matky na šroubech bych ale navrhoval zapustit taktéž o rozměr screw_head_height_M3, neboť u matky která je tenčí (2.7mm) nabude vadit, že bude zapuštěná více.  Bylo by ale hodně nepraktické, kdyby spojka byla asymetrická.

**Comment by Elizaa62** [comment]
Podle tvého návrhu jsem opravila spojky 666_1004, 666_1017 a 666_1026. Přičemž u prvních dvou spojek je šířka včetně výšky hlavičky šroubu. Otvory pro hlavičky šroubů a pro matku jsou sjednoceny stejnou výškou "Screw_head_height_M3". 

U třetí spojky je hlavička šroubu i matka mimo spojku, tudíž pro šířku matky jsem použila výpočet normalizované délky šroubu od které jsem odečetla výšku hlavičky šroubu "Screw_head_height_M4", aby šroub přečníval a bylo na něj možné nasadit matičku.


Podle těchto nových spojek jsem opravila i otvory v dílu 666_1027.

**Comment by kaklik** [comment]
Paráda, podívám se na to. :)

**Comment by kaklik** [comment]
Tak myslím, že to funguje dobře. Mám radost, že jsi to zvládla vyřešit. :)

Myslíš, že je lepší ty rozměry počítat takhle pokaždé znova? Já si právě říkal, že by možná bylo lepší, ten výpočet provést rovnou v tom společném souboru parameters.scad.  Aby si to každý model nemusel počítat samostatně.

Ta spojka 666_1026 je pro tenhle výpočet problematická, protože je právě jiná tím, že se  šroub nezapouští. Ale jsou na něm ještě plechy a podložky a jsou to díly, které nejsou nakreslené v openscadu, takže jejich rozměry se zatím nedají automaticky měnit. To se ale doufám jednou stane. Takže ten výpočet tam zatím nech. Jenom by teď bylo potřeba, aby  dočasně dával konstantní šířku spojky 666_1026  **50mm**.  To můžeš udělat například tím, že odečteš ještě vhodnou tloušťku plechů, aby to vyšlo.

**Comment by kaklik** [comment]
Mám k tomu nový poznatek - když jsem vytiskl podložku v tom stavu, co  je nyní na githubu a vypadá takhle: 
![image](https://user-images.githubusercontent.com/1194177/40914877-34961330-67fa-11e8-90ac-766699c2c907.png)

Tak to dopadlo tak, že zadní spojka je teď příliš vzadu a nepasuje do toho původního rámu z trubek. (Vyřešil jsem to tak, že jsem tam pilkou vyřízl vetší díru.)

Nedovedu vyloučit, že jsem to nezpůsobil já svými úpravami jako posun akumulátorů a posun díry pro prostřední spojku. Nicméně situace je teď taková, že to nepasuje dohromady s existujícím rámem a chtělo by to vyřešit.

**Comment by Elizaa62** [comment]
Už asi vím, kde vznikl problém s pozici zadní spojky. Jak se měnila šířka spojky tak, aby pasovala na normalizované šrouby, tak jsem změnila i parametr "second_undercarriage_hole" podle, kterého se zadní spojka umisťuje. 

Původně se počítal jako:
second_undercarriage_hole = main_tube_outer_diameter*2 + 2*coupling_wall_thickness + main_tube_outer_diameter + 170 + 160;

a teď se počítá:
second_undercarriage_hole = main_tube_outer_diameter*2 + coupling_width_666_1004 + 170 + 160;

Změnou je šířka spojky ->místo "main_tube_outer_diameter + 2*coupling_wall_thicknes" je zde "coupling_width_666_1004", která je samozřejmě větší. 

Proto nejspíš došlo k jinému umístění zadní spojky. Jinak si to nedovedu vysvětlit.
Takže to nejspíš asi mám opravit na to původní počítaní, že?

Jinak ještě k těm šířkám spojek dle normalizovaných šroubů.. Šířku spojky 666_1026 jsem udělala konstantní 50 mm, jak jsi psal výše. Použila jsem k tomu nový parametr "thickness_of_plate", který se počítá jako nová šířka spojky mínus konstantní šířka 50mm a tento parametr se pak odečte od normalizované šířky, abychom dostali konstantní šířku 50 mm.

**Comment by kaklik** [comment]
Aha :) To je fajn, že jsi na to přišla. 

Přemýšlím, jak by to mělo fungovat správně a myslím si, že ve skutečnosti by pozice těch dvou spojek (přední a zadní) měla být nějak dána délkou hlavní trubky.  Protože délka kapky a vůbec všeho bude potřeba větší s rostoucí délkou hlavní trubky. 

Navrhoval bych ale zatím to neměnit, dokud nedokončíme zkoušky s již vytištěnou podložkou. Tu posunutou díru jsem totiž využil na to, že jsem tudy protáhl kabely k servům na ocasních plochách. 

Takže nejvíc by mi teď asi pomohlo ten zadní otvor zvětšit o polovinu jeho současného rozměru směrem dopředu. Abych tam příště až tu podložku budu tisknout nemusel řezat pilkou. 

S tou spojkou 666_1026 jsi to vymyslela hodně dobře. :)

**Comment by kaklik** [comment]
Ten otvor pro zadní spojku by zřejmě chtělo upravit tak, aby za ním zůstalo místo pro kabelové prostupy do podélné trubky. Viz fotka: 

![dsc01279](https://user-images.githubusercontent.com/1194177/41586117-3a13bfb6-73ac-11e8-9f71-9411acc10b54.JPG)

**Comment by Elizaa62** [comment]
Změnila jsem parametr "second_undercarriage_hole" na původní výpočet, aby v tom nebyly další zmatky. Otvor jsem zvětšila o coupling_width_666_1004/2 a posunula o tuto hodnotu dopředu. Ten otvor na kabely tedy bude tedy velký coupling_width_666_1004/2 nebo chceš, aby byl velký jako uvádíš na obrázku?

**Comment by kaklik** [comment]
Paráda :) Otvor pro kabely může být klidně coupling_width_666_1004/2 protože předpokládám, že je to více než hodnota na obrázku a tím pádem se tam kabely vejdou.

**Comment by Elizaa62** [comment]
Dobře :)

**Comment by kaklik** [comment]
Tak jsem zjistil, že výpočet pozice zadní spojky ve skutečnosti nebyl navrácen na původní. Protože ta pozice zadní spojky je ve skutečnosti rozbitá mnohem déle.  A to konkrétně od tohoto commitu: 
https://github.com/Elizaa62/Components/commit/02fbde8e85179fd5ff120c0bf4c55bff340a4926#diff-1b45c2dfa8ef077ea9d609a18eb740e9

Přišel jsem na to tak, že když jsem si zobrazil tenhle náhled: 

![screenshot from 2018-07-19 12-24-52](https://user-images.githubusercontent.com/1194177/42938700-78f54c5e-8b53-11e8-9fa6-5530b649f41f.png)

Kde je vidět, že spojka je moc vzadu.  

Nyní jsem to myslím opravil tak, že jsem tam nastavil pozici před commitem, kde se to rozbilo. 
Zároveň jsem zavedl novou díru jenom pro kabely od serv na ocasu, kterou jsem posunul mezi vertikální trubku a zadní spojku. 

Takže teď to vypadá takhle: 

![screenshot from 2018-07-19 13-04-45](https://user-images.githubusercontent.com/1194177/42938942-5ea88d56-8b54-11e8-82d7-1785e80a40bc.png)

**Comment by kaklik** [comment]
Po tom co jsem do nové trubky vyvrtal otvory podle vrtacího přípravku 888_1014.scad jsem zjistil, že pasují všechny díry až na úplně přední díru pro šroub, který drží podložku na hlavní trubce. 
Díra je přibližně o polovinu průměru posunutá více dopředu, než by měla být.  Takže skrz podložku do ní nelze prostrčit šroub. 

Když jsem se pokusil jenom rychle zjistit, čím by to mohlo být, tak to vypadá, že je i nějak posunutá přední spojka pro podvozkovou trubku. 

![screenshot from 2018-07-24 12-13-07](https://user-images.githubusercontent.com/1194177/43132935-8677ce04-8f3d-11e8-8d5d-3ded485b4353.png)

Zřejmě se tedy otvory posouvají do pozic které jsou různé v přípravku a na podložce.  Je to ale divné, protože díry vypadají, že se posouvají podle stejných parametrů.

Otvor je v podložce umístěný podle: 
https://github.com/kaklik/Components/blob/4a4389497d42c02da4d14f9e1848017d990a3da6/src/666_1027.scad#L538

A v přípravku je umístění nastaveno jako: 
https://github.com/kaklik/Components/blob/4a4389497d42c02da4d14f9e1848017d990a3da6/src/manufacturing_helpers/888_1014.scad#L113

**Comment by Elizaa62** [comment]
Chyby plynou ze změněné šířky spojky 666_1004, jelikož se rozměry spojky mění podle délky šroubu. Všechny následující parametry pro umístění dalších spojek a dalších souvisejících komponent jsou uvedeny s pevnými parametry pro spojení. Pokusím se to opravit, ale změny se projeví ve více souborech.

Změny:
-> Parametr "second_undercarriage_hole" na height_1026 + height_1004/2 + 170  + 160. Musí se projevit změna šířky spojky 666_1004. Tudíž se mění pozice všech komponent závislých na parametru "second_undercarriage_hole" (otvory pro spojky v 666_1027, pozice podvozkových trubek)

-> pozice samotné spojky 666_1004, která je nyní height_666_1026 + height_1004/2.

-> 888_1008 - počátek podvozkových trubek je v ose x v height_666_1026 + height_1004/2.


Jinak jsem koukala na chybu, jak jsi popisoval výše, že nesedí vyvrtaný otvor pro první šroub s otvorem, co je v dílu 666_1027. Ale jediné, co jsem našla je, že jsem díl 888_1014 posunula o coupling_walll_thickness, aby díl začínal v počátku os. To je možná důvod proč ti to nesedí, tak jsem posunutí zrušila. Hodnota coupling_wall_thicknesss představuje tloušťku materiálu před horizontální trubkou.

**Comment by kaklik** [comment]
Asi to způsobí komplikace, protože budu muset přetisknout hodně dílů a udělat v podstatě nový kus. Zřejmě to ale potřeba opravit, aby se nám ten model nerozbíjel při změně souvisejících parametrů.

**Comment by Elizaa62** [comment]
Musela jsem to opravit, protože je zdlouhavé pořád přemýšlet nad tím, jak to je.

Pokud to tak nechceš, tak to opravím zpátky, ale bude to způsobovat další komplikace.

**Comment by kaklik** [comment]
Ne, já to tak právě chci. Je správně, že jsi to opravila. :)

**Comment by kaklik** [comment]
Ty spojky jsou zřejmě už správně. 
Zůstala ale nějaká divnost v pozicích příčných podvozkových trubek vůči spojkám. 
Je to vidět na tomto obrázku: 

![image](https://user-images.githubusercontent.com/1194177/46041906-4ec77000-c114-11e8-9f2c-7372166c67ee.png)

**Comment by Elizaa62** [comment]
Koukala jsem na model 666_2000 a žádný problém v pozici jsem neshledala..
Teď jsem koukala na model 888_1005 a tam ten problém je. 
Musíme se dohodnout, který model se bude používat! Podle toho to opravím.

**Comment by kaklik** [comment]
Budeme používat sestavu, která obsahuje méně chyb, tedy 666_2000.  Druhá sestava se může smazat.

**Comment by Elizaa62** [comment]
Jsou v tomto issue nějaké záležitosti, které potřebují vyřešit?

**Comment by kaklik** [comment]
Viděl jsem že druhá sestava je smazaná, takže je to zřejmě vyřešené.
