### ISSUE TITLE
Zkosení ocasních ploch shora a zdola

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#130]
Nyní čtvercové ocasní plochy by bylo potřeba zkosit o 10stupňů jak ze spodní tak i z horní strany. Důvody k tomu jsou následující.

1.  Ušetření hmotnosti 
2. Zjednodušení startu (ocasní plocha nebude při startu tak snadno dřít o zem)
3. Zvětšení prostoru mezi rotorem a ocasní plochou.

**Comment by Elizaa62** [comment]
Pokusím se ty plochy zkosit.. ale nedaří se mi tam dát to dno.

**Comment by Elizaa62** [comment]
Je to na netu.. nevím , zda jsem to pochopila správně...

**Comment by kaklik** [comment]
Dobrá, zatím je to bez dna.  Jak vypadal ten problém s jeho doplněním? 

Jinak to zkosení jsem myslel tak, aby se ten díl zužoval směrem dozadu.  V případě tohoto obrázku nahoru: 

![image](https://user-images.githubusercontent.com/1194177/48825556-ff926a00-ed67-11e8-85b0-c6ca948817fd.png)

**Comment by kaklik** [comment]
Issue se stalo irelevantní díky možnosti změnit celkovou konstrukci ocasních ploch.
