### ISSUE TITLE
Zlepšení odolnosti spojky pro vertikální trubku

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#139]
Při experimentech se ukazuje, že pevnost spojení vertikální trubky a horizontální trubky není příliš dobře dimenzována. 
Navrhoval bych proto dva šrouby změnit na M4 a ze spodní strany spojky přidat materiál a šroub M3, aby trubka byla spojkou lépe obepnuta. 

![spojka_1017](https://user-images.githubusercontent.com/1194177/41600339-f9871612-73d5-11e8-89d6-96eeed9a7131.png)

**Comment by Elizaa62** [comment]
Zvětšila jsem spojku pod horizontální trubkou o hodnotu "material_plus". Tato hodnota je uvedena přímo v kódu spojky 666_1017. Označené šrouby jsem změnila i s matkami na velikost M4. V přidaném materiálu jsem vytvořila otvor pro šroub M3.

**Comment by kaklik** [comment]
Prohlédl jsem si to a myslím, že to skutečně zlepší pevnost spojky.  
Jenom zvažuji, jestli konstantu material_plus nenahradit spíše tím, že spojka bude tlustší všude.  Například dvojnásobně, než ostatní spojky. 
Bude to mít sice vliv i na otvory v podložce, ale pevnost spojky by se tím zvýšila výrazně. 
Teď je totiž nepříjemné, že vertikální pylon se na podélné trubce poměrně snadno mele. Nevím jak moc to vadí, ale chtěl bych zkusit najít řešení takové, aby se pylon nemlel.

**Comment by kaklik** [comment]
Tak jsem přišel na komplikaci, která tedy zřejmě už existuje dlouho, ale teď je výraznější. 
Spojka totiž přesahuje pod spodní rovinu desky. Tím pádem tlačí na dva díly, které jsou určené pro náklad a prohýbá se tím stěna boxu pro náklad.  
Zřejmě je potřeba nákladový prostor nějak tvarově upravit, aby nevznikala kolize s touto spojkou.

**Comment by kaklik** [comment]
Zvětšil jsem tu tloušťku spojky tak, aby odpovídala dvojnásobku tloušťky ostatních spojek.  Potřebná délka šroubu pak je 45mm. 
![image](https://user-images.githubusercontent.com/1194177/42050418-3024d3e6-7b09-11e8-90e3-03ff436a1c99.png)

Nebylo to ale tak úplně jednoduché. Protože nestačilo změnit požadavek na tloušťku v parameters.scad Neboť kopie výpočtu délky šroubu byla pro mne nepochopitelně ještě v souboru samotné spojky. Tyto dva výskyty se pak navzájem přebíjely.  Řešením bylo smazat výpočet vyskytující se přímo u spojky.

 Když jsem se ale pak díval jak je to u ostatních spojek, tak to vypadá, že každá spojka má výpočet ještě u sebe.  Je k tomu nějaký důvod to takhle řešit?

**Comment by Elizaa62** [comment]
A jaké výpočty myslíš?  U spojky 666_1017 byl výpočet opravený, jen jsem ho asi zapomněla uvnitř samotného kódu smazat.

**Comment by kaklik** [comment]
No jde mi o to, že některé spojky ještě ve svém souboru obsahují třeba tohle:

https://github.com/Elizaa62/Components/blob/e773c52085e90c9cde41d03ff38ef7d4bda3eefb/src/666_1004.scad#L7-L19

U většiny jsem to už smazal a nechal jsem to akorát v souboru s parametry.  Protože když se to neudělá, tak nefunguje změna parametrů v souboru Parameters.scad neboť výpočet u samotné spojky má přednost.

**Comment by Elizaa62** [comment]
Opraveno 1004, 1014, 1017, 1026.

Je v tomto issue ještě nějaký další problém?

**Comment by kaklik** [comment]
Není, myslím, že je to vyřešené. :)
