### ISSUE TITLE
Rozbité podpory dílu D spodního krytu

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#141]
Nějak se stalo, že se rozbily podpory pro výřezy na podvozkové nohy v zadní části spodního krytu  a dil teď nejde vytisknout. 

![image](https://user-images.githubusercontent.com/1194177/42090147-7e7ac57c-7ba0-11e8-8d2c-a9fcc33ef15b.png)
 
Nevím přesně jak dlouho tato chyba existuje.

**Comment by Elizaa62** [comment]
Ať hledám, jak hledám, tu chybu tam nevidím.

**Comment by kaklik** [comment]
Zajímavé, teď tam po té chybě je jenom takový zbytek: 

![image](https://user-images.githubusercontent.com/1194177/45383507-b6a59300-b60b-11e8-92bd-9e5cdefd8cc0.png)

není možné, že se to trochu opravilo tím, že jsem se snažil opravit  #129 ?

**Comment by kaklik** [comment]
Tohle vypadá skutečně, jako vyřešené. :)

Akorát mi není jasné, jak to, že se liší levá a pravá strana dílu. 

Pravá strana
![image](https://user-images.githubusercontent.com/1194177/47485409-5d519600-d83e-11e8-9f25-e43f05756098.png)

Levá strana 

![image](https://user-images.githubusercontent.com/1194177/47485631-cafdc200-d83e-11e8-9106-5fd811dcd5e0.png)

Z hlediska funkce a tisku to ale nemá žádný vliv, takže to můžeme zatím uzavřít.
