### ISSUE TITLE
Držák pro start ze střechy automobilu

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#146]
Pro start vírníku bude potřeba mechanismus který umožní start ze střechy automobilu.   Pro základní experimenty je nutné, aby konstrukce byla především bezpečná. 
Takže bude realizovaná tak, že na příčníky bude našroubovaná deska z voděodolné překližky o rozměrech 250x125cm tlustá 15mm. 

Na tuto desku bude teprve našroubovaný vypouštěcí mechanismus, tak že v desce budou narážecí matice M10 do dřeva. Do kterých se z druhé strany našroubují šrouby. 
Samotný vypouštěcí mechanismus může být realizovaný z hliníkových profilů a tištěných dílů. 
Odjištění vírníku během vypouštění lze předpokládat [přídržným elektromagnetem s permanentním magnetem](https://www.magnety.cz/pridrzne-elektromagnety/pridrzne-elektromagnety-s-permanentnim-magnetem/).

Elektromagnet, jako těžší komponenta by zřejmě měl zůstat na vypouštěcím automobilu a kotva zůstane na podvozku vírníku. 

Uchycení vírníku před opuštěním držáku musí splňovat tyto parametry

- Volnost pohybu v ose pitch alespoň 0 až +20 stupňů
- Volnost pohybu v ose yaw maximálně +/-5 stupňů
- Volnost pohybu v ose Roll +/- 15 stupňů.
- Nemožnost vyskočení z držáku vibracemi a nárazy při rozjezdu
- Nemožnost vypadnutí z držáku při prudkém zabrždění automobilu v jakékoliv fázi startu až do odjištění. 

Konvence pojmenování os je patrná z [tohoto obrázku](https://upload.wikimedia.org/wikipedia/commons/c/c1/Yaw_Axis_Corrected.svg).

Uchycení proto zřejmě bude realizované [kardanovo spojkou](https://en.wikipedia.org/wiki/Universal_joint) na jejímž volném konci bude magnet držící podvozek UAV.  Spojka ale musí omezovat zosah volností podle seznamu výše. Konstrukčně lze vyjít například z [tohoto návrhu](https://www.thingiverse.com/thing:392828/files). Použití kuličkových ložisek pro uvažovanou aplikaci ale není nutné. 

Postup vypouštění bude následující.

1. Aktivace avionických systému UAV a kontrola vypouštěcího mechanismu. 
2. Postupný rozjed automobilu na max 50km/h. 
3. Růst otáček rotoru
4. Zvednutí přídě UAV na doraz vypouštěcího mechanismu, díky dostatečnému vztlaku rotoru.
5. Autopilot vyrovná náklony v osách Roll a Yaw a stabilizuje osu Pitch, tak aby nebylo dosaženo žádného dorazu vypouštěcího mechanismu
6. Odjištění vypouštěcího mechanismu a přechod do stoupání směrem před automobil. (Automobil se vzdaluje za vírník) a vírník opouští vypouštěcí mechanismus v kvadrantu 0-90stupňů měřeno od přídě automobilu.

 Z toho je zřejmé, že je potřeba, aby došlo ke koordinaci mezi UAV, člověkem který jej pilotuje a vypouštěcím zařízením na střeše automobilu. Vhodným technickým řešením takového úkolu zřejmě může být použití [ROS](http://www.ros.org/), který na základě dat přijatých přes MAVlink odjestí vypouštěcí mechanismus. 
Pro odjištění ale musí dojít ke shodě z těchto míst: 

1. Pilot UAV musí dát signál k vypuštění
2. Autopilot UAV musí měřit parametry vhodné k vypuštění
3. ROS systém v automobilu musí telemetrické parametry vyhodnotit jako odpovídající požadavku na vypuštění
4. operátor automobilu nesmí mít zapnuté blokování vypouštění. (Přepínač odpojující elektrický okruh vypouštěcího elektromagnetu)

**Comment by roman-dvorak** [comment]
Vypouštěcí plošina by měla mít možnost nějakým způsobem zafixovat vírník ve výchozí poloze. Ať už z důvodu pojezdu auta bez předpokladu startu nebo uvedení vírníku do vodorovné (rovnoběžné s autem) polohy pro usnadnění přizpůsobení autopilota.

Toto by šlo vyřešit tím, že kardanův závěs bude umístěn pevně v jednom místě a okolní "podlaha" (podpěry vírníku) bude výškově nastavitelná. Tím zároveň může dojít k plynulému nastavování rozsahu volnosti ve všech osách.

Při rozjezdu s předpokladem startu by se nejdříve auto rozjelo na určitou rychlost a teprve poté by se podložka pomalu snížia (zvětšila by se volnost kardanova kloubu do uvedených mezí). Rychlost uvolňování by byla podle toho, jak se regulátor dokáže plynule přizpůsobovat.

**Comment by kaklik** [comment]
To by ale znamenalo, že kromě ovládání elekromagnetu by se se musela ovládat ještě výška podložky.  Pokud by to skutečně bylo nutné takhle řešit, tak je asi lepší vertikálně posouvat uchycení kardanova závěsu třeba vertikálním trapézovým šroubem na krokovém motoru.

Myslel jsem, že by zafixování pro převoz bylo řešeno uchycením podvozkových ližin do tištěných U profilů našroubovaných na překližku, kde budou i kola.  
Při přípravě pro start by se jenom sundaly upínací pásky a ližiny by ležely v profilech, dokud by nedošlo k nadzvednutí.  

Teď mě napadlo, že to jde vylepšit tím, že by profil pro ližiny měl směrem nahoru rozšiřující se tvar, takže by s roztoucí výškou nadzvednutí stoupala i volnost do stran.

**Comment by kaklik** [comment]
Tady je rychlý náčrtek toho, jak bych si to zhruba představoval. 

![ptdc0119](https://user-images.githubusercontent.com/1194177/45388693-fd9a8500-b619-11e8-9e4d-1f9c1edf4e04.JPG)

Ještě to rozkreslím na dílčí komponenty.

**Comment by kaklik** [comment]
Přesunutí příspěvku @roman-dvorak 

Přemýšlel jsem dnska o té Markovo připomínce/otázce, proč je to tlačné a né tažné.

Je pravda, že s tažným závěsem by jsme možná získali podstatně větší stabilitu letadla na závěše, protože by to byla stabilní poloha. Takhle se to vychýlí ze středu a bude v nestabilní poloze. Dokud nebude mít vírník větší tah než rychlost auta.

Zato v případě tažného závěsu by letadlo bylo stále ve stabilním stavu a odepnulo by se v bodě, kdy tah je nulový  a letadlo by okamžitě přidalo na svém výkonu.

Samotný závěs by mohl být tažný, ale umístěný více v zadu než AZ (YAW) točna a tím by zde opadnul problém s tím, že letadlo má vystartovat dopředu. Kotva na letadle by byla umístěna v zadní části podvozku stejným způsobem. Možná by to mělo výhod, že by kontva moha být napevno přidělána a jen by se otáčel magnet na závěsu. Snad je to z následujícího schématu vidět případně překleslím.

![img_20180917_091619](https://user-images.githubusercontent.com/5196729/45610032-c6cdd000-ba5a-11e8-8434-78988cc15400.jpg)
(rozhodně není v měřítku)

díly nakreslené v #156

**Comment by kaklik** [comment]
Tohle řešení by zřejmě bylo vhodnější. Protože nedestabilizuje celý systém. Ideální by zřejmě bylo, aby ty rotační osy procházely těžištěm UAV, pak by vliv na změnu stability byl neutrální.

Ten tenzometr bych asi z prvních pokusů vyjmul a nejdřív vyzkoušíme jak se to chová bez něj.  Myslím, že je dost možné, že k ničemu ani nebude potřeba. 

Myslím, že ani není potřeba, aby rotace v ose Roll byla umožněna ložiskem u elektromagnetu a může to být zajištěno stále "třetím dílem" podle #156 
Akorát se na opačnou stranu vahadla bude muset umístit protizávaží tak, aby vyvažovalo jak osu Roll, tak i osu Pitch.

**Comment by kaklik** [comment]
Ještě je možná zajímavý tenhle obrázek, který ukazuje, jak se měří síly ve skutečném aerodynamickém tunelu.

![Force Measurement system](http://aerorocket.com/tunnel/system.gif)

**Comment by roman-dvorak** [comment]
Myslím, že umístění rotace v ose Roll je špatně ve "třetím dílu". Protože při náklonu v Roll se vírník bude otáčet po velké kružinci okolo třetího dílu. Což mi nepřipadá dobře. Tato rotační osa by měla být taktéž co nejblíže těšišti a ose Roll na vírníku.

A zde by mohl vzniknout "čtvrtý díl", který by řešil rotaci ve dvou osách zároveň. Rotaci v ose Roll tak, že by přímo do magnetu byl M8 inbus šroub. V tom samém dílu by byla volnost v ose Pitch (Podruhé!) aby zde nedocházelo ke kroucení mezi magnetem a kotvou.

Stále se bojím, aby jsme se pod vírník s tím vším dobře vešli na výšku...

**Comment by kaklik** [comment]
S tou vzdáleností od osy rotace maš úplně pravdu.  Jenom si teď nedovedu moc představit ten nový čtvrtý díl. 
Dovedl by jsi ten díl nakreslit? 

S tím jestli  se pod virník vejdeme bych si zatím nedělal moc starosti.  Vírník můžeme nad desku zvednout tím, že pod ližiny dáme nějaké podložky. Zkomplikuje to akorát montáž rotoru. Nemusí být navíc nutně uchycený za ližiny ale můžeme klidně použit tu vertikální trubku, pro třetí kolečko, která je teď nevyužitá.

**Comment by roman-dvorak** [comment]
Nákres čtvrtého dílu je v  #156

**Comment by kaklik** [comment]
Aktuální chyby v návrhu: 

- Díl 888_3007 má špatnou velikost matek pro připevnění příruby EMFS-17.

**Comment by kaklik** [comment]
Tak velikost děr pro matky jsem vyřešil. 
A nový způsob upevnění k magnetu také. 
Takže zbývá jenom nalézt metodu, jak počítat tvar závěsu pro zvětšení rozsahu úhlů. Na tom pracuje @roman-dvorak.

**Comment by kaklik** [comment]
Aktuálně držák na autě vypadá takto: 

![image](https://user-images.githubusercontent.com/1194177/46415783-51ceeb80-c726-11e8-96df-4937ab3f6f9b.png)

**Comment by Elizaa62** [comment]
Jak to vypadá s tímto issue?

**Comment by kaklik** [comment]
Tenhle úkol se zatím stabilizoval na použití pevného sloupku s elektromegnetem. 
Budoucí problém je změna konstrukčního uspořádání tak, aby držák pro start umožnil i umístění nákladu na UAV.
