### ISSUE TITLE
Díl pro přidělání koleček k hliníkové tyči udělat bytelnější

### ISSUE THREAD

**Issue by roman-dvorak** [Elizaa62/Components#150]
Díl č. 666_1014 [https://github.com/Elizaa62/Components/blob/master/src/666_1014.scad](url) pro přidělánů koleček k AL tyči upravit tak, aby byl k tyči přidělán pomocí dvou M3 šroubů. Nyní se díra v hliníkové trubce vykloktá a kolečko nedrží kolmo.

**Comment by kaklik** [comment]
Ono to možná na těch vyrobených kusech je díky tomu, že vyvrtat ty díry úplně kolmo je dost těžké.  Nicméně použít dva šrouby je dobrý nápad.

**Comment by Elizaa62** [comment]
Do dílu 666_1014 přidán druhý šroub pro připevnění k trubce.

**Comment by kaklik** [comment]
@Elizaa62 Přidání šroubu je myslím správně, je fajn, že se ty šrouby vešly do stejné šířky.  Ještě je to potřeba upravit u vrtacího přípravku, ale to předpokládám víš.

**Comment by Elizaa62** [comment]
Vrtací přípravek je také opraven. Jen jsem to sem nezapsala.

**Comment by kaklik** [comment]
Já, když jsem se sem díval, tak v repozitáři ještě nebyl. Teď už ho vidím. :)
