### ISSUE TITLE
Přípravek pro zkracování šroubů

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#153]
Na zkrácení šroubů do kování rotorových listů by se hodil přípravek, do kterého se zašroubuje šroub (proti matici na opačné straně přípravku) a pak se pilkou na železo prořízne štěrbina v definované vzdálenosti od hlavy šroubu. 
Tím by mělo být možné opakovaně řezat šrouby stejné délky.

Podobné řešení už existuje pro řezání trubek. viz https://github.com/kaklik/Components/blob/master/src/manufacturing_helpers/tube_cutter.scad

Potřebná délka uříznutého šroubu je 21,5mm.

**Comment by Elizaa62** [comment]
Je uveden jako "screw_cutter". 

Díl je řešen tak, že si můžeš v záhlaví zvolit jakou délku šroubu potřebuješ a jaký průměr šroubu budeš řezat.

Otvor pro pilku je hodnota "global_clearance" a otvor je až za požadovanou délkou šroubu.

**Comment by kaklik** [comment]
Tak jsem trochu upravil rozměry a vytiskl to. 
![20180913_115149](https://user-images.githubusercontent.com/1194177/45484070-35591800-b753-11e8-99dd-1e1ee56cd99d.jpg)

Myslím, že to funguje :) 


![20180913_123653](https://user-images.githubusercontent.com/1194177/45484133-74876900-b753-11e8-91e4-d091079b6d5e.jpg)

Akorát asi bude potřeba šroub do přípravku uchytit samojistnou maticí, protože se při řezání povoluje.
