### ISSUE TITLE
Díly pro uchycení elektropermanentního magnetu a UAV

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#156]
Při uchycení podvozku vírníku na desku na střešním nosiči musí být umožněna jistá volnost pohybu minimálně ve dvou rotačních osách.  Viz #146 
K tomu je potřeba užít kardanův závěs s omezeným rozsahem pohybu.  Rozsah pohybu může být omezen tvarem. 
Jako čepy pro spojení jednotlivých dílů bych navrhoval použít šrouby M6  nějakých standardních délek s inbus hlavou.

Magnet, který máme  je typ EPPM-6329-24-020 s průměrem 63mm. 
https://www.magnety.cz/pridrzne-elektromagnety/pridrzne-elektromagnety-s-permanentnim-magnetem/

**Comment by kaklik** [comment]
Zkusil jsem udělat náčrtek, jak by konstrukce závěsu mohla vypadat.  
Pro spojení předpokládám použití šroubů M6 a samojistných matic zapuštěných v kapsách. Šrouby se do matic nebudou úplně dotahovat a tím vznikne možnost protáčení v kloubových spojích.

Každá osa má dorazy maximálního rozsahu otočení.  Tyto rozsahy by bylo potřeba v kódu součásti nastavovat jako úhly.

![20180912_142533](https://user-images.githubusercontent.com/1194177/45425439-ab00ad80-b699-11e8-963f-3edc34f5f3c9.jpg)

![20180912_142557](https://user-images.githubusercontent.com/1194177/45425447-afc56180-b699-11e8-9a28-563d1f5a0624.jpg)

**Comment by roman-dvorak** [comment]
### První díl (AZ, YAW) bude řešit rotaci kolmo na střechu auta (YAW osu auta). 

tento díl by se pomocí 2-4 M6 šroubů přidělal do dřevěné desky (18mm). Skrz tento díl povede licovaný šroub 8mm M6, který bude zespoud (od dřevěné desky přidělán bezpečnostní maticí). Pod maticí bude ložisko 608. Stejné ložisko bude i shora, kde z horní strany pnese druhý díl.

![img_20180917_001914](https://user-images.githubusercontent.com/5196729/45601703-69616100-ba11-11e8-9ef5-da6c44c3e4d0.jpg)

### Druhý díl (ALT) 

Druhý díl bude přidělán na první díl pomocí stejného lícovaného šroubu. V této části bude hlava šroubu a povede směrem dolů. Možná by stálo za to, místo, kde bude hlava šroubu udělat širší pro možnost podložky pro roznesení síly.

Z tohoto dílu, směrem dozadu, povede "výběžek", ve kterém bude zašroubován šroub (M6?) směrem dolů. Bude vytvářet takový "trn" pro omezení volnosti rotace v AZ ose.

![img_20180917_003205](https://user-images.githubusercontent.com/5196729/45601697-52227380-ba11-11e8-8331-0b166166408a.jpg)

Z boků do tohoto dílu povede další lícovaný šroub, který zajistí rotaci v ose ALT.


### Třetí díl.
Tento díl bude jednoduchá kostka, kterou skrz na skrz povede lícovaný šroub z druhého dílu. Ve spodní části ním bude prostrčena M8 závitová tyč. Tato tyč bude uložena rotačně pomocí radiálních ložísek 608 z boku dílu. Ložiska budou z každé strany stažěna maticí M8.

![img_20180917_000420](https://user-images.githubusercontent.com/5196729/45601735-fad0d300-ba11-11e8-8b3e-7dcf2e8d1bf8.jpg)

Na konci závitové tyče bude umístěn tenzometr a magnet. Je vybrána závitová tyč M8, která už je dostatečně pevná a navíc v magnetu je M8 závit. Na druhé straně musí být závaží, které bude vyrovnávan nevyváženost soustavy.

### Celek...
![img_20180917_000416](https://user-images.githubusercontent.com/5196729/45601757-5a2ee300-ba12-11e8-8243-fa7c41cf3a45.jpg)

**Comment by kaklik** [comment]
Souhlasím, jenom bych kvůli konstrukčnímu zjednodušení navrhoval díl První díl (AZ, YAW) tvarově upravit tak, aby vycházel z kuželu. 

![image](https://user-images.githubusercontent.com/1194177/45614392-b113d700-ba69-11e8-8495-2255e83e1ef0.png)

Zapsáno jako 

    cylinder(h=50, r1=50, r2=30, center=false);

Odpadne tím požadavek na ta žebra a celkově se to myslím zjednoduší i pro tisk. Neboť díry pro šrouby se pak dají vytvořit prostým odečtením.

Ostatně u druhého dílu (ALT) by to mohlo být podobné. 

[Rozměry ložiska 608](https://www.arkov.cz/p/608-2zr-lozisko-kulickove-jednorade-oboustranne-kryte-plechem-zkl-13967)

**Comment by kaklik** [comment]
Tohle jsou lícované šrouby průměru 8mm/M6, které máme  k dispozici
Délky jsou 70 a 30mm.  Pro ukázku je na fotce ještě ložisko 608 a čep 8mm / 40mm, který ale do ložiska nejde prostrčit.

![20180917_114408](https://user-images.githubusercontent.com/1194177/45618696-ea067880-ba76-11e8-848a-f1f9a3781963.jpg)

**Comment by kaklik** [comment]
"čtvrtý díl" bude nějaká spojka, pomocí které se spojí 2 M8 závitové tyče. Pro vodorovnou tyč bych navrhoval ukončit uvnitř dílu. Do dílo by byla kapsa pro M8 matici a z venku by se to stáhlo proti této matici. Svislá závitová tyč by byla skrz stažená z vnějších stran maticí. Toto řešení navrhuji udělat z důvodu, aby výška tohoto zařízení byla co nejmenší. 

![img_20180917_233044](https://user-images.githubusercontent.com/5196729/45652553-41d3cc80-bad5-11e8-8c34-fa019713964c.jpg)
(Na obrázku je to nakresleno o 90 stupňů otočené než bude skutečná pozice) 

"Pátý díl" se nasadí na M8 závitovou tyč. Uvnitř tohoto dílu bude kapsa pro matici a stáhne se to oproti druhé matici z venku. V horní části tohoto dílu bude díra pro osu ALT (pitch).

"Šestý díl" bude pomocí takově vydlice nasazen na "pátý díl". Ložiska jsou uložena z vnější strany tohoto dílu. V horní části budou z obou staran znovu vložena ložiska a pomocí šroubu M8 to bude zašroubováno přímo do těla magnetu. Na horní straně budou takové dva "výběžky", které budou nastavovat rozsah rotační osy tohoto kloubu. Skrz tyto výběžky budou zašroubovány nastavovací šrouby skrz matice zasunuté do kapes v tomto díle.

![img_20180917_233050](https://user-images.githubusercontent.com/5196729/45652617-81021d80-bad5-11e8-92fe-4987d26846d5.jpg)


Mezi "Šestým dílem" a magnetem bude "Sedmý díl", který bude mít stejný průměr jako magnet a na sobě takový "trn" který toto omezí. Trn může být vystužen zašroubováním šroubu do těla trnu (ze strany od magnetu) Okolo díry pro M8 šrob by bylo vhodné udělat osazení, které by tlačilo na střední část ložiska.

![img_20180917_233114](https://user-images.githubusercontent.com/5196729/45652638-937c5700-bad5-11e8-9710-f65cd8843ecb.jpg)

**Comment by kaklik** [comment]
@Elizaa62  Správně jsou ty nákresy od @roman-dvorak

**Comment by Elizaa62** [comment]
Díl první jako díl 888_3000. 
Díl druhý jako díl 888_3001.

**Comment by roman-dvorak** [comment]
Na díl 888_3000 je potřeba přidělat časti pro omezení rotace v YAW ose.

@Elizaa62 Po domluvě s @kaklik by to chtělo na díl 888_3000 přidělat takové "sloupky", vyšší než je současná výška dílu. Na mém nákresu výše je to trochu vidět. Skrze tento díl umístit sroub, kterým by se nastavoval rozsah volnosti osy a tento šroub by narážel do výběžku z dílu 888_3001. Matice by byla umístěná v kapse přímo v tom sloupku.

Z výběžku na dílu 888_3001 by se mohla odstranit díra, která byla původně myšlená na trn směrem dolú, který by měl stejný účel.

**Comment by roman-dvorak** [comment]
@Elizaa62 "Čtvrtý díl" a "pátý díl" by bylo možné spojit v jeden. Viz. následující nákres
![42104914_490258154717854_2312889160760819712_n](https://user-images.githubusercontent.com/5196729/45752353-72228480-bc15-11e8-9f60-9be375f458c6.jpg)

Udělal bych to spíše tak, že "díl 4+5" by byl jako vidlice a "šestý díl" by se vkládal dovnitř. Ostatní díly by měly zůstat stejné.

**Comment by Elizaa62** [comment]
Doplněny sloupky k dílu 888_3000 i s otvorem pro šroub a kapsou pro matku. Akorát si nejsem jistá, zda správně.

Zvětšeny rozměry dílu 888_3001 a odstraněn otvor pro šroub ve výstupku.

Nový díl 888_3002 -  třetí díl z tohoto issue.

Nový díl 888_3003 - sestava předchozích třech dílů.

**Comment by roman-dvorak** [comment]
@Elizaa62 úplně správně ne :)

Má to být tak, že díl 888_3001 se má na dílu 888_3000 otáčet v omezeném rozsahu (cca 10deg) A šrouby vložené do těch výstupků z dílu 888_3000 mají nastavovat rozsah, jak moc se může otáčet. 

Takže je potřeba přidělat kapsu i do druhého sloupku. 
Výstupek z dílu 888_3001 bych udělal trochu uzší a odstranit díru skrz.
Sloupky z dílu 888_3000 udělat dál od sebe a udělat větší mezeru mezi sloupkem z dílu 888_3000 a válcovou základnou dílu 888_3001

Nápad od @kaklik, že by to bylo bez žeber a byl by to kužel není špatný, protože by se tím velmi zvýšila pevnost těchto výstupků.

**Comment by kaklik** [comment]
Nezavedeme si nějakou konvenci v těch názvech?  vytvořit sestavu z dílů je dobrý nápad, ale chtělo by to pojmenovat nějak aby bylo jasné, že to sestava té skupiny. 

Zatím  to máme odlišené jako 

- 666_ výkresy od pana Dobiáše. 
- 888_ naše nové výkresy

A pak je zevedeno číslování skupiny jako třeba  888_3XXX jsou díly závěsu.  Tohle mi připadá dobré. 
Akorát bych to ještě rozšířil o sestavy a zavedl třeba 888_31XX konkrétně třeba 888_3101. Za předpokladu, že skupina dílů nebude mít víc jak 100 komponent. Pak by to asi přestalo fungovat. 

Jde mi o to, že když se sestavy budou číslovat stejně jako díly, tak bude existovat sestava 888_3003 a další díl skupiny bude 888_3004. Což mi přijde dost nepřehledné.

**Comment by Elizaa62** [comment]
Sestava přejmenována na 888_3101.scad

888_3003 - čtvrtý a pátý díl
888_3004 - šestý díl
888_3005 - sedmý díl

**Comment by roman-dvorak** [comment]
![snimek obrazovky porizeny 2018-09-20 15-37-56](https://user-images.githubusercontent.com/5196729/45822367-9a7cb280-bceb-11e8-85c3-59d2d2e8fecd.png)

Díl 3004 by měl být dole půlkruhový, aby se mohl v dílu 3003 otáčet. To že nepůjde naklonit dopředu dolů nevadí. Musí jít naklánět "dozadu".

Díl 3004 musí být širší a zarážky pro omezení roll rotace dále od sebe. Aby se díl 3005 mohl otáčet alespoň o 10deg na každou stranu. Ze stejného důvodu musí být díl 3004 nižší.

**Comment by roman-dvorak** [comment]
@Elizaa62 Když si prohlížím takhle ten složený díl, tak vzhledem k rozměrům a potřebné volnosti roll osy (minulý komentář) by možná bylo lepší vidlici udělat na díl 3004 a díl 3005 do toho vkládat. Omlouvám, se že jsem to navrhoval původně obráceně. Nedokázal jsem si dobře představit rozměry.

To zapuštění ložiska do vnitřní strany vidlice je fajn nápad. Ale blbé je, že když se šroub stáhne ze stran maticí, tak se nebude otáčet a nemá tam to ložisko moc smysl. Proto by bylo dobré to udělat podobně jako je to na mé modifikací dílu 3002. A vlastně ten díl 3003 lze vytvořit modifikací dílu 3002 tak, že se přidá uložení pro ložisko i do druhé díry a trochu se protáhne.

**Comment by Elizaa62** [comment]
Pokusila jsem se to opravit.

**Comment by kaklik** [comment]
Díly 3003 a 3004 do sebe pasují velmi na těsno. není tam žádná vůle pro separační podložky u ložisek.

![20180921_161711](https://user-images.githubusercontent.com/1194177/45889955-0b8e9980-bdc2-11e8-8e54-a7b2e6ddde7d.jpg)

Tohle se netiskne moc dobře. Zřejmě  by to chtělo zkosit hrany, tak aby při tisku tvořily šikmý převis, nikoli rovnou plochu. 
![20180921_102931](https://user-images.githubusercontent.com/1194177/45890022-3547c080-bdc2-11e8-9799-6dc39ca9af91.jpg)

Ve spodním dílu není žádná rezerva na délce šroubu a šroub sotva dosahuje do spodního ložiska.
Je to zřejmě způsobené tím, že se špatně počítá s délkou lícovaného šroubu. 
![20180921_100635](https://user-images.githubusercontent.com/1194177/45890042-40025580-bdc2-11e8-9398-8fe1361242f2.jpg)

**Comment by kaklik** [comment]
Díry pro hlavy šroubů M6 v základně by měly být spíše šestihranné,  protože takto jdou použít pouze šrouby s inbus hlavou.

**Comment by kaklik** [comment]
V dílu 888_2006 chybí kapsy na zapuštění matic šrobů M2.5 od serva.

**Comment by kaklik** [comment]
Pro současnou aplikaci řešení vyhovuje.
