### ISSUE TITLE
Náhrada řemenového převodu hlavy ozubeným

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#158]
Na hlavě by bylo potřeba vyzkoušet nahradit současný řemenový převod ozubeným převodem. 
Důvody k tomu jsou:

- Zvýšení převodového poměru mezi motorem a rotorem 
- Odstranění zátěže rotoru vznikající statickým odporem při ohybu řemenu

Ozubená kola by zřejmě měla mít šípové ozubení.  První verzi ozubených kol je potřeba navrhnout tak, aby je bylo možné vytisknout.

**Comment by kaklik** [comment]
Ozubený převod vyžaduje změnu smyslu otáčení rotoru.

**Comment by roman-dvorak** [comment]
> Ozubený převod vyžaduje změnu smyslu otáčení rotoru.

Asi nechápu... Vždyť se motor může táčet obráceně. Nevidím zde v tomto žadný problém.

Ale toto řešení nepovažuji za vhodné z důvodu pružení desky rotorové hlavy.

**Comment by kaklik** [comment]
Když se motor bude otáčet opačně, tak se povolí unašeč pastorku na jeho hřídeli, pokud by neměl levý závit. 
Musel by se tak změnit smysl otáčení rotoru, ale to je velká konstrukční změna.
