### ISSUE TITLE
Tisknutelný díl pro montáž rotorové hlavy na pilon 

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#164]
Plechové díly 666 1021 a 666 1022 mají být nahrazené jedním tisknutlým dílem s kloubovým ložiskem [EFSM-12 ](https://www.igus.cz/product/382).

**Comment by roman-dvorak** [comment]
![img_20180925_144820](https://user-images.githubusercontent.com/5196729/46032458-f71d0a80-c0fb-11e8-9c7e-0511c1836300.jpg)

**Comment by kaklik** [comment]
Prohlédl jsem si to a myslím že ten díl je už z velké části hotový. Našel jsem zatím jenom tyhle nedostatky

- chybí díry na šrouby od serva a kapsy pro matky M2.5
- drážka na kolík z desky hlavy je otočená o 90 stupňů a měla by být podstatně hubší ( alespoň 15mm), nebo skrz materiál. Správná orientace drážky je vidět ve výkresu 666_1021.pdf
- je nutné, aby pozice drážky byla přesná oproti středu kulového kloubu, vzdálenost stredu drážky od osy kulového kloubu musí být 32 mm.
- prostřední díra pro kulové ložisko je malá. Měla by mít průměr 25 mm. 
- servo by mělo být blíže k pravému okraji dílu vychází mi to podle výkresu asi na 4mm od hrany plechu.
- stěna pod ložiskem by myslím měla být tlustší, bude se přes ní přenášet celá hmotnost.

**Comment by kaklik** [comment]
Ještě jsem si všiml, že ty rozměry, které tam jsou zřejmě nejsou pro přírubu EFSM-12 ale pro menší EFSM-04. Na tom odkazu je totiž potřeba si překliknout na správný typ. Potom jsou rozměry následující: 

![](https://www.igus.cz/contentData/Products/ProductPictures/p382z22594_1050x700.jpg)

Parameter | Value
-- | --
Ø d1 | 12,00 mm
Ø dB | 25,0 mm
h | 40,0 mm
m | 28,0 mm
A1 | 7,0 mm
Ag | 13,0 mm
N | 5,3 mm

**Comment by kaklik** [comment]
Tak díl jsem vytiskl.  Pozitivní je, že do něj pasuje příruba s kulovým kloubem. :) 
Jsou tam ale i nedokonalosti. 

![image](https://user-images.githubusercontent.com/1194177/46144615-c94fd700-c25d-11e8-9f6e-7bf9e07335cb.png)


Například tyto: 
- Nejde prostrčit servo do otvoru, protože tomu brání jeho kabel. Řešením je zkosit hrany otvoru tak, aby nepřekážel kabel od serva.
- Čep z desky hlavy naráží do přední a zadní stěny výřežu pro čep.  Výřez je zřejmě potřeba zvětšit a zvětšit rozsah úhlů pohybu.
- Díl hlavy je širší, než předchozí plechová verze. Nevím jak se to stalo, ale je potřeba zajistit, aby měl rozměr pro nějaké existující délky šroubů.  
- Zamyslet se nad možnostmi odlehčení dílu, což by mohlo kromě snížení hmotnosti i zkrátit tiskový čas.

**Comment by Elizaa62** [comment]
K tomu čepu.. Co tam mám zvětšit? Můžu maximálně hýbat z poloměry..

Jinak šířku jsem změnila.. Nevím proč, ale nepočítala jsem tam s šířkou dílu 666_1026 počítanou na délku šroubu.. Takže nyní je šířka dílu pro montáž rotorové hlavy šířka dílu 666_1026 počítaná pro normalizované délky šroubu plus 2 krát tloušťka plechu, která je 1,5 mm.

**Comment by kaklik** [comment]
Dobře, po téhle úpravě by to pak mělo být stejně široké, jako původní díl. To by mělo být správně. :)

U toho čepu jde o to, že při pohybu ve směru osy X naráží do okrajů toho otvoru. Nevím o kolik to je, ale zřejmě je potřeba jednak zvětšit ten otvor, a potom i zvětšit poloměr podstavy toho kuželu, kterým je otvor vytvořen.  To by mělo zajistit, aby se čep mohl pohybovat ve větším rozsahu úhlů a po větší vzdálenosti. 
Rozsah úhlů ve kterých se čep může pohybovat je asi +/- 20 stupňů.

**Comment by kaklik** [comment]
Zjistil jsem, že by bylo zřejmě lepší tenhle díl upravit tak, aby se na trubku šrouboval fixní délkou šroubů.  S tím že hlavička a matka šroubu bude v dílu trochu zapuštěná. Vhodný šroub je například M4x50, neboť je potíž sehnat delší šrouby.
