### ISSUE TITLE
Aktualizace sestavy podle současného stavu

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#166]
Soubory ve složce https://github.com/Elizaa62/Components/tree/master/src/drawings 

Už neobsahují přiliš aktuální stav celkové sestavy.  Bylo by proto zřejmě vhodné sestavu aktualizovat.

**Comment by Elizaa62** [comment]
Sestava je aktualizovaná pod názvem 666_2000.  Sestavu pod názvem 888_1005 jsem smazala, aby nedošlo k záměnám.
Modifikovala jsem trochu spojku 888_2003. 
Dále bych potřebovala rozměry podvozkových trubek, abych mohla případně vytvořit ohýbací přípravky, či zpřesnit celou sestavu.
Případné připomínky k sestavě směřovat sem prosím.

**Comment by Elizaa62** [comment]
> Sestava je aktualizovaná pod názvem 666_2000. Sestavu pod názvem 888_1005 jsem smazala, aby nedošlo k záměnám.

**Comment by kaklik** [comment]
Rozměry trubek jsem přidal přímo jako fotografie do úlohy řešení ohýbacího přípravku #119


=> rozměry trubek použity pro rozměry podvozkových trubek v sestavě.

**Comment by kaklik** [comment]
- V modelu chybí pohyblivé části směrovky
- Některé díly třeba kryt rotorové hlavy není upraven, aby pasoval k současnému stavu modelu

**Comment by Elizaa62** [comment]
Koukala jsem, že díl A spodního krytu je opravená. Opravila jsem podle rozměrů podvozkové trubky. 

Mohl bys mi prosím napsat seznam dílů, které se měnily a tudíž nepasují do sestavy?

Kryt rotorové hlavy je který díl?

**Comment by kaklik** [comment]
Dílů, které do sestavy nepasují díky tomu, že se měnily je minimum. 
Je to v podstatě akorát:
-  [Kryt vertikální trubky](https://github.com/ThunderFly-aerospace/TF-G1/blob/master/STL/666_1032.stl)
-  [Navázání držáku motoru k hornímu krytu](https://github.com/ThunderFly-aerospace/TF-G1/issues/174)

Horší je to ale s díly které v sestavě chybí úplně.  Ideálně by sestava totiž měla obsahovat všechny tyto komponenty: 

- [x] [vrtule](https://github.com/ThunderFly-aerospace/TF-G1/blob/master/STL/APC_15x4C.stl) 
- [x]  rotor ([listy](https://github.com/ThunderFly-aerospace/TF-G1/blob/master/STL/666_1201.stl), [kování](https://github.com/ThunderFly-aerospace/TF-G1/blob/master/STL/666_1206.stl), [závěs](https://github.com/ThunderFly-aerospace/TF-G1/blob/master/STL/666_1232.stl), [domek](https://github.com/ThunderFly-aerospace/TF-G1/blob/master/STL/666_1207.stl), [podložky listů](https://github.com/ThunderFly-aerospace/TF-G1/blob/master/STL/666_1247.stl) )
- [x]  [sestava rotorové hlavy](https://github.com/ThunderFly-aerospace/TF-G1/blob/master/STL/888_1101.stl) a [ozubená řemenice](https://github.com/ThunderFly-aerospace/TF-G1/blob/master/STL/rotor_pulley.stl). 
- [x]  ocas včetně [pohyblivých částí](https://github.com/ThunderFly-aerospace/TF-G1/blob/master/STL/print_plate_1028_rudder.stl)
- [x]  podvozek přední
- [x] podvozek zadní
- [x]  kolečka včetně středu
- [x]  Válce jako atrapa motorů (prerotátor i hlavní motor)

rotorové listy, závaží a kování máme namodelované jako jednotlivé komponenty, je z toho však potřeba vytvořit podsestavu.

**Comment by Elizaa62** [comment]
A k těm chybějícím dílům máš když tak jejich čísla? Abych to nemusela hledat a zkoumat.

**Comment by kaklik** [comment]
Aktualizoval jsem ten můj předchozí komentář o odkazy na díly, které teď aktuálně máme.  
Ještě mě napadlo, že by ti možná ušetřilo práci a čas, kdyby jsi tyto díly do té sestavy[ importovala jako už vyrenderované STL soubory](https://en.wikibooks.org/wiki/OpenSCAD_User_Manual/STL_Import_and_Export#import). Pak bys nemusela čekat, až se vyrenderuje celá sestava. 

Tento proces bude minimálně nutný v případě rotorového domku, protože ten nemáme jako openscad soubor, ale pouze jako STEP model, který ti překonvertuju na STL přidám mezi komponenty.

**Comment by Elizaa62** [comment]
Vytvořila jsem sestavu rotorových listů s podložkami a kováním, ale bez závěsu. Nejsem si jistá, jak to tam vše patří -> 666_2300.scad

vložena sestava rotorové hlavy a ozubené řemenice

podvozek přední - nevím přesně, co do něj patří

podvozek zadní jsem se pokusila aktualizovat podle rozměrů, které jsi poskytl v úloze řešení ohýbacího přípravku #119

kolečka včetně středu - také nevím, co přesně patří

akorát si nejsem jistá, zda jsem všechno nahrála na net, při vkládání mi vyskočila tato hláška

![image](https://user-images.githubusercontent.com/31339298/59380192-d57eb480-8d58-11e9-8496-79ae78041b69.png)

**Comment by kaklik** [comment]
Ta hláška je způsobená tím, že někdo udělal změny v repozitáři mezitím, co jsi něco upravovala. Nemělo by to být nic hrozného a  mělo by stačit spustit git pull. 

Teď se mi taky podařilo exportovat [díl rotorového domku](https://github.com/ThunderFly-aerospace/TF-G1/blob/master/STL/666_1207.stl).

**Comment by kaklik** [comment]
Vytvořil jsem ti [příklad](https://github.com/ThunderFly-aerospace/TF-G1/blob/master/src/666_1207.scad) jak importovat už hotové díly do sestavy.

Tenhle nový způsob považuji za důležitý kvůli tomu, že to je megarychlá metoda, jak skládat sestavy z vyrenderovaných dílů. Kde nemusíš čekat, až se ti překreslí sestava.

**Comment by kaklik** [comment]
Ta vrtule v té sestavě je, akorát má špatnou velikost a je na nečekaném místě. 

![666_2000](https://user-images.githubusercontent.com/1194177/59635698-1b20f000-9152-11e9-90cd-7dc71f1cb537.png)

**Comment by kaklik** [comment]
Tak problém s vrtulí jsem částečně vyřešil tak, že jsem model vrtule v meshlabu přeškáloval na reálnou velikost v milimetrech. 

![image](https://user-images.githubusercontent.com/1194177/59661232-9e6e3000-91aa-11e9-9c88-d75ed6dbd606.png)

**Comment by roman-dvorak** [comment]
dílčí sestavy byly složeny v blenderu. Výsledek je takový:

![Snímek z 2019-06-18 02-02-52](https://user-images.githubusercontent.com/5196729/59644505-790f0100-916d-11e9-97bd-84ebd92840de.png)

rotorové listy byly do modelu vloženy ručně, protože je nebylo možné vyrenderovat v sestavě.
Místo prerotátoru byl přidán válec.

**Comment by kaklik** [comment]
@Elizaa62  Aby se tohle issue mohlo uzavřít a příště nebylo potřeba tu sestavu skládat v blenderu, tak je potřeba vyřešit ty nezaškrtnuté body výše. 

Měly by ti k tomu chybět akorát rozměry válce jako hlavního motoru, které jsou průměr 49.5 mm a výška 49 mm .

**Comment by kaklik** [comment]
Myslím, že tohle je pro aktuální stav vírníku vyřešeno.
