### ISSUE TITLE
Vytvoření otvorů ve směrovce pro snadnější připevnění

### ISSUE THREAD

**Issue by Elizaa62** [Elizaa62/Components#167]
Při montáži směrovky na hlavní trubku není dostatek prostoru pro vložení inbusu a následnému přišroubování. Proto je nutné ve směrovce vytvořit otvory pro následnou snadnější montáž.

**Comment by kaklik** [comment]
Tohle vypadá jako vyřešené :)

![image](https://user-images.githubusercontent.com/1194177/47213426-47a22380-d39b-11e8-971d-2d5b5a5a9392.png)
