### ISSUE TITLE
Výška vrtacích přípravků

### ISSUE THREAD

**Issue by Elizaa62** [Elizaa62/Components#168]
Je nutné zkontrolovat výšku vrtacích přípravků.

**Comment by Elizaa62** [comment]
![image](https://user-images.githubusercontent.com/31339298/46428469-5a361f00-c744-11e8-8507-e9ce469a7bbd.png)

Toto je můj nákres související s tvořením vrtacích přípravků. Jsou zde uvedeny rozměry, podle kterých jsem je tvořila.. V posledním přípravku, koukám, mám špatně nakreslené otvory pro šrouby, ale rozměry sedí.

**Comment by Elizaa62** [comment]
Přípravky jsem překontrolovala a nezdá se mi,že by tam byla nějaká chyba. 

Vložila jsem přípravky pro znázornění do souboru drill_helper_together. Tento soubor se pak může klidně smazat.

**Comment by kaklik** [comment]
No ono se nám minule, když jsme vrtali tu hlavní trubku podařilo vyvrtat díry přesně tím kolmým způsobem, jak je tam máš nakreslené, protože ty přípravky k sobě tak pasovaly. :)

Jinak od toho souboru drill_helper_together.scad už existuje delší dobu lepší varianta, která vypadá takhle: 
![image](https://user-images.githubusercontent.com/1194177/46435727-5233aa80-c757-11e8-8519-3a186a7f3821.png)

a je to soubor https://github.com/Elizaa62/Components/blob/master/src/drawings/888_1007.scad  
Asi by se ho hodilo přejmenovat na  drill_helper_together.scad, protože je to výztižnější název a pravděpodobně ho tak spíš někdo najde.

**Comment by kaklik** [comment]
Většina vrtacích přípravků se nyní změní, takže jejich přesné parametry  není potřeba řešit.
