### ISSUE TITLE
Zkusit vytvořit tisknutelnou variantu desky rotorové hlavy

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#169]
Frézovanou desku rotorové hlavy by bylo zajímavé vyměnit za tisknutelný díl později s nějakými plechovými vložkami.

![image](https://user-images.githubusercontent.com/1194177/46468519-edb53180-c7d0-11e8-9c77-3083abf40173.png)

**Comment by kaklik** [comment]
A tohle je plechová náhrada současné  frézované desky, která tam teď je namontovaná: 

![image](https://user-images.githubusercontent.com/1194177/49432966-2a8dac80-f7b1-11e8-802f-708690a04f17.png)

**Comment by kaklik** [comment]
Otvory pro očka na nové desce je potřeba posunout dál od řemenice, aby očka nepřekážela řemenici.

**Comment by roman-dvorak** [comment]
díra pro šroub skrz očko posunuta o 5mm níže (dál od řemenice).

**Comment by kaklik** [comment]
Kapsy pro matky šroubů táhel by zřejmě měly být na opačnou stranu, aby při demontáži šroubu matka nevypadla.  Nebo alternativně z bogu ze zadní strany, kde bude otvor i lépe chráněn před zátékáním vody.

**Comment by kaklik** [comment]
Současná tisknutelná rotorová deska funguje velmi dobře, ale jen v malých úhlech, kdy hrany tisknutelných dílů nenarazí při zpětném chodu do sebe.  Díl je potřeba upravit tak, aby hrany dílů nemohly přesahovat přes sebe a nebo měly šikmý náběh, který zabrání zaseknutí.

**Comment by roman-dvorak** [comment]
Díl se nyní otáčí volně v obou dvou osách. Problém je dost vysoká Yaw volnost. Jako jedno z možných řešení je celý tvar kloubu výrazně protáhnout. Následně vytisknout celý a otestovat.

**Comment by kaklik** [comment]
Nahrazeno #225
