### ISSUE TITLE
Kryt 666_1032 nepasuje na díl  666_1025

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#17]
- Tolerance pro nasunutí dílu 666_1032 přes kryt 666_1025 je moc malá (minimálně o 1.5mm)

**Comment by Elizaa62** [comment]
Já jsem tam ten nástavec na dílu 666_1025 už nějak zmenšovala, ale asi je to zmenšení stále malé..

**Comment by kaklik** [comment]
Já to od té doby nezkoušel asi vytisknout. Myslím, že by mi pomohl nějaký testovací výřez, na kterém bych zkusil jak moc to do sebe pasuje.

**Comment by Elizaa62** [comment]
Vytvořila jsem dva nové díly 666_1025ZK1 a 666_1025ZK2 určené jen pro rychlý tisk a následnou kontrolu držáku.

**Comment by kaklik** [comment]
Zjistil jsem že po úpravě kryt pylonu stále nepasuje do držáku na horní části kapotáže.  Příčinou byla nesprávně zmenšená část pro držák.  Zmenšení o 2mm tak nebylo rezervou pro tolerance, ale prostým celkovým zmenšením.  Upravil jsem proto zdrojový kód tak, aby držák zmenšoval správně a navíc jsem zavedl proměnnou "clearance", která umožňuje nastavit velikost tolerančního prostoru mezi díly. 
K tomu bylo potřeba pracovat s úhlem odtokové hrany a délku profilu zmenšit patřičně k velikosti tohoto úhlu.
