### ISSUE TITLE
Vytvoření pohledů vhodných pro příručku

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#170]
V příručce budou potřeba pohledy s okótovanými základními rozměry.  V podstatě to vychází z úkolu #166 

Asi by to mělo být vyřešené tak, že každý obrázek v příručce bude mít tady svůj vlastní soubor: https://github.com/Elizaa62/Components/tree/master/src/drawings
Který bude využívat celkovou sestavu.  Sestava je teď v souboru  	888_1005.scad nebo 666_2000.scad netuším, jaký je mezi nimi rozdíl.  => sestava 888_1005.scad již neexistuje.

Obrázky by měly být rozděleny na svoje soubory, aby je bylo možné v příručce jednoduše aktualizovat. Ideální by bylo, kdyby sobor pohledu měl i nastavený pohled přes $vpr, $vpt a $vpd aby se dal vždycky snadno přegenerovat.

**Comment by kaklik** [comment]
Jeden z potřebných pohledů by měl být takový, aby umožňoval zanesení těchto kót (se správnými rozměry):

![tf-g1_dimensions](https://user-images.githubusercontent.com/1194177/54048090-09d25a00-41d9-11e9-97ca-d773407923b6.jpg)
 
Je to důležité ke správnému nastavení simulačního modelu.

**Comment by Elizaa62** [comment]
Co vše na tom pohledu má být vidět? Základní tělo s trubkami a podvozkem?

**Comment by kaklik** [comment]
Ano, nemusí tam být vůbec ty vnitří části, ani tam nemusí vůbec být rotor a kolečka.  Stačí pouze okótované jejich pravděpodobné pozice.
