### ISSUE TITLE
Držák na střechu auta pro transport  a omezení na jednu osou volnosti

### ISSUE THREAD

**Issue by roman-dvorak** [Elizaa62/Components#177]
Pro potřeby vývoje SW a nastavování regulátoru by bylo potřeba vyrobit držák, který bude umožňovat pohyb pouze v ose [Roll](https://simple.wikipedia.org/wiki/Pitch,_yaw,_and_roll). Osy Pitch a Yaw by měly být pevně zafixovány. Držák by měl vírník podpírat pod ocasní částí pomocí "dvojnožky". Držák by měl jít snadno demontovat nebo nějak sklopit.

Tento držák je rozšíření issue #146 

Na následujících obrázcích je můj návrh tohoto držáku.
![20190128_014016](https://user-images.githubusercontent.com/5196729/51809230-f14c5700-229e-11e9-9261-d29bf1397936.jpg)

Spodní díly 1-1 a 1-2: Spodní díl bude přišroubován jedním šroubem (rozdíl oproti obrázku) do nosné desky na střeše auta. K dílu 1-1 bude pomocí šroubu přidělán díl 1-2. Spolu budou tvořit kloub, který celý držák umožní sklopit dozadu. Díl proto musí mít na rozdíl od obrázku zaoblené rohy na otočné části, aby nepřekážely při otáčení.
Do dílu 1-2 budou nastrčeny AL trubky a sešroubovány pomocí šroubu skrz.
![20190128_014021](https://user-images.githubusercontent.com/5196729/51809238-09bc7180-229f-11e9-86ac-341d0178f4cc.jpg)

Díl 2-1 a 2-2 Pevně spojí trubky od patek. Trubky zde budou znovu prošroubované.
![20190128_014027](https://user-images.githubusercontent.com/5196729/51809244-1e990500-229f-11e9-9075-22e78b1124c0.jpg)

Vrchní díl umožňí připevnit horizontální trubku vírníku. Je potřeba mít možnost naklonit tento díl podle sklonu vírníku.
![20190128_014032](https://user-images.githubusercontent.com/5196729/51809248-396b7980-229f-11e9-8220-2afec9d029e7.jpg)

**Comment by roman-dvorak** [comment]
Výška středu horizontální trubky vírníku nad základní deskou je 28 cm. V první řadě je potřeba vytvořit držák, který bude v roll ose volný. Tzn. ocasní trubka se v držáku musí volně protáčet.

**Comment by kaklik** [comment]
Nějakým speciálním protáčením bych to teď nekomplikoval. Myslím že stačí když se na tom dílu, co stahuje trubku úplně nedotáhnou šrouby.

**Comment by Elizaa62** [comment]
V tomto issue jsem vytvořila díl 1.1 a 1.2 jako díl 888_3011.scad. Bylo by možné vytvořit pull_request, abych si mohla stáhnout i další vytvořené díly?

**Comment by kaklik** [comment]
pull-request obsahující nový držák jsem vytvořil.

**Comment by kaklik** [comment]
Tak se po posledním testu ukázalo, že držák je potřeba mírně snížit.  Ovšem do desky na střeše TF-R1 jsme navrtali díry pro současnou rozteč patek držáku. 

Rozteč by měla být patrná z následujících fotografií a je to potřeba přepočítat na rozteč děr v patkách. 

![Vnější strana patek](https://user-images.githubusercontent.com/1194177/52211049-00c43500-2889-11e9-85f7-bcba0f70fcfd.jpg)

![Vnitřní strana patek](https://user-images.githubusercontent.com/1194177/52211061-0883d980-2889-11e9-8f2c-8fc40f9e0f65.jpg)

Aby nebylo potřeba vrtat nové díry, tak je nutné tuto současnou vyvrtanou rozteč děr zachovat. 
Držák pak lze snížit buď 

- snížením výšky patek, což jde, neboť teď je zapuštění pro šrouby k desce zbytečně vysoké a stačila by výška pouze na matku M6. 
- Změnou délky trubek, což ale přináší i nutnost zmenit úhel trubek v držáku. Trubky jsou teď dlouhé 199mm. 

Asi bych navrhoval postup nejdříve změnšit výšku patek a teprve pak, když to nebude stačit, tak měnit délku trubek.  Protože potřebné snížení je v rozsahu 1-2cm. 

Celkové úkoly proto jsou: 

- [ ] Snížit výšku patek držáku
- [ ] Upravit rozměry tak, aby šroubové spoje vycházely na nějakou standardní délku šroubů.

**Comment by roman-dvorak** [comment]
Navrhuji vrchní tři díly (2-2, 3-1, 3-2, podle popisků výše) nahradit pomocí dílu, který je na obrázku. 

![51156690_375489903250615_2506315632866230272_n](https://user-images.githubusercontent.com/5196729/52242821-0006bf80-28d8-11e9-9eb7-e077880a492f.jpg)

Byla by to polovina položeného válce, ve kterém by byla drážka pro horizontální trubku vírníku. V ose tohoto válce by byla díra pro přidělání spony, která trubku přitáhne a zafixuje. Je potřeba zde dodržet dostatečnou toleranci, aby se zde vírnik mohl volně protáčet, jako to bylo doposud.

Tím se velmi zjednoduší demontáž, protože bude stačit vyšroubovat jeden šroub a je to lépe optimalizované pro 3D tisk.

**Comment by Elizaa62** [comment]
díl 888_3015.scad

**Comment by Elizaa62** [comment]
Patky opraveny.

**Comment by kaklik** [comment]
Držák funguje.
