### ISSUE TITLE
Označení typu na bočních plochách kapoty

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#18]
Na boční plochy je třeba vyznačit typ UAV v tomto případě TF-G1

**Comment by Elizaa62** [comment]
Přidán text. Akorát mám problém s písmenky. Z té jedné strany jsem text otočila, aby šel zprava doleva, akorát písmenko F je opačně tak než se píše a čte.

**Comment by kaklik** [comment]
Vypadá to, že je to tím, že parametr direction = "rtl" zřejmě funguje jinak, než by se dalo očekávat, neboť neotáčí ani písmena G a ani číslici 1. 
Řešením zřejmě je text klasicky orotovat v tomto případě podle osy Y. Rovnou jsem to zkusil a font při tom změnil na PT Sans. 

Ještě je potřeba vyřešit, aby text byl na boku skutečně vidět i po vyrenderování modelu.

**Comment by Elizaa62** [comment]
Písmo jsem v ose Z posunula o 0,5 mm. Nejsem si ale jistá, zda je to tak správně.

**Comment by kaklik** [comment]
přidal jsem tam linear_extrude(wall_thickness), aby text neměl nulovou tloušťku. 
Teď je třeba to doladit tak, aby se text vešel do maximálního tisknutelného rozměru a nebo ho naopak udělat inverzní dovnitř. 

Aktuálně se text nepropisuje na všechny díly právě díky tomu, že některé díly se ořezávají na maximální tisknutelný rozměr.

**Comment by Elizaa62** [comment]
Označení vytvořeno přes differenci. V ose z odečtení 0.3 mm. Zároveň jsem nápis v ose x posunula.

**Comment by kaklik** [comment]
Paráda :) Nápis jsem jenom posunul kousek níže, protože mi to tak připadá hezčí. 
Je to ale uzavřené.
