### ISSUE TITLE
Otočit držák pro GPS anténu

### ISSUE THREAD

**Issue by roman-dvorak** [Elizaa62/Components#180]
Držák z issue #25 je potřeba otočit tak, aby byla orientace podle následujícího obrázku. Trojúhelník by měl mít jednu těžnici rovnoběžně s osou vírníku. Deska může být umístěna na původním místě (kryt přes to lze nasadit)

![20190210_135302](https://user-images.githubusercontent.com/5196729/52539468-b528f400-2d7e-11e9-82ea-e3bb898c9e25.jpg)

Protože by jeden šroub vycházel přímo do horizontální trubky vírníku, tak to lze udělat tak, že podpírající sloupek bude o trochu širší a vyšší (je možné, že současné rozměry sloupku jsou dostačující). A na jeho spodní straně bude kapsa pro zasunutí matky.

![20190210_220152](https://user-images.githubusercontent.com/5196729/52539782-667d5900-2d82-11e9-8b5c-66330890358b.jpg)

**Comment by kaklik** [comment]
A není lepší spíš přijít na to, jak softwarově odrotovat ten senzor? 
Protože vyměnit celou podložku je poměrně drastický servisní zásah.  Navíc ještě k tomu současný držák docela funguje.

**Comment by roman-dvorak** [comment]
Ano, už asi vím, jak to otočit softwarově. Tohle issue nemusí být tedy vyřešeno hned. Ale pro další kus vírníku by to tak mohlo být. Navíc, když by z nějakého důvodu bylo potřeba, tak toto řešení umožňuje větší variabilitu umístění GPS na podložce.

**Comment by kaklik** [comment]
Pokud je známé softwarové řešení problému. Tak bych to navrhoval neřešit v modelu. Neboť další kus stejně bude mít GPS modul, který bude vypadat jinak.

**Comment by roman-dvorak** [comment]
Na novém kusu vírníku bude použita jiná GPS. Sloupky pro GPS budou dostraněny

Vyřešeno pomocí #212 a #214
