### ISSUE TITLE
Úprava držáku kotvy magnetu

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#182]
Současný [držák kotvy](https://github.com/ThunderFly-aerospace/TF-G1/blob/master/src/888_3004.scad) je potřeba upravit tak, aby k němu bylo možné přišroubovat novou kotvu. Jejíchž výkres vypadá takto (soubor kotva-magnetu.pdf): 

![image](https://user-images.githubusercontent.com/1194177/53335202-27f7aa80-38fb-11e9-8fca-0424c1d44051.png)

V podstatě je potřeba upravit hlavně rozteč šroubů pro upevnění.  Tištěný díl má dosedat na rovnou plochu kotvy ke které se upevňuje dvěma zapuštěnými šrouby.  Průměr základny tištěného dílu se může trochu upravit, aby nějak rozumně odpovídal rozměrům kotvy.

**Comment by Elizaa62** [comment]
Upravila jsem průměr z 70 na 75. Dále rozteč šroubů jsem nastavila dle uvedeného výkresu na 42,5. Oboje jsem raději nastavila parametricky. 
Je zde ještě něco dalšího, co je potřeba udělat?

**Comment by kaklik** [comment]
Super, tohle bych řekl, že je tím hotové. Jenom to teď vytisknu a vyzkouším, jestli to pasuje. :)

**Comment by kaklik** [comment]
Pasuje to! :) 

![crop](https://user-images.githubusercontent.com/1194177/57336577-a73d0200-7126-11e9-9ba6-9fcbeabc1d41.jpg)
