### ISSUE TITLE
Vypouštěcí zařízení pro start z lana

### ISSUE THREAD

**Issue by roman-dvorak** [Elizaa62/Components#187]
Do dílu 888_1026 (Držák tažného motoru) je potřeba integrovat vypouštěcí zařízení, které umožní odpojit tažné lano pomocí dálkového ovladače a serva na vírníku.

Princip zařízení je vidět na tomto orázku:
http://www.gliders.uk.com/images/0723470.jpg

V dílu 888_1026 bude podélná štěrbina. U vstupu bude vysoká, aby umožňovala velký úhel tažného lana, a její výška se bude postupně snižovat. Příčně, přes tuto díru, bude osa - dlouhý M3-A2 šroub. Tento šroub je potřeba orientovat tak, aby nedocházelo k jeho povolení tím, že se o něj bude lano smýkat.. O tuto osu se z horní strany bude opírat ocelový drát veducí až k servu, které bude za drát tahat. Po vytažení ocelového drátu servem dojde k uvolnění lana. 
![20190604_004104](https://user-images.githubusercontent.com/5196729/58839322-afbf2480-8661-11e9-85cc-bc0ce695fff6.jpg)

Navrhovaná realizace je na následujících náčrtcích:

![navrh_01](https://user-images.githubusercontent.com/5196729/58838631-87362b00-865f-11e9-8f45-5f27966a489d.png)

![navrh_02](https://user-images.githubusercontent.com/5196729/58838636-89988500-865f-11e9-8d7f-3924fdd9843e.png)

Předpokládané umístění serva je takto:
![20190602_174145](https://user-images.githubusercontent.com/5196729/58838723-c8c6d600-865f-11e9-87ec-cdc86a00c100.jpg)
Servo je potřeba, vzhledem ke směru tisku, orientovat tímto směrem.

Je potřeba brát v ohled, že se skrze tento díl se přenáší veškerý tah motoru a je tedy potřeba co nejvíce zachovat jeho pevnosti.

**Comment by kaklik** [comment]
Nepodařilo se mi přijít na to jak je ta konstrukce vymyšlená.  Jedinné umístění serva ve kterém tam pasuje je toto: 

![image](https://user-images.githubusercontent.com/1194177/60337252-d5aac100-99a2-11e9-995d-96e399de8756.png)

![image](https://user-images.githubusercontent.com/1194177/60337269-e4917380-99a2-11e9-9ac4-67936ac8ee6f.png)

Tohle řešení ale má několik problémů. 

1. Páka serva nevychází naproti drážce pro páku a táhlo. 
2. Servo drží pouze na jednom šroubu
3. Přesahuje mimo model do zadní části

Při konstrukci dílu je třeba také myslet na to, že na díl má pak nějak navazovat [horní kryt](https://github.com/ThunderFly-aerospace/TF-G1/blob/master/STL/666_1025.stl).

**Comment by roman-dvorak** [comment]
@cesilko1 Myslíš, že takto je to hotové? Mě přijde ta drážka pro příchytku serva dost úzká. Jak je v modelu široká? Jsou tam započitané dostatečné tolerance?

Jak je plánovaný tisk tohoto dílu?

**Comment by raska-vilem** [comment]
@roman-dvorak jestli jsem správně pochopil tohle http://file.yizimg.com/357982/201719-11844730.pdf tak je ta drážka o 0.5mm větší

**Comment by kaklik** [comment]
Mě přijde že tam je hrozně málo místa pro páku serva a taky na úchyt táhla na páku serva. 

![image](https://user-images.githubusercontent.com/1194177/60881869-eb43a480-a246-11e9-826d-8dc5967c5ce9.png)

**Comment by roman-dvorak** [comment]
Vidím další změny.. 
https://github.com/ThunderFly-aerospace/TF-G1/blob/master/STL/888_1026.stl

Takhle se mi to už líbí podstatně více. @kaklik co si o tom myslíš teď?

**Comment by kaklik** [comment]
Ten model je původně plánovaný pro tisk v [této pozici](https://github.com/ThunderFly-aerospace/TF-G1/blob/master/STL/print_plate_1026_engine.stl).

Nevím jak se vytiskne ten převislý držák serva. Nechal jsem to tisknout s podporami a uvidíme, jaký bude výsledek.

**Comment by roman-dvorak** [comment]
Pro tisk bez podpor je potřeba do dílu namodelovat podpory ručně v místě serva a vytvořit drážku pro vyvedení kabelu serva.

![20190721_000705](https://user-images.githubusercontent.com/5196729/61584649-b93a1880-ab4b-11e9-9b09-acad8a4693d1.jpg)

**Comment by kaklik** [comment]
Takhle konstruovaná podpora integrovaná do modelu nebude dobře fungovat. 

![obrazek](https://user-images.githubusercontent.com/1194177/61634973-d3cad980-ac92-11e9-898e-503eddeea52e.png)

Je potřeba aby byla co nejtenčí. Ideálně jen velmi málo nad 0.61mm. Zároveň je také potřeba aby podpírala převis v celém profilu a nebo, aby umožnila jednoznačným způsobem tisknout most.  Vzhledem k tomu, že je převis ukosený, tak to v tomhle případě jednoznačné není. Podpora by tak ukosená musela být taky.

**Comment by raska-vilem** [comment]
tak jsem upravil supporty, tloušťka se dá nastavit proměnnou `supports_thickness` na řádku 33

**Comment by kaklik** [comment]
Rozteč šroubů pro uchycení serva je příliš velká. 
V modelu jsou zřejmě použity šroby M2,5 ale reálně servo má být přichyceno šrouby M2.
