### ISSUE TITLE
Zlepšení odpružení předního kola

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#189]
Upevnění předního kola by mělo být přesunuto do dílu [držáku motoru](https://github.com/ThunderFly-aerospace/TF-G1/blob/master/STL/888_1026.stl). 

Zároveň je potřeba aby bod otáčení kola byl přímo pod místem uchycení na trubu, nebo více vzadu, aby nedocházelo k vyvrácení kola při nárazu na překážku.  Nejpoužívanější řešení jsou tato: 

![61762095_592538947922434_736684447151161344_n](https://user-images.githubusercontent.com/1194177/58993351-95b24d00-87ed-11e9-9fce-e59f2265838a.jpg)

**Comment by kaklik** [comment]
@roman-dvorak  čím se vůbec liší ty dva obrázky vpravo?  V tom nákresu zřejmě asi chybí parametry úhlů a závleku kolečka popsané v [tomto článku](https://www.kitplanes.com/where-the-rubber-meets-the-runway/).

**Comment by roman-dvorak** [comment]
Tam se to lišio umístěním kloubů. U jedné konstrukce je píst stále svisle dulů (pod konstatním úlhem) a klouby jsou pouze na 'torque linku'. V této konstrukci jsou také úhly kolečka a závleku konstantní po celou dobu chodu pístu. 

Druhá kontrukce je udělaná tak, že se tyto úhly mění s dle stlačení pístu. V posledním obrázku zřejmě nejsou úplně korektně značené klouby.

**Comment by roman-dvorak** [comment]
K absorci nárazu byly zvoleny písty [RT/57208/M/25](https://www.tme.eu/cz/details/rt_57208_m_25/pracovni-valce/norgren-herion/). Použije se jejich dvojic, která bude umístěna ze strany kolečka. Přední podvozek se bude skládat z několika dílů, ktré zajistí 

![20190819_093604~2](https://user-images.githubusercontent.com/5196729/63247293-01407e00-c265-11e9-97b4-6d8d1320d3a9.jpg)

![20190819_013122](https://user-images.githubusercontent.com/5196729/63247346-20d7a680-c265-11e9-8014-367177277439.jpg)

Kolečko bude využito z issue #191. To bude umístěno v H dilu. Z jedné strany do něj bude vlozeno kolečko a z druhé bude pomocí ložisek (696) připvněn druhý díl. Díl se může na horní straně sbíhat. To se uvidí podle poměru velikostí. 

Další díl je taková "páka" která bude pod nosníkem vírníku umístěna na šikmo. To má za úkol stabilizovat pohyb a samotné kolečko. 

V obou dílech musí být přípevňovací body pro připevnění pístu. Dole to bude realizováno pomocí kulového očka IGUS (KBRM-03) upevněného M3 pevnostním šroubem.  Nahoře bude na píst nasazený vytištěný díl, který bude s pístem sešroubován pomocí M3 šroubu a skrz vidlici povede jeden (asi) M6 šroub. Ten bude uložen ve dvojici ložisek 696. 

Kdyby byly další nejasnosti @cesilko1, tak určitě piš.

**Comment by kaklik** [comment]
Ten šikmý díl pro uchycení kola by zřejmě neměl přesahovat dopředu více, než je vzdálenost od místa uchycení k vrtuli. 

Otočná a pevná část by také měla obsahovat nějaké dorazy, aby rozsah otočení směru kola byl omezený.

**Comment by roman-dvorak** [comment]
U tohoto dílu je potřeba zúžit díly tak, aby bylo možné použít do ložisek M4 šrouby. Nejdéle tedy M4x55 ale i užší díly by byly dostatečné. 

- [x] Zúžit ramena
- [x] Zvětšít caster úhel
- [x] Prodloužít díl pod podložkou
- [x] Posunout kolečko více dopředu, počítat to z nastavení úhlu motoru
- [x] Ve vidlici použít M4 šroub
- [x] Posunout uchycení pístu nad osu kola.

**Comment by roman-dvorak** [comment]
- [x] Špatně vypočítaná délka osy kolečka
- [x] Ve středním dílu není otvor na ložiska
- [x] Chybi zapuštění pro matku a hlavu šroubu ve spodním díle

1) nejdelší M4 šroub, co máme je M4x55. Aktuální rozměry zapuštění šroubu by byly akorát pro M4x60.
![20190922_111602_HDR](https://user-images.githubusercontent.com/5196729/65394316-79322480-dd8c-11e9-9e19-101e6f1ea495.jpg)
 
2) V prostředním dílu předního kolečka chybí otvoy pro ložisko
3) Na horní části spodního dílu chybí zapuštění pro matku a hlavu šroubu (osy tohoto kloubu) Díky tomu nelze tento spoj dotáhnout bez použití více nástrojů
