### ISSUE TITLE
Šrouby pro fixaci krytu

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#19]
Horní část kapotáže 666_1025 by měla být fixována šrouby s matkami zapuštěnými do dílu 666_1027. Matky by měly být zapuštěny a fixovány tak, aby šrouby bylo možné zašroubovat bez přidržování matek. 

Stačí jeden šroub z každé strany každé části krytu.

**Comment by Elizaa62** [comment]
Přidány díry pro šrouby do dílu 666_1025.

**Comment by Elizaa62** [comment]
Upravila jsem výšku těch děr, nevšimla jsem si, že je mám každou jinak vysoko. Na té podložce pracuju.

**Comment by Elizaa62** [comment]
Hotovka.

**Comment by kaklik** [comment]
Myslím ze na podložce 1027 jsou ty otvory pro matky nerovnoměrně daleko od kraje. Teď se to projevilo při umisťování akumulátorů.

**Comment by Elizaa62** [comment]
Myslíš otvory pro matky pro připevnění horního krytu?

**Comment by kaklik** [comment]
Ano myslím, na jedné straně jsou blíže k okraji, než na druhé. Je to vidět při tomto pohledu: 

![image](https://user-images.githubusercontent.com/1194177/33965337-d4b0b11c-e05b-11e7-8d0e-1b68d463c09d.png)

**Comment by kaklik** [comment]
Zjistil jsem že otvor pro matky je příliš úzký a matka se tam svojí výškou nevejde. Zrovna v tomhle směru ale nevadí i celkem velká tolerance.  Kritický je rozměr v kolmém směru, tam matka teď pravděpodobně sedí dobře, tak akorát, aby se neprotáčela.

**Comment by Elizaa62** [comment]
Otvor pro matku zvětšen na výšce matky o 1 mm.

**Comment by kaklik** [comment]
Ano, otvor pro matku je zvětšen správně. :) 

Na konci otvoru je ale 6tihran, který má matku zřejmě držet. Zdá se mi, že ten zůstal stejně vysoký: 
![image](https://user-images.githubusercontent.com/1194177/34341109-da195454-e990-11e7-80ed-44bf354f1294.png)

Pro zjednodušení by možná i stačilo, kdyby na konci otvoru nebyl šestihran, ale otvor může končit obdélníkem. Zajištění matky proti otáčení na dvou stěnách by mohlo stačit.

**Comment by Elizaa62** [comment]
Už je tam šestihran, musela bych to celé opravovat. Otvor pro držení matky je taky zvětšen o 1 mm.

**Comment by kaklik** [comment]
Vyřešeno. :)
