### ISSUE TITLE
Nový způsob připevnění předního kola ve vlečném uspořádání

### ISSUE THREAD

**Issue by roman-dvorak** [Elizaa62/Components#190]
Toto issue nezahrnuje odpružení předního kola z #189. Je to pouze alternativa k tyči, která se rozbila při pokusu o přistání. Mělo by to být bytelnější a nemít chyby z predchozí konstrukce. Navíc by to mělo být ve vlečném uspořádání (kolečko směrem dozadu - ne dopředu) To nám umožňuje použít menší servo.

Připevnění předního kola bude místo podložky pro přimagnetování na platformu v dílu #172. V dílu držáku motoru jsou dvě díry M4, do kterých se strčí dva šrouby. Ve sloupku budou teda díry na šrouby a kapsy na matky. Sloupek bude kónický.  Celý sloupek bude rozdělen na dva díly kvůli tisku. Tyto dva díly budou také sešroubovány - budou stačit pouze M3 šrouby, protože budou jen tyto dva díly držet pohromadě. Celé to bude stažené pomocí lícovaného šroubu v ose dílu. Matka M5 bude v kapse. 

Spodní část bude navazovat kónicky na první (horní) polovinu. Na horní části spodní poloviny bude taková "destička" ve které bude přidělané servo pomocí dvojice šroubků.. Lépe to bude vidět na obrázku :) 

![20190606_232244](https://user-images.githubusercontent.com/5196729/59067589-5568d280-88b2-11e9-9571-a3b8b43fa3e9.jpg)

 Je potřeba zajistit, aby táhlo od serva vycházelo kolmo na páku spodní vidlice a aby odpovídala výška páky serva a páky vydlice - je vhodné si následně udělat sestavu, ve které je toto dobře vidět. 

Ještě bude potřeba změřit nějaké další rozměry toho serva. V dílu pro malý vírník nejsou dostatečné parametry - pouze šířka a hloubka.

**Comment by kaklik** [comment]
Je toto ještě relevantní? 

Řekl bych, že toto je již zastaralé issue, neboť v této chvíli to už musíme vyřešit lépe. Navíc neplánuji přední kolečko mít řízené.
