### ISSUE TITLE
3D tištěný náboj mechového kola

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#191]
Do mechového kola je potřeba navrhnout 3D tišténé disky do kterých se vloží ložiska s nábojem. 

![62085972_344618962870217_7902652164357488640_n](https://user-images.githubusercontent.com/1194177/59221592-f368df80-8bc7-11e9-9f95-94894a995e40.jpg)

Konstrukce disků může být například takováto: 

![62307472_421748008671827_73653702669369344_n](https://user-images.githubusercontent.com/1194177/59221639-04b1ec00-8bc8-11e9-82ca-70937dede42f.jpg)

Ložiska použitá na kole budou 608. Středový šroub by měl být alespoň M5.  Kolo by mělo umožnit použití jak pro stranovou montáž, tak i pro použití ve vidlici. 

Model je jeden z potřebných pro vyřešení issue #166  Proto by bylo potreba, aby vysledkem byla podsestavakolecka, vcetne molitanu.

**Comment by roman-dvorak** [comment]
![20190610_230121~3](https://user-images.githubusercontent.com/5196729/59299765-c1ba4c00-8c8d-11e9-89e6-3744c5b1fc56.jpg)

budou to dva disky, které budou mít na sobě válec, který je bude držet v nějaké určité vzdálenosti. Budou staženy trojicí šroubů. 

Vnitřní díl se musí dotýkat pouze vnitřní části ložiska. Je vhodné tam udělat takový kružek, který zajistí dostatečnou vzdálenost od zbytku ložiska.

**Comment by alcamrkvicka** [comment]
Disky pro mechove kolo ... 888_1029
![disk](https://user-images.githubusercontent.com/51204144/59338277-62e2ea00-8d02-11e9-9345-1703d79db201.PNG)
![disk1](https://user-images.githubusercontent.com/51204144/59338294-670f0780-8d02-11e9-8a06-d3b7c6b8cc2e.PNG)

**Comment by roman-dvorak** [comment]
tu vnitřní díru je potřeba výrazně rozšířit. Nastavit jí průměr něco jako ```608_bearing_outer_diameter - 5```. Tím se zajistí, aby nedocházelo ke zbytečnému tření mezi vnitřní (statickou) částí ložíska a vytištěným dílem (který se bude točit). 

Dále je potřeba přes tuto díru udělat přemostění, které zajistí lepší kvalitu výtisku. Takto by se při výrobě materiál propadal.

**Comment by alcamrkvicka** [comment]
Lozisko cele zapusteno do disku.
![111](https://user-images.githubusercontent.com/51204144/59549804-2eba3400-8f63-11e9-84bb-f492db4dc9d0.PNG)
![222](https://user-images.githubusercontent.com/51204144/59549807-311c8e00-8f63-11e9-9cd6-5e2b06d29812.PNG)

**Comment by roman-dvorak** [comment]
Model obsahuje několik chyb:

- [x] Disky mají mezi sebou velkou mezeru - zřejmě je to způsobeno špatným použitím parametru
- [x] Mezeru mezi disky nechat 1 mm.
- [x] Zvětšit průměr vnějšího disku na 51 mm (parametr už taktéž existuje)
- [x] Zajistit použití šroubu M3x30 - je potřeba správně napočítat jeho délku a správně zapustit jeho hlavu do dílu. 

![20190615_235751](https://user-images.githubusercontent.com/5196729/59556941-b25c3b00-8fcc-11e9-9790-96d32bd1dcc1.jpg)

![20190616_000121](https://user-images.githubusercontent.com/5196729/59556942-b5efc200-8fcc-11e9-9d80-5c9cb57dc639.jpg)

**Comment by alcamrkvicka** [comment]
Chyby opraveny, zapusteni hlavy je udelano pro sroub M3x35.
![xxx](https://user-images.githubusercontent.com/51204144/59914784-615ca480-941b-11e9-9069-2761a07e7c67.PNG)
![xxxx](https://user-images.githubusercontent.com/51204144/59914792-6588c200-941b-11e9-9413-0ee16c2cbf96.PNG)

**Comment by kaklik** [comment]
Tak jsem vytištěný náboj zkoušel složit a mám tyhle poznatky

- [x] Překrytí otvoru vrstvou materiálu se blbě vyřezává, protože zde není jen jedna vrstva, jejíž tloušťka by byla definována parametrem [layer_thickness](https://github.com/ThunderFly-aerospace/Auto-G2/blob/dd94fedd44c93dcea9dbe41fe11ccf57465f813d/CAD/parameters.scad#L4)
- [x] Nevychází délka vnitřní vložky pro šroub M5 a kus přečnívá i na složeném nedotáhnutém kole.
- [x] Středová vložka se blbě tiskne, díky tenké stěně okolo šroubu. S ohledem na použití původně navržené vidlice bych asi stejnak  byl pro změnu šroubu na M4. Myslím že je pro plánovanou aplikaci dostatečný. 

![kolecko](https://user-images.githubusercontent.com/1194177/60055227-35704600-96dd-11e9-8c0b-0dddaa7ba76c.JPG)

**Comment by alcamrkvicka** [comment]
Melo by to byt spravene. Ta spatna delka vnitrni vlozky vznikla kvuli zmene zapusteni loziska - puvodne melo byt zapustene jen z poloviny.
![image](https://user-images.githubusercontent.com/51204144/60083135-6aa88280-9735-11e9-8c63-6994a6182387.png)
Nyni by mezi vnitrnimi vlozkami mela byt 2 mm mezera.

**Comment by kaklik** [comment]
Ok, ale mezi vnitřními vložkami mezera být nemůže.  Neboť principem té vložky je právě vlastnost, že ten šroub který vložkami prochází utáhnu tolik, aby se vložky stáhly k sobě. Zároveň ale tahle vzdálenost vyjde přesně taková, že stažením vložek nevznikne boční tlak na vnitřní kroužky ložisek. 

Výsledek má být, že kolo se může volně otáčet na dovou stažených vložkách, ale nemůže dojít k jeho posuvu po vložce.

**Comment by alcamrkvicka** [comment]
dobre, je to prodlouzene akorat, aby se dotykaly. Mne bylo na zacatku receno, ze se dotykat nemusi, proto jsem to tak udelala

**Comment by roman-dvorak** [comment]
Vidlice ke kolečku je moc úzká - zřejmě nepočítá s vnějšími podložkami. Lépe je to vidět na obrázku
![20190630_004014](https://user-images.githubusercontent.com/5196729/60390372-992bb200-9ad5-11e9-839c-5697422de3db.jpg)

**Comment by roman-dvorak** [comment]
Z vložky do ložiska je potřeba odebrat vnější límec, který měl původně sloužit k ochraně ložiska. To zatím není potřeba a nyní to způsobuje, že vidlice musí být velmi široká.

**Comment by roman-dvorak** [comment]
Vnitrnimu dilu odebran vnejsi limec na ochranu loziska pred pocasim. 
Upraveny rozměry náboje, změněno zapuštění šroubu, přidána plná vrstva nad otvor pro matice.

**Comment by kaklik** [comment]
Vnitřnímu dílu ložiska chybí osazení, které by se opíralo o obvod vnitřního kroužku a bránilo kontaktu límce s otáčejícím se krytováním ložiska. 
Absence tohoto osazení, které v modelu původně bylo zároveň ovlivňuje boční vůli kolečka na vnitřních vložkách šroubu M4.  Kolečko se nyní může zhruba o milimetr hýbat ze strany na stranu.

**Comment by kaklik** [comment]
Myslím že vnitřní kroužek na model @roman-dvorak  doplnil.
