### ISSUE TITLE
Úprava držáku kotvy magnetu

### ISSUE THREAD

**Issue by ChroustJan** [Elizaa62/Components#192]
Je potřeba vytvořit nový díl, který bude držet kovovou část (žlutě ohraničený díl), která se chytá na magnet na střeše auta. Je potřeba, aby se aktuální umístění kovové části posunulo o svůj celý průměr dozadu do bíle vyznačené oblasti (bude nově začínat tam kde aktuální končí). Viz znázornění na fotce. 

![foto_drzak_mag](https://user-images.githubusercontent.com/9783606/59246895-fd1d3200-8c1d-11e9-8eea-d507c51f19ea.jpg)

Díl by měl vzniknout úpravou držáku předního kolečka.

**Comment by roman-dvorak** [comment]
![20190611_201316~2](https://user-images.githubusercontent.com/5196729/59296429-4608d100-8c86-11e9-8924-09ab650f271f.jpg)

Při vytváření tohoto dílu lze vycházet z 888_2003, který byl umístěn na stejném místě. Popřípadě ho rovnou upravit. 
![888_2003](https://user-images.githubusercontent.com/5196729/59296586-9ed86980-8c86-11e9-8d9d-cb2471f64988.png)

**Comment by ChroustJan** [comment]
Je důležité, aby ten držák byl trochu vysunutý, aby nedošlo ke kolizi s tím modrým dílem držící motor. Podle mě bude určitě stačit 1cm pod tu fialovou desku UAV. Možná i 5mm.

**Comment by kaklik** [comment]
Současný držák 888_2003 je vysunutý příliš a zbytečně zvedá vírník nad magnet.

![image](https://user-images.githubusercontent.com/1194177/60047730-b7a33f00-96ca-11e9-8afb-f7a57f932699.png)

Je potřeba aby držák co nejméně přečníval pod spodní stranu desky vírníku.


![montaz_magnetu](https://user-images.githubusercontent.com/1194177/60052569-e5da4c00-96d5-11e9-92ae-58fcc5eb0fb0.JPG)

**Comment by ChroustJan** [comment]
Je potřeba provést opravu dílu. Skrz celý materiál je šestihranný otvor. Matice propadá.

![IMG_20190630_162916](https://user-images.githubusercontent.com/9783606/60491612-76ea8d80-9ca9-11e9-9fc3-d4172606ef62.jpg)

**Comment by kaklik** [comment]
Na opraveném dílu kotva magnetu drží.
