### ISSUE TITLE
Úprava ocasních ploch

### ISSUE THREAD

**Issue by roman-dvorak** [Elizaa62/Components#194]
Existující řešení ocasních ploch ve tvaru písmene H má řadu problémů, které by vyřešily ocasní plochy ve tvaru písmene A. Pro toto issue lze vycházet z existujícího modelu ocasních ploch. Toto řešení by mělo zvětšit pevnost ocasu a snížit možnost střetu s rotorem.

Nově bude ocas přidělán pomocí dvojice trubek (D=10mm), které budou vycházet z podložky vírníku. 

Servo bude nahrazeno servem  (BMS-115HV) s otvory pro boční přidělání. Tato úprava má hlavní přínos v tom, že bude podstatně snazší servo demontovat a vyměnit. Rozměry tohoto serva mám oměřené. 

Ocasní plochy by se měly skádat ze dvou částí, které budou na horní straně vzájemně sešroubované.

Tvar ploch  by měl vycházet z [existujícího modelu](https://github.com/ThunderFly-aerospace/TF-G1/blob/master/src/666_1028.scad). 

![20190615_235855](https://user-images.githubusercontent.com/5196729/59557238-184cc080-8fd5-11e9-8b50-fc08ef03c4e0.jpg)

**Comment by kaklik** [comment]
Issue, které se zabývá uchycením serv v ocasních plochách je zde: https://github.com/ThunderFly-aerospace/TF-G1/issues/120

**Comment by alcamrkvicka** [comment]
![666_1028](https://user-images.githubusercontent.com/51204144/60052438-8f6d0d80-96d5-11e9-89b0-4a0d9acb1f31.png)
![666_1028_1](https://user-images.githubusercontent.com/51204144/60052449-96941b80-96d5-11e9-9281-3bc024ffcdf4.png)

Cast pro zapusteni je navrzena na sroub M3x15 ISO7380

**Comment by roman-dvorak** [comment]
Protože pro přidělání ocasních ploch budou použity uhlíkové trubky s vnějším průměrem 10 mm a musí být skrze ně provlečeny alespoň 3 dráty k servům, tak není možné trubku provrtat a sešroubovat. Při tomto postupu navíc hrozí výrazné oslabení pevnosti trubky a její následné zničení vlhkostí. 

Proto byl vymyšlen postup, že na konci trubky bude takový vytištěný "adaptér", který se na trubku nalepí a sešroubuje se zbytkem směrovky. 

Je potřeba aby tento adaptér odpovídal profilu křídla. Ze zadní strany by měl mít otvor na provlečení kabelů. Jeho spojení se zbytkem směrovky by bylo provedeno sešroubováním. Jako nejlepší místo na sešroubování mi připadá umístit šrouby pod a nad připevňovací trubku, kdy by se šroub zastrčil ze předu. V hlavním díle směrovky by byly díry na kapsy pro matky a díry pro šrouby.

Trochu načrtnuté je to zde. Pokud jsou nějaké nejasnosti, ptej se na cokoliv :

![20190813_131916](https://user-images.githubusercontent.com/5196729/62938786-0e2a2100-bdd0-11e9-9071-65c68a488dce.jpg)

**Comment by kaklik** [comment]
Já bych to asi raději viděl tak, aby se ten díl šrouboval ke směrovce zboku, nikoli zepředu. Část toho dílu by tak stále byla permenentně součástí směrovky. Domnívám se, že se to tak bude i lépe tisknout. 

V jaké poloze se vůbec bude tisknout tahle nová směrovka?   Moje představa je, že bude spodní hranou profilu stát na podložce.  
Aby ale v takovém případě mohl být vytištěn otvor pro pohyblivou část směrovky, tak směrovka musí být zkosená.

**Comment by roman-dvorak** [comment]
Já jsem totiž myslel, že se to bude tisknout náběžnou hranou dolů. Je blbé, že pak ta hrana není hezká. Aby se to tisklo na stoajto, tak ta zkosená hrana bude muset být dost zkosená. To mi skolo vychází tam vymodelovat podpory ručně a nahoře udělat most. Ta podpora by měla stále tvar airfolu té směrovky jen by tam bylo dutá komora. 

A z toho předpokladu, že se to bude tisknout na náběžnou hranu, tak jsem zvolil šrouby takto umístěné. Při bočním umístění šroubů se bojím toho, aby kvůli šroubům se směrovka zbytečně neztlusťovala.

**Comment by kaklik** [comment]
Ten tisk na náběžné hraně není optimální. Vyžaduje v modelu vymodelovaný brim, který je pak třeba odřezávat. 
Použití vymodelovaných podpor místo úkosu je dobrý nápad. 

Na šrouby tam může být boule, která může být i součástí boule pro trubku.

**Comment by taury55** [comment]
> 
> 
> Existující řešení ocasních ploch ve tvaru písmene H má řadu problémů, které by vyřešily ocasní plochy ve tvaru písmene A. Pro toto issue lze vycházet z existujícího modelu ocasních ploch. Toto řešení by mělo zvětšit pevnost ocasu a snížit možnost střetu s rotorem.
> 
> Nově bude ocas přidělán pomocí dvojice trubek (D=10mm), které budou vycházet z podložky vírníku.
> 
> Servo bude nahrazeno servem (BMS-115HV) s otvory pro boční přidělání. Tato úprava má hlavní přínos v tom, že bude podstatně snazší servo demontovat a vyměnit. Rozměry tohoto serva mám oměřené.
> 
> Ocasní plochy by se měly skádat ze dvou částí, které budou na horní straně vzájemně sešroubované.
> 
> Tvar ploch by měl vycházet z [existujícího modelu](https://github.com/ThunderFly-aerospace/TF-G1/blob/master/src/666_1028.scad).
> 
> ![20190615_235855](https://user-images.githubusercontent.com/5196729/59557238-184cc080-8fd5-11e9-8b50-fc08ef03c4e0.jpg)

Ty trubky, na kterých budou plochy uchecny mají jaký rozestup?

**Comment by roman-dvorak** [comment]
V modelu je několik nových problémů:

- [x] Stěna profilu je moc tlustá. Dříve pro to existoval parametr, který tuto šířku definoval.
- [x] Díra na servo je moc nízká
- [x] Příčka pro připevnění serva je moc blízko vnitřnímu kraji
- [x] Pozice otvoru je špatná - páka serva vychází na spodní část směrovky

**Comment by roman-dvorak** [comment]
Pokud jsou předchozí body nesrozumitelné, tak tady je rozepisuji:

1. to je asi jasné

2. Servo se do otvoru nevejde na výšku. Chybí tam asi 1 mm. Ale i pokud se to rozšíří o 1 mm na některou stranu, tak díry pro připevnění serva jsou ve špatné výšce. 
Na obrázku je nakreslen rozměr, kterým myslím výšku otvoru
![Snímek z 2019-09-02 20-53-24_01](https://user-images.githubusercontent.com/5196729/64131586-d0fef080-cdc9-11e9-8c7d-dae309688041.png)

3. Uvnitř otvoru pro servo jsou 2 "stěny" za které má být servo přišroubované. Připadá mi, že jsou úplně uprostřed. Je potřeba je posunout trošku k vnější straně směrovky. Důvod, tohoto posunu je, že nyní servo bude velmi vyčuhovat ven z profilu
![Snímek z 2019-09-02 20-53-24_02](https://user-images.githubusercontent.com/5196729/64132112-79628400-cdcd-11e9-80b7-6982b3eb80be.png)

4. Pokud bude servo v součastném otvoru směrem dolu, bude to vycházet tak, že táhlo bude na spodním okraji pohyblivé části směrovky. Bude to vycházet tak, že kabel od serva bude vždy na vzdálenější straně od tyče. Ale to se asi musí vyřešit šikovně udělanou cestičkou.

![Snímek z 2019-09-02 22-14-38](https://user-images.githubusercontent.com/5196729/64132293-1b36a080-cdcf-11e9-88ef-6528f766f10a.png)

**Comment by roman-dvorak** [comment]
Po vytištění směrovek se ukázalo několik problémů. 

 - [x] Výplň v horní části
 - [ ] Silnější horizontální stěny v okolí podpor
 - [x] Zaslepit otvor pro osu pohyblivé části
 - [x] Zvětšit otvor pro protáhnutí kabelu od serva
 - [x] Posunout umístění díry pro připevnění serva
 - [x] Zdvojnásobit tloušťku pláště

1) V části, kde je zešikmení pro sešroubování dvou polovin je problém, že neni namodelovaný infill. Infill je potřeba mít namodelovaný až do konce. Pokud se to tiskne bez infillu tak tam díky velkému zšikmení nedrží vrstvy po hromadě a je to velmi měkké.

2) V místech, kde jsou domodelované podpory (tedy v místě pohyblivé části a v místě, kam patří adaptér na tyč) jsou velmi tenké horní a spodní stěny. V těchto místech bych to navrhoval zesílit (alespoň na 2 - 3 vrstvy). Protože situace je taková, přemostění není moc kvalitní - jsou v něm velké mezery. A snadno se trhá. To i při vyřezávání podpor. 
Další vhodná úprava by bylo nad  a pod podporami udělat droubou mezeru, aby zde plast nebyl tak doře spojen.

3) Ve spodní části směrovky nemít díru pro osu směrovky až veskrz. Nechat pod ní pár vrstev (více než 1) Díky tomu se nebude muset zalepovat tavným lepidlem. Nahoře tyčky budo zajištěny tím, jak se směrovky sešroubují.

4) Vytvořený tunel je moc nízký. Nelze tam prostrčit dráty od serva, která jsou dosti měkká. Je potřeba tam vytvořit drážky. Buď po celé délce. Nebo alespoň do poloviny výšky rámečku serva. 


![20190907_144944](https://user-images.githubusercontent.com/5196729/64475265-ce611a00-d180-11e9-91e2-519580d45e2a.jpg)

5) Díru pro připevnění serva je potřeba posunout výš o 2 mm. Díry posunout trochu od kraje o cca 1 mm. Díra se nyní trošku propadá dovnitř z důvodu tenké stěny.

![20190907_145021](https://user-images.githubusercontent.com/5196729/64475275-e8026180-d180-11e9-952a-64301e2dbdfa.jpg)

**Comment by roman-dvorak** [comment]
Směrovka pro nový model je zřejmě dost malá. Je potřeba zvětšit její plochu. Vzhledem k tomu, že je využit celý tiskový prostor, musí se model rozdělit na více částí. Zároveň by se tím dal vyřesit problém potřeby modelovat podpory.

Představoval, bych si to tak, že se to rozdělí na 3 části. Spodní část, prostřední část - část, kde je pohyblivá část směrovky a třetí část by byl horní zbytek. Tyto 3 části by se následně slepily. popř. sešroubovaly.

Díky tomu je možné zvětšit výšku střední části do tiskárny a zároveň by bylo možné zvětšit hloubku profilu.

**Comment by roman-dvorak** [comment]
Dneska jsme složili novou verzi směrovky. Ukázalo se několik problémů.

- [x]  Nelze složit pohyblivá část směrovky s pevnou částí. Problém je, že díry pro tyčku jsou moc blízko konci výřezu pro pohyblivou část.
![20191005_235121](https://user-images.githubusercontent.com/5196729/66275313-90dad400-e887-11e9-808c-fed700f7e208.jpg)

- [x] Servo přesunout tak, aby kabel vedl rovnou do tyče. Nový prodloužený profil to dovoluje. Přinese to výrazně rychlejší skládání. 
![20191006_192738](https://user-images.githubusercontent.com/5196729/66275353-0181f080-e888-11e9-8b12-b2cf6cb9971c.jpg)

- [ ] Použít jiný způsob modelování tohoto křídla. Jak to funguje, jsem se snažil popsat na [wiki](https://github.com/ThunderFly-aerospace/TF-G1/wiki/Modelov%C3%A1n%C3%AD-k%C5%99%C3%ADdel) Zřejmě to stále není dostačující. Takže jestli to z toho nechápeš, prosím napiš, pokusím se Ti doupřesnit, jak je to myšleno. 

- [x] Všechno má strašně silné stěny. Stačil by jeden perimetr - pokud vyřešíš předchozí bod, tak toto nebudeš muset řešit. Protože to pak vyřeší slicer.

**Comment by roman-dvorak** [comment]
- [x]  Infill je dost hustý. Navrhuji zkusit vzdálenost výztuh nastavit na nějkých cca 130 % z aktuální hodnoty

- [x] Odebrat díry pro vyztužení pomocí uhlíkových tyček. Zároveň tam pak nemusí bý ty plné výplně, které mají tyčky držet. Konstrukce se tím znovu odlehčí.

- [x]  Pozice otvoru na servo je OK. Servo umístit blíže k vnější straně. Pokud servo vložím ze strany, kde je přepážka blíže ven, tak by to chtělo servo zapustit o 1 mm hlouběji.  Příčku, ketrá podepírá serrvo udělat tlustší (až na druhou stranu k vnější stěně profilu. Pro připevnění serva by se použily samořezné šrouby. Vzdálenost otvorů pro šrouby by měla být 28 mm. Průměr této díry ještě upřesním. 

- [ ] Na vnější straně směrovky zrušit díru pro servo. Servo se tam vloží i přišroubuje z vnitřní strany. Tato strana by měla být hladká a voděo odolná.

- [x] Pro minimalizaci možnosti vniknutí vody do serva by servo mělo být natočeno směrem dolů.

- [x] Na spodním dílu směrovky je díra pro osu směrovky vyvedena až ven. Je potřeba udělat její zaslepení. Zrychlí to montáž směrovky.a zjednoduší výrobní postup.

- [x] Páka má stejný přesah i rozteč montážních děr jako její menší verze na staré směrovce. Takže tuto pozici táhla je nejlepší vzít odsud. Podle měření je tento přesat 5.5 mm od první montážní díry. 

![20191013_112133_HDR](https://user-images.githubusercontent.com/5196729/66713579-b6e30580-edac-11e9-98c4-8b409ff5ce52.jpg)

- [x] Na jednom středním dílu směrovky chybí otvory pro připevnění držáku na tyč. 

- [x]  Odstranit tuto díru na obrázku pod servem. Zřejmě nějaký pozůstatek po tunelu..

**Comment by kaklik** [comment]
![obrazek](https://user-images.githubusercontent.com/1194177/67306692-b0b0ff80-f4f7-11e9-96d5-9f6f90a6be77.png)

![obrazek](https://user-images.githubusercontent.com/1194177/67309811-cd9c0180-f4fc-11e9-9e56-f4fa216648bb.png)


- [x] šrouby adaptéru nesedí proti dírám ve směrovce
- [x] servo je ve výklenku ze stran a zespodu hodně na těsno a je ho tam potřeba násilně vtlačit
- [x] podložky šroubů serva se nevejdou do mezer ze stran serva (na fotografii), chybí asi 1mm místa. 
- [x] adaptér nepřechází plynule na plochu směrovky ale vzniká tam zub
- [x] hloubka zapuštění serva neuvažuje délku páky na servu a na směrovce
- [x] pohyblivá část směrovky obsahuje příliš tenkou stěnu
- [x] na pohyblivé části směrovky je potřeba základnu páky zarovnat, částečným zapuštěním do směrovky

**Comment by roman-dvorak** [comment]
V servu je potřeba udělat úpravu, aby bylo možné osu směrovky snadno vytáhnout. Toto lze vyřešit odstraněním (snížením) kostky v okolí osy

**Comment by roman-dvorak** [comment]
@taury55 snažím se dostat směrovku do celkové sestavy vírníku. Jak nebyly dobře pochopeny připravené parametry, tak nefungoval původní výpočet vzdálenosti tyčí, na kterých je směrovka přidělaná. 

Teď jsem se snažil tento výpočet předělat tak, aby to sedělo na novou směrovku. Aby mi to sedělo, tak  k výpočtu musím přičítat nějakou divnou konstantu, aby to sedělo správně. Vidět je to např zde:

https://github.com/ThunderFly-aerospace/TF-G1/blob/improved_suspension/parameters.scad#L367

Nešlo by to nějak vyřešit?

**Comment by taury55** [comment]
@roman-dvorak Dostal jsem se k tomu až teď, ale ta proměnná tail_pipe_distance je tam naprosto přebytečná a v celém 666_1028.scad není použita.
