### ISSUE TITLE
Úchyt zadního kolečka na nápravnici

### ISSUE THREAD

**Issue by ChroustJan** [Elizaa62/Components#195]
Pro testy na střeše potřebujeme udělat nový úchytný díl pro zadní kolečka. Díl by mohl vypadat následovně:
![IMG_20190616_092918 (1)](https://user-images.githubusercontent.com/9783606/59560932-ead63600-9019-11e9-96b7-c8d0c5ad3ece.jpg)

Díl přijde přidělat na zadní nápravnici o průměru 25mm. Stažení na tuto trubku by mělo být provedeno pomocí čtveřice šroubů M3. Do dílu následně přijde trubka o průměru 10mm na jejím druhém konci bude kolečko.

Není nutné tvořit díl označený číslem 2. Je možné mít proti sobě dva dílce 3.

**Comment by alcamrkvicka** [comment]
888_2010
4 otvory jsou udelane na srouby M3x20, mezera mezi 2 castmi je 3 mm, je to tak ok?
![2010](https://user-images.githubusercontent.com/51204144/59977182-4aaa7f00-95ce-11e9-9547-63b40609f252.PNG)
![2010x](https://user-images.githubusercontent.com/51204144/59977183-4da56f80-95ce-11e9-910b-3d2af6b61530.PNG)

**Comment by roman-dvorak** [comment]
Tento díl mi příjde až moc zbytečně masivní. Navrhuji ho proto udělat tenčí
(a zároveň lehčí). Upevňovací šrouby dát max 1 cm od hlavní tyče. Na
straně, kam se vkládá tenčí trubka, tak udělat nějaký výčnělek nebo tento
díl udělat trochu oválný.

Myslím, že tento problém vychází z původního nákresu, který není nakreslen
úplně v měřítku.

![2019](https://user-images.githubusercontent.com/5196729/59979365-535b7f00-95e7-11e9-9f7e-caacce34c2e7.jpg)

(tento nákres také není 100 % v měřítku ale lépe popisuje poměr hlavní tyče
a sílu tištěných dílů.

tyto dvě části můžou být namodelovány v jednom souboru jako 2 moduly.

**Comment by alcamrkvicka** [comment]
Ztenceno a upraveno do protahlejsiho tvaru...
![image](https://user-images.githubusercontent.com/51204144/59981180-3c755680-9600-11e9-819e-f2da1b405298.png)

**Comment by ChroustJan** [comment]
Já to kreslil hodně zjednodušeně, aby to bylo jednoduché. Tento díl se mi samozřejmě líbí víc.

**Comment by kaklik** [comment]
V modelu jsou [špatně užity parametry průměrů trubek](https://github.com/ThunderFly-aerospace/TF-G1/blob/81cb60f85d13ef3aa27e16925e3a3aaa7429a690/src/888_2010.scad#L6-L7). @ChroustJan  sice v zadání napsal průměry 10 a 25mm. To ovšem pro model není pravda a je potřeba použít [tyto parametry ](https://github.com/ThunderFly-aerospace/TF-G1/blob/81cb60f85d13ef3aa27e16925e3a3aaa7429a690/Parameters.scad#L3-L8)

Taktéž i parametr wheel_holder_thickness což je předpokládám šířka držáku by mohl být odvozený z průměru trubky např 1.5x průměr trubky. 

distance_between_parts je zas předpokládám mezera mezi díly pro sešroubování. Tato mezera je závislá na přesnosti tisku. Takže by měla být třeba 4x global_clearance.

**Comment by roman-dvorak** [comment]
Při přimontování dílu byl zjištěn problém s tolerancemi ve velikosti parametru na 10 mm trubku. Trubka byla v tomto dílu volná. Je to stejný problém jako #203 

Díl se zdá pro tento účel použitelný.

**Comment by ChroustJan** [comment]
Je potřeba posunout šroub držící trubku o síle 10mm do středu dílu. Viz obrázek. Takto dochází k vrtání do trubky na jejím okraji.
![IMG_20190630_162813](https://user-images.githubusercontent.com/9783606/60491973-43f4c980-9caa-11e9-8c21-b4875a341ae7.jpg)

**Comment by alcamrkvicka** [comment]
Dira je presunuta doprostred.

**Comment by kaklik** [comment]
@ChroustJan  issue se uzavírá až když se otestuje jeho vyřešení. Do té doby je Resolved.

**Comment by kaklik** [comment]
Nový úchyt funguje.
