### ISSUE TITLE
Kryt vertikální trubky

### ISSUE THREAD

**Issue by Elizaa62** [Elizaa62/Components#196]
- kryt musí plynule a vodotěsně přecházet na rotorovou hlavu

![image](https://user-images.githubusercontent.com/31339298/59792582-c659b280-92d4-11e9-896c-1dd3f327b3e7.png)

**Comment by kaklik** [comment]
Co ten kryt ukončil tím zaobleným tvarem kapky, stejně jako třeba končí rotorový list?

Do tohoto tvaru by se teprve vyřízl otvor pro rotorovou hlavu. 

![obrazek](https://user-images.githubusercontent.com/1194177/59935061-39863480-944d-11e9-9c6a-dd4adda69db9.png)

**Comment by Elizaa62** [comment]
Zkusila jsem vložit tu kapku nahoru 
![image](https://user-images.githubusercontent.com/31339298/60290988-3346fb00-991a-11e9-8cee-240d7182cac5.png)

akorát je problém v tom, že se to nevejde do tisknutelného rozměru...

**Comment by kaklik** [comment]
Paráda! :) Tak to asi zbývá jen rozdělit na více dílů. Horní, prostřední a spodní díl. 

Jinak tenhle kryt v budoucnu pravděpodobně čeká úprava, že spodní část bude širší, než horní.  Teď to ale zatím není potřeba.

**Comment by kaklik** [comment]
Toto řešení je pro současnou verzi ve větvi master dostatečné.
