### ISSUE TITLE
Doplnit sestavu kolečka o vidlici 888_2103

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#199]
Sestavu kolečka by bylo potřeba doplnit o vidlici 888_1027. Rozměry vidlice je potřeba nastavit tak, aby ke kolečku pasovala. Parametry vidlice by proto měly vycházet z rozměrů kolečka v souboru parameters.scad
 
![obrazek](https://user-images.githubusercontent.com/1194177/60087329-16090580-973d-11e9-800f-5422d816508d.png)

**Comment by alcamrkvicka** [comment]
![image](https://user-images.githubusercontent.com/51204144/60090584-1dcba880-9743-11e9-9db7-90b85ca56651.png)
 jak velka mezera ma mezi vidlici a koleckem byt?

**Comment by kaklik** [comment]
Jestli myslíš z boku kolečka, tak žádná. Tam stačí na tloušťku té obruby vložek. 
Také jsem si všiml, že ty vložky v sestavě nejsou možná úplně správně zapuštěny v kolečku po úpravách jejich délky. 

Mezera mezi běhounem kolečka a zaoblenou částí vidlice stačí malá třeba 10mm. Ale do tohoto směru může být vidlice klidně delší, aby ji bylo možné uchytit za delší část trubky. Horním limitem je pak určitě tiskový rozměr 150mm.

**Comment by kaklik** [comment]
Dalším požadavkem na vidlici je, aby využívala šrouby o nějaké existující délce. Pokud je to možné, tak například M4x50 nebo 55mm.

**Comment by roman-dvorak** [comment]
Je potřeba upravit sestavu kolečka tak, aby poloha jednotlivých dílů byla nastavena pomocí odpovídajících parametrů a zkontrolovat jejich správnost. 

Do vidlice je potřeba použít šroub M4x55. Teď to vychází na délku šroubu M4x60 (který se moc nevyrábí). To lze vyřešit tak, že se z vložky ložiska odstraní vnější lem (viz: https://github.com/ThunderFly-aerospace/TF-G1/issues/191#issuecomment-508866092 ) a o dvojnásobek jeho tloušťky se zúží vidlice. Pak je potřeba ohlídat správné zapuštění matic (a hlavy šroubu) do vidlice na délku šroubu M4x55.

**Comment by roman-dvorak** [comment]
Druhá část vidlice - třmen pro šroub není namodelován s použitím stejných parametrů.

**Comment by roman-dvorak** [comment]
Zaktualizovány rozměry vidlice, upraveny připevňovací body, více zapuštěny matice pro prošroubování tyče, Délka šroubu napočínána pro M4x55 DIN 912.
