### ISSUE TITLE
Převis na přední části dílu 666_1025

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#20]
Přední část, má dělení u výřezu pro motor příliš vzadu. V důsledku toho vzniká převis, který znemožňuje tisk. 

Taktéž boční stěny ve výřezu pro motor musí být prodlouženy až na spodní úroveň dílu, aby jejich tisk začínal od podložky. 
Je možné, že díky této úpravě bude nutné upravit i díl 666_1027

**Comment by Elizaa62** [comment]
Boční stěny ve výřezu pro motor jsem prodloužila na spodní úroveň dílu, Ale překrývá se to s tím lemem. Je to tedy ve stejné úrovni, ale to by snad nemělo vadit. U toho dílu 666_1027 udělám výřez až na úroveň zářezu.

**Comment by Elizaa62** [comment]
Tak jsem upravila i ten převis. Zvolila jsem špatnou hodnotu posunutí.

**Comment by kaklik** [comment]
Potvrzuji, že převis je odstraněný a díl teď půjde vytisknout.. :) 
Bylo by ještě dobré, aby stěny byly přidány ne v poddružném modelu ale v hlavním modelu kapkového krytu, aby steny byly vidět i v sestavě.  Podobně jako je teď vyřešen držák krytu vertikální trubky.

**Comment by Elizaa62** [comment]
Stěny přesunuty do hlavního kapkovitého modelu.
