### ISSUE TITLE
Upravit parametry pro 608 ložisko

### ISSUE THREAD

**Issue by roman-dvorak** [Elizaa62/Components#203]
Vnitřní průměr pro ložisko 608 je moc malý. Parametr vnitřního rozměru bych zvětšil cca o 0.5 mm

**Comment by roman-dvorak** [comment]
Díl 1030 (střed tištěného kolečka #191) má vnější průměr části do ložiska 7.4 mm - 7.5 mm. 
Parametr definující tuto velikost je nastaven:  `608_bearing_inner_diameter = 8-0.3;`

Proto by bylo vhodné tento parametr zvětšit max o 0.5 mm a otestovat např na tomto dílu.

**Comment by kaklik** [comment]
Nové parametry pasují.
