### ISSUE TITLE
Zadní podvozek - výběr vhodného tlumiče

### ISSUE THREAD

**Issue by roman-dvorak** [Elizaa62/Components#205]
Jako vhodný tlumící člen podvozku #188 se jeví použití pneumatického pístu, který bude mít spojené obě části pomocí jednosměrného ventilu.

K vybranému pístu je následně nutné upravit připevňovací díl do Igubal ložisek. Stejně, jako je tomu u šestiosé platformy.

**Comment by roman-dvorak** [comment]
Zajímavé řešení by bylo použití tlumiče s MRF (Magneto-Rheological Fluid) nebo ERF (Electro-Rheological Fluid) náplní. Výhoda tohoto řešení je, že lze elektronicky ovládat velikost tlumení.

Zatím jsem nalezl jediného výrobce MRF kapaliny [Mid Atlantic Rubber (Lord MRF)](http://www.lordmrstore.com/lord-mr-products/mrf-132dg-magneto-rheological-fluid-250ml). Také nabízí rovnou tlumiče s touto kapalinou a integrovaným magnetem [RD-8041-1](http://www.lordmrstore.com/lord-mr-products/rd-8041-1-mr-damper-long-stroke). Díky tomu, že je magnet umístěný uvnitř pístu, tak by nemuselo docházet k velkému úniku magnetického pole mimo obal. Tím následné rušení magnetometru. 

Jako první krok bude zřejmě vhodné navrhnout podvozek s použitím pneumatických pístů jako tlumiče. A zjistit, jestli složité elektronické řízení tlumení je potřeba.

**Comment by kaklik** [comment]
Zatím se zdá, že pneumatické tlumení je dostatečné.
