### ISSUE TITLE
Zadní podvozek - připevnění tlumiče k příčné podvozkové tyči

### ISSUE THREAD

**Issue by roman-dvorak** [Elizaa62/Components#206]
Na příčnou tyč je potřeba kyvně přichytit pneumatický píst. K tomu je vhodné znovu použít kulová ložiska Igus. Naklonění ložiska bude vypočítáno z celkových parametrů podvozku.

![20190701_193005](https://user-images.githubusercontent.com/5196729/60455850-e6c03000-9c37-11e9-91a5-245d3e0c446b.jpg)

![20190701_193219](https://user-images.githubusercontent.com/5196729/60455855-e9bb2080-9c37-11e9-968f-61717743a65e.jpg)

Lze vycházet z dílu #195

**Comment by roman-dvorak** [comment]
Vybrat vhodnou délku šroubu pro připevnění kulového ložiska k dílu a do dílu zapustit matku místo hlavičky. Nebude tam pak ani muset být servisní otvor pro imbus klíč. 

Díl je zbytečně robusný, je potřeba sjednotit délku šroubu pro stažení tyče.

**Comment by roman-dvorak** [comment]
Díl bude předělán na boční uchycení na trubku.

**Comment by roman-dvorak** [comment]
Vyřešeno tímto dílem: https://github.com/ThunderFly-aerospace/TF-G1/blob/improved_suspension/STL/print_plate_888_2016.stl

![Snímek z 2019-07-23 01-02-27](https://user-images.githubusercontent.com/5196729/61671345-77de7000-ace7-11e9-9f6f-3f614c3aad7a.png)

**Comment by kaklik** [comment]
K dílu pouze chybí vrtací přípravek, jinak je díl použitelný.

**Comment by roman-dvorak** [comment]
Vrtací přípravek již nějakou dobu existuje v této sestavě: https://github.com/ThunderFly-aerospace/TF-G1/blob/improved_suspension/STL/print_plate_888_2016.stl

Sestavu jsem ještě přerenderoval
