### ISSUE TITLE
Nový podvozek - připevňení ramen a tlumiče podvozku ke kolečku

### ISSUE THREAD

**Issue by roman-dvorak** [Elizaa62/Components#207]
Mezi vidlicí a tyčemi bude mezikus, který bude sloužit ke spojení obou tyčí od podvozku a tlumiče. Dvě tyče budou k tomuto dílu připevňeni na pevno tak, aby nedocházelo k jeho naklánění a nějakým deformacem. Pravděpodobně by tyče měly být přidělány prošroubováním šroubu skrze ně k této destičce. Je potřeba, aby držáky tyčí měly správný úhel. 

Dále k tomuto dílu bude přidělán kulový čep z řady Igubal, za který bude přidělán pneumatický tlumič. Domek tohoto ložiska bude muset být přidělán také trochu šikmo. 

Tvar celé "destičky" je zatím volný. Nemusí vůbec odpovídat nákresu. Je to vhodné dělat podle potřeb vidlice s integrovaným motorem/brzdou. To samé platí o připevňovacích dílech. 

Rozdělení těcho dvou dílů je z důvodu snazšího tisku a následného vylepšování vidlice. 

![20190701_225257](https://user-images.githubusercontent.com/5196729/60467093-dd45c080-9c55-11e9-9b31-34be34beed84.jpg)

![20190701_225334](https://user-images.githubusercontent.com/5196729/60467129-f9e1f880-9c55-11e9-8067-7699fd96a1d8.jpg)

**Comment by roman-dvorak** [comment]
Kulové ložisko KBRM má větší vnější průměr (než EFSM) a nevejde se tedy do připravené díry. Dále by bylo vhodné tento díl udělat kompaktnější tím, že nebude obsahovat jednotlivé trubyčky ale bude to obalené obálkou.

**Comment by roman-dvorak** [comment]
Nalzené problémy opraveny. 

![Snímek z 2019-07-22 00-24-17](https://user-images.githubusercontent.com/5196729/61597945-1949c100-ac17-11e9-94ab-c81291ffc719.png)

**Comment by kaklik** [comment]
Tento díl myslím funguje. :)
