### ISSUE TITLE
Vidlice zadních kol

### ISSUE THREAD

**Issue by roman-dvorak** [Elizaa62/Components#208]
Protože zadní podvozek bude sloužit k zatáčení vírníku, je potřeba do podvozkové vidlice integrovat motor, který bude vždy jedno kolečko přibržďovat.

Mělo by to být řešeno tak, že se plášť kolečka bude dotýkat s rotačním obalem motoru. 

Vidlice bude následně připevněna na díl #207

**Comment by roman-dvorak** [comment]
Vidlice musí mít obráceně umístěný šroub tvořící osu kola. Když se vidlice přišroubuje k dílu #207 tak nelze osu kolečka vytočit/připevnit. Matka může být umístěna směrem k #207. Tím dojde k tomu, že matka nevypadne.

**Comment by kaklik** [comment]
Zde by zřejmě bylo ještě vhodné: 

- [x] posunout náboj kola mezi dva montážní šrouby dílu #207 - Tím dojde ke zmenšení namáhání dílů, neboť síly budou při roztahování podvozku působit blíže osy kola. Navíc nebude vypadávat matice šroubu tvořícího osu kola.
- [ ] Doplnit kryt na enkodér, kabely a přečnívající osu motoru.

**Comment by roman-dvorak** [comment]
- [ ]  Přes enkodér namodelovat nacvakávací kryt, který ho bude chránit před prachem atd..
- [ ]  Využít všechny 4 díry motoru
- [x]  Zkrátit vidlici - je zbytečně vysoká
- [ ]  Napočítat délku šroubu do páky s motorem

**Comment by roman-dvorak** [comment]
Motor nad vidlicí může být ke kolečku dotahován pomocí zkrutné pružiny, která bude obmotána kolem osy páky pro motor. Pružina bude schovaná mezi dílem vidlice a držákem motoru.

Dojde tím zároveň k hmotnostní optimalizaci držáku

**Comment by roman-dvorak** [comment]
Jako vhodná síla pro přítlak motoru ke kolu mi připadá něco mezi 15 - 20 N. Páka je na 5cm. To znamená 0.75 - 1 Nm. 

Chod pružity k vytvoření této síly by měl být cca 20-30 stupňů.


Měření této síly bylo provedeno tak, že jsem kolečko vírníku postavil na váhu a rukou jsem přitlačoval motor oproti kolečku směrem dolů. Tato síla se pak změřila na váze.

**Comment by roman-dvorak** [comment]
Otvory pro páku s motorem byly prozatím odebrány. Vidlice byla snížena a mírně upravena poloha šroubů pro přípevnění k podvozku
