### ISSUE TITLE
Úpravy podložky 1027

### ISSUE THREAD

**Issue by roman-dvorak** [Elizaa62/Components#209]
Pro nový podvozek #188 #189 a novou směrovku #194 a nový způsob přichycený rotorové hlavy je potřeba provést několik úprav podložky. 

- [x] Implementovat připevňení podvozkových ramen skrze KSTM ložiska
- [x] Zadní příčnou tyč přidělat přímo do podložky
- [x] Odebrat střední hliníkovou tyč
- [x] Jako kostru podložky použít 2 10 mm tyče
- [x] Vytvořit otvory pro připevňení směrovek a jejich prokabelování
- [x] Vytvořit připevňovací otvory pro přední kolečko, kotvu magetu, payload a další (lehké příslušenství.
- [x] Nové připevnění rotorové hlavy na 4 sloupcích

**Comment by kaklik** [comment]
Podle mě se tohle musí rozdělit na jednotlivé issue vycházející z #223

**Comment by roman-dvorak** [comment]
Toto issue vyřešeno pomocí #223
