### ISSUE TITLE
Zvětšení výřezu pro motorové lože na dílu podložky 666_1027

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#21]
Díky řešení  převisu  #20 bude potřeba rozšířit výřez na podložce. Světlá šířka výřezu by měla být tak 60mm neboť plech motorového lože je na díl 666_1026 uchycen šrouby s šestihrannou hlavou.  A na druhé straně šroubů jsou samojistné matice, které musí být dostupné pro seřízení klíčem při sejmutí předního krytu.

**Comment by Elizaa62** [comment]
Hotovka.. šířka zanesena parametricky jako width_of_front_part.
