### ISSUE TITLE
Připravit rozdvojku pro GPS a safety switch na CUAV V5+ autopilota

### ISSUE THREAD

**Issue by roman-dvorak** [Elizaa62/Components#212]
CUAV V5+ autopilot má sloučený konektor pro GPS, safety tlačítko, Safety LEDku a pípák. Z konstrukčních důvodů by bylo vhodné vyvést další safety tlačítko mimo GPS.

Nejsnazší způsob je na dodaný propojovací kabel paraelně připájet drátky s tlačítkem. Pípák může zůstat ten, co je v GPS. 

Je možné využít dodané safety switch, které má dokonce montážní otvory a LED v tlačítku.
![20190704_221650_HDR](https://user-images.githubusercontent.com/5196729/60686526-9ea84400-9ea9-11e9-881c-ed4d9f943895.jpg)

Rozteč montážních otvorů je 19 mm, střed děr od okraje PCB je 5 mm a díry jsou pro M3 šruby. 

Pinout konektoru na autopilotu je následující:
![Snímek z 2019-07-04 22-12-35](https://user-images.githubusercontent.com/5196729/60686427-e24e7e00-9ea8-11e9-85e0-03ded82ea135.png)

**Comment by kaklik** [comment]
Vyřešeno vyrobením nového kabelu ke GPS s piny oddělenými pro safety switch.
