### ISSUE TITLE
Nový podvozek - připevnění příčné trubky k podložce

### ISSUE THREAD

**Issue by roman-dvorak** [Elizaa62/Components#213]
Příčná podvozková trubka by měla být přidělána k podložce pomocí dvojice třmenů, které budou prošroubované do podložky. Tyto třmeny by měly být co nejblíže podélným výztuhám v podložce.

**Comment by roman-dvorak** [comment]
Upravit díl tak, aby ho bylo možné tisknout bez podpor. To nejspíše znamená rozdělit ho na 2 časti.

**Comment by kaklik** [comment]
Myslím, že je to vyřešeno.
