### ISSUE TITLE
Uprava parametru pro tenkou 10 mm trubku

### ISSUE THREAD

**Issue by roman-dvorak** [Elizaa62/Components#215]
Vytisteny parametr pro tenkou (10 mm) trubku ma realny prumer 10.3 mm

**Comment by kaklik** [comment]
Ono tu ještě závisí na tom, jestli otvor pro trubku se tiskne po vrstvách, nebo kolmo na vrstvy. Protože tisk kolmo na vrstvy je přesnější.

**Comment by roman-dvorak** [comment]
S upraveným parametrem bylo vytištěno několik modelů v různých orientacích - kolmo na vrstvy, po vrstvách a  šikmo. Do všech dílů bylo možné tyč zasunout.
