### ISSUE TITLE
Připravit mixer a potřebnou konfiguraci do nového autopilota pro test na střeše

### ISSUE THREAD

**Issue by roman-dvorak** [Elizaa62/Components#218]

**Comment by roman-dvorak** [comment]
na SVN ve složce `svnThunderFly/projekty/UAV/autogyro/TF-G1/SDcard` je složka, která by měla jít nahrát na SD kartu vírníku s novým autopilotem. Následně by to mělo odpovídat [tomuto zapojení](https://github.com/ThunderFly-aerospace/TF-G1/wiki/RC-channels-and-outputs).

Možná bude potřeba provést kalibraci vysílačky v autopilotu s novým nastavením vysílačky `TF-G1 auto` profilem.

**Comment by kaklik** [comment]
Vyřešeno.
