### ISSUE TITLE
Zámky pro přesnější lepení dílů. 

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#22]
Při lepení kapoty 666_1025 jsem zjistil, že je těžké na sebe navázat jednotlivé stěny částí. Pomohl by proto nějaký tvarový přechod, který by umožnil, aby do sebe oba díly před lepením zapadly.

**Comment by Elizaa62** [comment]
Stále tento problém trvá?

**Comment by Elizaa62** [comment]
Přemýšlím jak to udělat.. napadlo mě, že by se ten lem dal nahoře vykrojit a udělaly by se tam takové ploché drážky, do kterých by se nasunula a nalepila rovná podložka a ta by se pak nasunula a nalepila do stejných drážek, které by byly umístěny v protější části dílu, který by se přilepoval. Rozumíš mi trochu? :(

**Comment by kaklik** [comment]
V protější části dílu by zřejmě byly spíš zuby, ne?  Myslím, že něco podobného, je tady popsané jako "spoj zubový" a nebo "pero - drážka". 

![](http://www.lepidla.cz/userfiles/clanky-pred-lepenim/konstrukce-lepenych-spoju.jpg)

Když jsem to teď našel, tak se mi docela líbí ty "hrdlové spoje".  Možná by bylo jednodušší je vymodelovat, než ty zuby. :)

**Comment by Elizaa62** [comment]
Když mě pořád trápí problém, že ty díly jsou dělené na maximální tisknutelný rozměr, takže nevím, když se tam udělá nějaký zobáček v délce navíc, tak jestli to půjde vytisknout..

**Comment by kaklik** [comment]
Je výhodné, aby vnější povrch byl hladký. Takže vžechny tvarové zobáčky podobně  by bylo stejně potřeba zapustit pod povch. V Případě toho "hrdlového spoje" by to vypadalo tak, že to vnitřní hrdlo se v místě spoje zúží.

**Comment by Elizaa62** [comment]
Já asi moc, teda spíš určitě, nerozumím tomu, jak se to myslí.. Nedokážu si to vůbec představit :(

**Comment by Elizaa62** [comment]
Kdyz tam udelam napr. Ten zubovy spoj, tak se mi celkova delka te casti zmensi. Musela bych ty zuby udelat po celem obvodu, aby to melo trn spravny efekt a nedoslo ke zvlneni. Protoze kdyz bych udelala jeden zub, tak ty vedlejsi plochy nebudou pasovat do sebe.

**Comment by Elizaa62** [comment]
Co kdybch uplne zrusila ty lemy a misto tech lemu by se natiskli takove podlozky pomoci kterych by se ty dve casti jakoby podlepili?

**Comment by Elizaa62** [comment]
Vytvořený pokus o zámek. Více v commitu u dílu 666_1025.

**Comment by kaklik** [comment]
Ano, konstrukce zámku v principu dobrá, klidně by mohl být delší.  Teď je to akorát potřeba udělat skoro všude..

**Comment by Elizaa62** [comment]
Zámky u horního dílu krytu vytvořeny. Akorát mám problém u části B. Tys tam totiž ten lem nechal vlevo. Ale já mám u dílu A lem vpravo, takže u části B jsem lem vlevo smazala a nahradila třemi zámky. Dále u části C je lem též vlevo, tak jsem vytvořila u části B zámky i vpravo. Ale mám otázku, zda to půjde vytisknout, nebo ty lemy mám předělat tak, aby to pak šlo vytisknout?

**Comment by kaklik** [comment]
Obávám se, že zámky na straně, kde by měly začínat na podložce bez lemu, který drží model na podložce nepůjde tisknout. 
Model při tisku musí  vždycky začínat lemem, aby něčím držel na podložce během tisku. 
Takže by asi bylo lepší to nějak překonstruovat.  Původně jsem tam ty lemy zvolil tak, aby se model během tisku zužoval směrem vzhůru, což mi připadalo přirozenější. Myslím ale, že se může i rozšiřovat a kvalitu tisku to neovlivní.

**Comment by kaklik** [comment]
Právě jsem vymyslel, jak potíž s tiskem zámků u prostředního dílu s držákem na kryt pylonu vyřešit.  Stačí tuhle část rozdělit ještě na dva další díly, které se nebudou slepovat ale jenom k sobě budou sesazeny.  Na to stačí, když každá část bude mít svůj vlastní lem, který ji zpevní. 

Rozdělení navíc umožní aby kryt šel sundat bez toho, aby se přetahovat shora přes pylon.

**Comment by Elizaa62** [comment]
Díl B jsem rozdělila na díl B a díl BB. Oba díly mají svou díru na šroub pro připevnění k podložce, svůj lem a své zámky.

**Comment by kaklik** [comment]
Paráda :)  Myslím, že spojování dílů je tím vyřešené.
