### ISSUE TITLE
Úprava podložky - přidání podélných výztuh podložky

### ISSUE THREAD

**Issue by roman-dvorak** [Elizaa62/Components#220]
Toto issue je jeden z podúkolů #209. 

Nový vírník bude mít upravenou směrovku (#194) ve tvaru písmene 'A' a bude přidělaná na dvou 10 mm trubkách. Dále bude odebrána střední tyč, která nyní tvoří kostru vírníku. To by mělo být nahrazeno trojicí dalších 10 mm trubek, které budou podélně prostrčené skrze podložku.

### Výztuhy
Výztuhy budou skrz trup (podložku) vírníku 3. Jedna uprostřed a dvě stejně vzdálené od středu po stranách. Tyto tyče budou procházet skrze celou podložku. 

### Připevnění ocasních ploch
Bude provedeno dvojicí 10 mm trubek, které budou končit někde v zadní polovině těla vírníku. Skrze tyto tyče povedou vodiče od serv (popř. něco jiného pokud bude potřeba) takže je potřeba u podložky zajistit, aby na konec trubky navazoval nějaký kanálek pro dráty. Představoval bych si to asi takto.
![20190722_151213~2](https://user-images.githubusercontent.com/5196729/61637871-99fcd180-ac98-11e9-9b99-4c1e222e6077.jpg)

Je potřeba aby vzdálenost těchto dvojic tyčí bylo možné upravit parametrem. Pak se to bude muset nastavit tak, aby to vycházelo mezi všechny díry v podložce (pro podvozek či další příslušenství)

**Comment by kaklik** [comment]
Tuto záležitost by měla vyřešit konstrukční změna #223
