### ISSUE TITLE
Nová konstrukce nosné podložky

### ISSUE THREAD

**Issue by ChroustJan** [Elizaa62/Components#223]
Při zvětšování nosné podložky dochází k problému nutnosti dělení dílce na tisknutelné části. Tento proces není příliš jednoduchý. Stávající podložka se také tiskla kolem 80h. Při vývoji a testech je potřeba co nejsnáze měnit rozložení vnitřní výbavy vírníku. Přibývá nová elektronika, nebo je potřeba posunout například baterie kvůli těžišti. 

Nová konstrukce má pouze dva hlavní dílce:
- tuhý středový trup skrz který vede dvojice uhlíkových trubek (v nákresech 1)
- okrajový dílec skrz který vede jedna uhlíková trubka, dílec také obsahuje drážku pro uchycení krytu vírníku jako tomu bylo u současného řešení ( v nákresech 2)

Nákres ze shora:
![IMG_20190804_082427](https://user-images.githubusercontent.com/9783606/62420582-ee3e8300-b694-11e9-9809-3adb21be8107.jpg)

Konstrukce umožňuje zachovat stávající díl předního motoru. Pouze bude potřebovat upravit uchycení na dvojici trubek. Plánovaný ocas se také nemění. Pouze bude vytvořen dílec pro uchycení dvojice trubek z ocasu na dvojici trubek rámu vírníku. Konstrukce zakrytování vírníku bude také zachována. Pouze bude jiné rozložení otvorů pro úchytné šrouby.

![IMG_20190804_082559](https://user-images.githubusercontent.com/9783606/62420586-f5fe2780-b694-11e9-9490-ae87668b8da3.jpg)

Náčrtek dílce hlavního nosného trupu. V rámci iterací bylo rozhodnuto, že se ocas nebude chytat na nosné trubky, ale na pomocné boční. Viz. první obrázek pohledu na vírník z vrchu. 

![IMG_20190804_082313](https://user-images.githubusercontent.com/9783606/62420588-fe566280-b694-11e9-8038-11aa458fcc0a.jpg)

Podrobnější rozkreslení dílce 1 a 2:

![IMG_20190804_082305](https://user-images.githubusercontent.com/9783606/62420590-02828000-b695-11e9-9a5c-886683d8ba26.jpg)

Dílec 1:

- jeho délka by měla být parametricky rostoucí. Maximální délka je omezená velikostí tiskárny.

- skrz celý díl procházejí dvě trubky (aktuálně o průměru 10mm) v jejich ose je vždy otvor pro šrouby M3, aby bylo možné trubku prošroubovat s tištěným dílem. Z obou stran otvoru musí být počítáno s tvarem pro umístění matice.

- po cca 50 mm možnost vložení dvojice trubek (aktuálně průměr 10mm) kolmých na hlavní nosné. Možnost jejich prošroubování šroubem M3, matice zas zapustit z obou stran dílce.

- v ose šroubů pro prošroubování hlavních trubek dát ještě kapsy pro matici M4, aby bylo možné z boku dílce uchytávat příslušenství. Uprostřed otvor pro šroub M4 se zapuštěnou maticí na obou stranách.

Dílec 2:

-obsahuje po své délce drážku pro kryt vírníku s kapsami pro M3 matici.

- po své délce má otvor na trubku (aktuálně 10mm průměr), zas by mělo být myšleno na možnost prošroubování s tištěným dílcem.

- otvory z boku pro pomocné trubky (aktuální průměr 10mm) s možností jejich prošroubování. 

Ukázka možností uchycení příslušenství v konstrukci:

![IMG_20190804_082254](https://user-images.githubusercontent.com/9783606/62420591-08786100-b695-11e9-805b-9dd032a9cd00.jpg)

Varianta 1:

- dvojitý dílec mezi dílem 1 a 2. Při povolení jeho šroubů je možné popojíždět dopředu dozadu, dle potřeby. Do tohoto dílce mohou být umístěny různé úchyty dle potřeby. Tento díl je uvažován například pro uchycení baterií.

Varianta 2:

- uchycení na hlavní trub z boku na matici M4, která je v kapse trupu. Možné využit například pro uchycení rotoru. Pokud se díl udělá dostatečně široký, je možné následné vyztužení trubkou kolmou vůči trupu. Dílec se na danou trubku pouze nasune. Nebude potřeba vrtání a lepení.

Varianta 3:

- pomocí šroubu M4 skrz trup. Trup má standardně tento otvor se zapuštěnou maticí s obou stran. Je možné umisťovat držák jak zespodu tak ze shora. 

Náčrtek možného uchycení zadní nápravy:
![IMG_20190804_083349](https://user-images.githubusercontent.com/9783606/62420593-0e6e4200-b695-11e9-8362-79bb15246c11.jpg)

Toto uchycení by mělo umožňovat snadnou demontáže celé zadní nápravy pro servis. Může jí držet třeba 4-8 šroubů. Základní uchycení je na hlavní trub s možností využití využití vedlejších trubek.

**Comment by roman-dvorak** [comment]
- [x] Sjednotit rozměry děr (a příslušných matek) skrze nosník
- [x] Do sestavy přidat značky pro jednoduché určení dílů
- [x] Odebrat podpory pro tisk univerzální drážky.

**Comment by roman-dvorak** [comment]
Nosník se zdá použitelný. Další problémy budou mít vlastní issue.
