### ISSUE TITLE
Implementace podélného dělení horního krytu

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#224]
Horní kryt je potřeba rozdělit i podélně na menší tiskové díly, aby bylo možné vytisknout trup širší, než je tiskový rozměr 3D tiskárny.

**Comment by kaklik** [comment]
Dělení krytu funguje přesně tak jak má a lze vybrat jen část krytu. Například: 

![image](https://user-images.githubusercontent.com/1194177/62546199-580c8780-b863-11e9-90e9-33adf1075cc8.png)

Přestaly ovšem díky tomu fungovat existující tiskové soubory [print_plate_1025X.scad](https://github.com/ThunderFly-aerospace/TF-G1/tree/master/src/4printing). Ty je potřeba poupravit tak, aby bylo možné samostatně vytisknout každý díl krytu. 

Je potřeba při tom pamatovat na to, že maximální tiskový rozměr tiskárny takto dělený kryt nejlépe vyplní úhlopříčně.

**Comment by kaklik** [comment]
Zkusil jsem si změnit parametry, abych zjistil, jak se dělení chová.  Přišel jsem na to, že nová podélná výztuha, se při aktuální kombinaci parametrů nechová úplně správně a vyčuhuje mimo trup. 

![image](https://user-images.githubusercontent.com/1194177/62547282-47f5a780-b865-11e9-8381-4ebfbc378ab2.png)

**Comment by Elizaa62** [comment]
Nefungovalo to, protože jste změnili parametr délky kapky z "hull_drop_lenght" na "hull_x_size". Už by to mělo fungovat.

**Comment by kaklik** [comment]
Určitě je ten přečnívající konec tím? Já si teď stánhul repozitář a přijde mi, že se nic nezměnilo. 


![image](https://user-images.githubusercontent.com/1194177/62651736-f5e27e00-b959-11e9-8922-9f897db3d189.png)

**Comment by Elizaa62** [comment]
Jaké parametry tam měníš?

**Comment by Elizaa62** [comment]
Už by to mělo fungovat :)

**Comment by Elizaa62** [comment]
> Dělení krytu funguje přesně tak jak má a lze vybrat jen část krytu. Například:
> 
> ![image](https://user-images.githubusercontent.com/1194177/62546199-580c8780-b863-11e9-90e9-33adf1075cc8.png)
> 
> Přestaly ovšem díky tomu fungovat existující tiskové soubory [print_plate_1025X.scad](https://github.com/ThunderFly-aerospace/TF-G1/tree/master/src/4printing). Ty je potřeba poupravit tak, aby bylo možné samostatně vytisknout každý díl krytu.
> 
> Je potřeba při tom pamatovat na to, že maximální tiskový rozměr tiskárny takto dělený kryt nejlépe vyplní úhlopříčně.

-> ve které větvi mám toto udělat? Master nebo improved_suspension?

**Comment by kaklik** [comment]
> Jaké parametry tam měníš?

Tak hýbal jsem s hull_x_size a hull_drop_lenght protože jsem nevěděl jaký je mezi nimi rozdíl. 

Teď ale můžu potvrdit že to funguje. :) 

![image](https://user-images.githubusercontent.com/1194177/62654924-35609880-b961-11e9-8f51-d72fbb6914eb.png)


A z těch [dvou parametrů jsem udělal jeden](https://github.com/ThunderFly-aerospace/TF-G1/blob/0a92604a2d136537b65ac377492dbab5660f56b0/parameters.scad#L161), tak že jsem hull_x_size přiřadil hodnotu parametru hull_drop_lenght s tím, že parametr hull_drop_lenght bude potřeba v budoucnu zřejmě úplně zrušit.

**Comment by kaklik** [comment]
> > Dělení krytu funguje přesně tak jak má a lze vybrat jen část krytu. Například:
> > ![image](https://user-images.githubusercontent.com/1194177/62546199-580c8780-b863-11e9-90e9-33adf1075cc8.png)
> > Přestaly ovšem díky tomu fungovat existující tiskové soubory [print_plate_1025X.scad](https://github.com/ThunderFly-aerospace/TF-G1/tree/master/src/4printing). Ty je potřeba poupravit tak, aby bylo možné samostatně vytisknout každý díl krytu.
> > Je potřeba při tom pamatovat na to, že maximální tiskový rozměr tiskárny takto dělený kryt nejlépe vyplní úhlopříčně.
> 
> -> ve které větvi mám toto udělat? Master nebo improved_suspension?

Tohle oprav ve větvi improved_suspension.  V master stále funguje původní varianta krytů a tam ji není potřeba měnit.

**Comment by Elizaa62** [comment]
> > > Dělení krytu funguje přesně tak jak má a lze vybrat jen část krytu. Například:
> > > ![image](https://user-images.githubusercontent.com/1194177/62546199-580c8780-b863-11e9-90e9-33adf1075cc8.png)
> > > Přestaly ovšem díky tomu fungovat existující tiskové soubory [print_plate_1025X.scad](https://github.com/ThunderFly-aerospace/TF-G1/tree/master/src/4printing). Ty je potřeba poupravit tak, aby bylo možné samostatně vytisknout každý díl krytu.
> > > Je potřeba při tom pamatovat na to, že maximální tiskový rozměr tiskárny takto dělený kryt nejlépe vyplní úhlopříčně.
> > 
> > 
> > -> ve které větvi mám toto udělat? Master nebo improved_suspension?
> 
> Tohle oprav ve větvi improved_suspension. V master stále funguje původní varianta krytů a tam ji není potřeba měnit.

--> jak myslíš úhlopříčně? Stačí otočit o 45 stupňů nebo ten díl mám ještě rovnat přesně na střed tisknutelného rozměru?
