### ISSUE TITLE
Tisknutelný kloubový spoj rotorové hlavy

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#225]
Současná tisknutelná rotorová deska, viditelná na následujícím obrázku funguje relativně dobře.
Díl se nyní naklání volně obou osách (podélně-pitch i příčně-roll). Problém je dost vysoká volnost okolo vertikální - Yaw osy. 

![obrazek](https://user-images.githubusercontent.com/1194177/62699604-35ec4400-b9e0-11e9-87eb-5dd1420574b4.png)

Existují dva možné přístupy k tomuto problému. 

1. Nebo upravit tvarový kloub bránící protočení hlavy, tak aby neměl tak velkou vůli a nebo když to nebude možné tak 
2. Opustit hlavu v provedení spindle head, která má pro 3D tisk výhodnou skladbu a navíc umožňuje teoreticky let na zádech a nahradit tuto konstrukci klasickým uspořádáním [offset gimbal head](http://www.msgyro.com/photos/Bensen_Gimbal_Head_Hub_Bar_and_Head_Plates_504x379.jpg)

**Comment by slimonslimon** [comment]
mám v hlavě návrh kolem toho kulového kloubu udělat tisknutý kardanův kloub.

ten kulový kloub umístit na vyvýšenou plošinku, která by měla v jedné ose očka přesně ve výšce kloubu, pak druhý díl, který by to obepínal zvenku (mohl by mít shora plošku se zářezem pro tyčku, což by mu zvýšilo pevnost) a třetí díl (vlastní deska s prerotátorem) by měla dvě očka smerem dolů a obepínala by s offsetem ten prostřední díl - kromě oček by s tohoto dílu musel být vytištěn ještě krček kolem osyčky, který by zajišťoval stažení horního dílu proti kulovému kloubu

**Comment by slimonslimon** [comment]
přes kardanův kloub by neměli jít v podstatě žádné síly, krom kompenzace yaw

**Comment by slimonslimon** [comment]
![IMG_20190808_162117](https://user-images.githubusercontent.com/9033168/62711328-275e5680-b9f9-11e9-96b4-2f8c967e0bc2.jpg)

**Comment by kaklik** [comment]
Jo, tohle hybridní řešení se mi docela líbí (pokud to nelze vyřešit tvarováním toho kloubu) . Ale v případě, že to nevyjde moc masivní, tak v tom nevidím problém. 

Pokud to správně chápu, tak ty otočné části ani nemusí být spojeny osou ale stačila by jen břitová vazba,  Podobně jako to máme na [vyvažovacím přípravku](https://github.com/ThunderFly-aerospace/TF-G1/blob/master/STL/manufacturing_helpers/888_1009.stl).

**Comment by slimonslimon** [comment]
břitová vazba zní zajimavě, bylo by to jednodušší na složení a asi i kreslení, akorát nevím jak dobře drží proti rotaci (yaw).

**Comment by kaklik** [comment]
> břitová vazba zní zajimavě, bylo by to jednodušší na složení a asi i kreslení, akorát nevím jak dobře drží proti rotaci (yaw).

Tak bude to držet tak moc, dokud se ty břity neulomí. Ovšem vzhledem k tomu, že tady nejde úplně o nutnost malého odporu spoje, tak by břity ve skutečnosti mohly mít i poměrně nízký rozsah úhlů. Pak by pevnost vazby nebyla dána tolik pevností břitu, ale pevností kulového ložiska proti vytažení kuličky. (klín břitového spoje by při krutu v ose yaw působil silou roztahující celý kulový spoj.)
Zřejmě zde bude existovat nějaké optimum pevností. Neboť je výhodnější, aby se při havárii hlava protočila a nikoliv utrhl celý rotor.

**Comment by kaklik** [comment]
Kloubový spoj funguje a nyní je potřeba jej implementovat do nové verze rotorové hlavy.
