### ISSUE TITLE
Oprava vnějšího průměru vložky pro šroub M4 do 8mm igus ložisek

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#226]
Vytištěná vložka má průměr 7.3mm  potřebný průměr je 8.0mm 

![20190811_102308](https://user-images.githubusercontent.com/1194177/62831587-4ee43780-bc22-11e9-9304-dbd69ce127b8.jpg)

**Comment by roman-dvorak** [comment]
Pro tento účel jsem vytvořil parametr nový `M8_plug_diameter`. Velikost tohoto rozměru byla změněna z `8-0.5` na `8 mm`. Předpokládaný nový reálný rozměr je tedy `7.8 mm`, díly jsou vyrenderované s novým rozměrem.
