### ISSUE TITLE
Držáky kabeláže

### ISSUE THREAD

**Issue by ChroustJan** [Elizaa62/Components#229]
Navrhnout univerzální držáky kabeláže pro novou koncepci vírníku, aby šli dát do drážek v trupu.

**Comment by kaklik** [comment]
Ještě by to sem chtělo doplnit ty obrázky...

**Comment by ChroustJan** [comment]
Přibližný profil trupu:
![profil](https://user-images.githubusercontent.com/9783606/63092556-6d1f9f80-bf62-11e9-9803-06ef8ba86c18.png)

Náčrtky koncepce držáku:
![drzak](https://user-images.githubusercontent.com/9783606/63092580-7c9ee880-bf62-11e9-8416-821a0c2a2e35.png)

![drzak2](https://user-images.githubusercontent.com/9783606/63092585-7f014280-bf62-11e9-9cd8-d6038bd3b763.png)

**Comment by roman-dvorak** [comment]
Tohle bude prozatím vyřešené použitím "Flexibilního kabelového držáku", který byl koupený původně do auta. Uřízne se jeden nebo dva háčky a do spodní strany se vyvrtá díra pro M3 a přišroubuje se do univerzálních podélných drážek.  Popřípadě se může zkusit využít samolepka na tomto držáku.

![obrazek](https://user-images.githubusercontent.com/5196729/63750503-e5188e80-c8ad-11e9-9e39-18cc6162c409.png)
