### ISSUE TITLE
Zapuštění akumulátorů do dílu 666_1027

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#23]
Do podložky by bylo potřeba vytvořit zahloubení pro umístění dvou akumulátorů [tohoto typu](http://www.pkmodelar.cz/akumulatory-lipol-akumulatory-letecke-4-clanek-lipol/foxy-g2-li-pol-5000mah-14-8v-40-80c-74-0wh-3eb4038). 
Cílem je zajistit, aby oba akumulátory mohly být chyceny k podložce vytištěnou sponou přitaženou šroubem. A v případě potřeby je bylo možné snadno vyjmout z trupu sundáním části krytu a povolením spony.

**Comment by Elizaa62** [comment]
Zahloubení pro akumálátory je vytvořeno. Hloubka zahloubení je main_tube_outer_diameter/2. Poté až vytvořím účkovou spojku ve tvaru kvádru, tak přidám otvory pro šrouby, kdy ze spodní strany podložky budou zahloubené otvory pro matky.

**Comment by Elizaa62** [comment]
Objevil se problém se zahloubením.. problémem je horizontální trubka..

**Comment by kaklik** [comment]
Řekl bych, že je to vyřešeno změnou pozice akumulátorů.

![25319768_10212259109967282_1560003635_o](https://user-images.githubusercontent.com/1194177/33888192-a01b9f94-df4c-11e7-8984-22cfb4402ce7.png)

A teď stačí je urovnat a doplnit třmen na přitažení.

**Comment by Elizaa62** [comment]
Třmenem myslíš tu mou spojku 888_1001?

**Comment by kaklik** [comment]
Ano, technicky se tomu řešení myslím říká třmen: https://eshop.killich.cz/eshop/trmen-sroub-tvar-u-m10-50-bily-zinek-dn-40-22400040_22400040.html

**Comment by Elizaa62** [comment]
Rozumím :)

**Comment by Elizaa62** [comment]
Jinak akumulátory srovnány parametrem move_of_accumulator a zapuštěny parametrem sink_of_accumulator.

**Comment by kaklik** [comment]
Paráda, vyřešeno :)
