### ISSUE TITLE
Vytvořit univerzální vrtací přípravky

### ISSUE THREAD

**Issue by roman-dvorak** [Elizaa62/Components#231]
Udělat vrtací přípravky, které budou obsahovat díry pro provrtání skrz střed tyčí tak i pro boční "čepy" pro uhlíkové tyče. Přípravek by měl mít stahovací šroub, aby bylo možné ho pevně umístit na tyč a stáhnout pomocí šroubu.

Bylo by fajn otestovat přípravek, který bude obsahovat vložky z provrtaných matic.

**Comment by alcamrkvicka** [comment]
Dil je nazvany drill_tool a nachazi se v manufacturing_helpers.
Na zacatku je mozne zakomentovanim zvolit prumer tyce (25mm nebo 10 mm) a sroub (M3 nebo M4).
![image](https://user-images.githubusercontent.com/51204144/63686790-1f792180-c803-11e9-842a-662f92fae592.png)
Je to takto v poradku?

**Comment by kaklik** [comment]
Ještě by bylo potřeba k dílu vytvořit tiskové soubory, které budou obsahovat díl natočený v tiskové pozici (otvorem pro trubku vertikálně) a budou obsahovat různé kombinace průměrů šroubu a trubky.

**Comment by roman-dvorak** [comment]
Dále by bylo potřeba vytvořit varianty, které budou mít na okrají vrtacích děr šestihranný otvor pro zastrčení matic s provrtaným závitem. Cílem toho je, aby vrtách procházel nějakým tvrdším materiálem a neopotřebovával se pak tolik vrtací přípravek. 

Těsně u trubky by následně mohlo být znovu rozšíření, aby se špony nemačkaly do plastu.
