### ISSUE TITLE
Držák tyčí od směrovky nosníku vírníu

### ISSUE THREAD

**Issue by roman-dvorak** [Elizaa62/Components#237]
Držák, který se nastrčí na podvozovou tyč a jednu příčnou a bude zároveň držet podélnou tyč od směrovky. 

![Snímek z 2019-09-06 06-56-30](https://user-images.githubusercontent.com/5196729/64401964-81435200-d073-11e9-83c4-adca81c4ae2f.png)

**Comment by kaklik** [comment]
On rozestup tyčí od směrovky vychází tak, že to lze takto udělat?

**Comment by roman-dvorak** [comment]
Podle jedné starší setavy to vychází do cca jedné třetiny mezery mezi nosníkem a límcem pro kryt
