### ISSUE TITLE
Vytvořit zatáčecí mechanizmus na přední kolečko

### ISSUE THREAD

**Issue by roman-dvorak** [Elizaa62/Components#245]
Protože zatáčení pomocí VESC regulátorů nejspíše zabere ještě nějaký čas, bylo by dobré si vytvořit možnost řízeně pojíždět i s jiným způsobem řízení.

Řízené by bylo přední kolečko. Na díl pod nosníkem je potřeba vymyslet způsob připevnění serva. První otáčející se díl musí mít na sobě nějakou páku nebo místo pro její připevnění.

**Comment by kaklik** [comment]
@roman-dvorak  nechybí v té páce zapuštění pro matku šroubu táhla? 

Ta tloušťka stěny pod šřouby, které tu páku mají držet se mi nezdá zrovna velká.

**Comment by roman-dvorak** [comment]
Spodní část to chce ještě posunout výše. Jinak je to funkční řešení.

**Comment by roman-dvorak** [comment]
Vyřešeno otočením dílu. Změnou polohy zapuštění pro matku.
