### ISSUE TITLE
Vyrobit závaží pro nové rotorové listy

### ISSUE THREAD

**Issue by roman-dvorak** [Elizaa62/Components#248]

**Comment by kaklik** [comment]
Nepomohlo by vyřešit vytékání olova z formy vylepení bočnic formy [keptonovou páskou](https://www.hotair.cz/detail/ochranne-pasky/kaptonove-tepluvzdorne-pasky/kaptonova-tepluvzdorna-paska-sire-150mm.html?gmc)?

Také můžeme pak objednat jiný tvar vyfrézovaných bočnic. A nebo vytisknout jiný tvar ohybacího přípravku na plech.

**Comment by kaklik** [comment]
Aktuálně vyrobená závaží stačí na 3 páry listů.  Problém je tak zatím vyřešen.
