### ISSUE TITLE
Vyzkoušet nový způsob modelování tištěného rotoru

### ISSUE THREAD

**Issue by roman-dvorak** [Elizaa62/Components#249]
Tištěný rotor podle testů s TF:Auto-G2 zřejmě může fugovat. 

V předchozím modelu byly namodelovány všechny infilly způsobem, že STL obsahovalo materiál v místě, kde  měl infill být. Pravděpodobně to není potřeba a lze to zjednodušit tak, že se infill bude modelovat jako štěrbina v "plném" profilu listu. 

Cílem toho issue je hlavně ověřit možnost list tímto způsobem vyrábět a zjistit jeho klady a zápory oproti způsobu využitém u tisku listů pro TF:Auto-G2.

**Comment by roman-dvorak** [comment]
Zatím známý klad je, že OpenSCAD model je podstatně jednodušší

**Comment by kaklik** [comment]
Experimentální profil by měl být symetrický nejspíše NACA0016.
