### ISSUE TITLE
Umístění GPS antény

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#25]
Pod zadní část horní kapoty je potřeba umístit GPS anténu s magnetometrem. 
Modul vypadá přibližně takto: https://hobbyking.com/media/catalog/product/cache/1/image/320x230/9df78eab33525d08d6e5fb8d27136e95/legacy/catalog/55558s2.jpg

A je potřeba, aby byl uchycený na 3 šroubech procházejících otvory skrz plošný spoj. 

Ze spodní strany plošného spoje musí být ponecháno výškově alespoň 5mm prostoru pro součástky naletované na spodní stranu plošného spoje.

**Comment by Elizaa62** [comment]
Toto má být připevněno k podložce 666_1027 v její zadní části?

**Comment by kaklik** [comment]
Ano má to být co nejvíc vzadu jak se to ještě vejde. Umístění je přibližně vidět tady: 
![25625542_10212324012949816_469250530_o](https://user-images.githubusercontent.com/1194177/34358563-1b815264-ea51-11e7-958c-700c81c15eab.jpg)

Rozměry musím pak upřesnit až je změřím, nikde jsem od toho nenašel výkres.

**Comment by Elizaa62** [comment]
Už jsou rozměry? :)

**Comment by kaklik** [comment]
Rozměry jsou tady: 

![Vzdálenost vnitřních stěn otvorů](https://user-images.githubusercontent.com/1194177/34470293-be862bf6-ef2e-11e7-8aa0-270bbc47effb.jpg)

![Vzdálenost vnějších stěn otvorů](https://user-images.githubusercontent.com/1194177/34470286-95ffba80-ef2e-11e7-8e01-61eac268826f.jpg)

Otvory jsou umístěny v rovnostranném trojúhelníku, kde  vzdálenost a průměr otvorů lze spočítat z předešlých fotografií měřených vzdáleností vnitřní a vnější strany otvorů. 

Vnější průměr kruhového plošného spoje 56mm. 

Protože plošný spoj obsahuje z obou stran poměrně vysoké součástky, tak by zřejmě bylo potřeba, aby otvory byly opatřeny distančními sloupky vysokými alespoň 8mm.

**Comment by Elizaa62** [comment]
Nakonec se mi tam podařilo dát všechny tři sloupky mimo horizontální trubku.

**Comment by kaklik** [comment]
Anténa na podložku pasuje. Zatím se úkol může uzavřít dokud nevyzkouším že se vejde pod kryt.
