### ISSUE TITLE
Tolerance vnějšího kardanu spindle head rotorové hlavy 

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#253]
- [x] Střední díl kardanu má okolo sebe velmi velké tolerance. Důsledek toho je, že kardan má značnou volnost v yaw ose. Tolerance můžou být poloviční.

_Originally posted by @roman-dvorak in https://github.com/ThunderFly-aerospace/TF-G1/issues/238#issuecomment-538888355_

**Comment by roman-dvorak** [comment]
Kardan je nyní velmi tuhý! Takto nastavené tolerance jsou super.

**Comment by slimonslimon** [comment]
byla to chyba v kódu, kdy horní díl měl 2x větší vůli než měl mít...
