### ISSUE TITLE
Úprava rozměrů ložiskové vložky 888_1023

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#256]
V souvislosti s úpravou #255  je potřeba upravit podložku 888_1023, tak aby byla nižší o posunutí šroubu způsobené snížením podložky. 

Zároveň by ložisková vložka měla končit otvorem pro šroub M6, aby se síla pro stažení šroubu rotoru nepřenášela pouze přes kuličku kulového ložiska.

**Comment by roman-dvorak** [comment]
Vložka pasovala OK. Byla použita nejdelší varianta. Více se ukáže po rozebrání rotorové hlavy.
