### ISSUE TITLE
Úprava otvoru pro pylon v horním krytu 888_1025

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#257]
Polohu otvoru pro pylon je potřeba v krytech posunout a upravit tak, aby otvor obepínal celou trojici trubek. 

Aktuální stav je zachycen na následujícím obrázku:

![image](https://user-images.githubusercontent.com/1194177/67150995-6e04e280-f2bf-11e9-9bbc-45db751e9d04.png)

**Comment by roman-dvorak** [comment]
Řešení otvoru pro pylon je vyhovující
