### ISSUE TITLE
Uchycení horního krytu na hlavní nosník

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#259]
Hlavní nosník je potřeba doplnit o jeden díl, který bude sloužit k uchycení krytu. 

Tvar posledního dílu by měl vycházet ze špičatého tvaru krytu v jeho koncové části. 
Kryt by měl pasovat do drážky v boční části dílu, podobně jako u límců, které drží okraje krytu.

**Comment by roman-dvorak** [comment]
Díl musí mít navíc díru na šroub pro sešroubování krytu a díl by mohl být o něco delší.
