### ISSUE TITLE
Rozpěrka ložisek předního podvozku

### ISSUE THREAD

**Issue by roman-dvorak** [Elizaa62/Components#261]
Přední kolečko nešlo připevnit velkou silou z důvodu, že ložiska předního podvozku nemají mezi sebou rozpěrku, která by zamezila křížení ložisek. Tento kloub se choval, tak, že pří dotažení (relativně malou silou) byla potřeba velká síla k zatočení kolečka. 

Je tedy potřeba upravit prostřední díl předního podvozku tak, aby se tam vešla rozpěrka ložisek a takovou rozpěrku namodelovat.

**Comment by kaklik** [comment]
Tu rozpěrku bych udělal kovovou z uříznuté hliníkové trubky 10x8mm. Takže rozpěrku není potřeba modelovat pouze je nutné určit jak má být dlouhá, aby ji  šlo na soustruhu vyrobit.
