### ISSUE TITLE
Zpevnění předního kolečka

### ISSUE THREAD

**Issue by roman-dvorak** [Elizaa62/Components#262]
Při testu se ukázalo, že přední kolečko #189 není dostatečně tuhé a kolečko se z dílu dokázalo vylomit.
![063A7370s](https://user-images.githubusercontent.com/5196729/67811155-736ee380-fa9c-11e9-90fe-27d2133cf970.JPG)

Při prohlížení dílu se zjistilo, že trubička okolo osy není s ničím zpevněna. Pouze infillem. Tento problém je potřeba eliminovat několika změnami současného dílu. 

- [x] Použití delšího lícovaného šroubu 8x70.
Tato změna by měla sílu rozložit na větší plochu. Ale i tak by v  dílu byla trubička, která nebude ničím pořádně vyztužena. To je potřeba vylepšit dvěmi způsoby.

- [x] Prodloužení kapsy na matku.
Kapsu na matku lícovaného šroubu by bylo vhodné udělat skrz celý díl. V orientaci zepředu dozadu. 

- [x] Vyztužovací otvory u osy kolečka. 
V dílu vymodelovat výztuhy od osy kolečka. Takové výztuhy mají za cíl v dílu vytvořit perimetry, které budou spojovat trubičku osy s vnějšími perimetry. To může být provedeno tak, že skze model budou vytvořeny díry (např d=1mm), které budou následně umístěny do spirály podél lícovaného šroubu. 

- [ ] Změna orientace vrstev při tisku modelu. Díl by měl být namodelován tak, aby umožňoval tisk vrstev co nejblíže ideální orientaci 45 stupňů vůči ose šroubu procházejícího ložisky. 

Mělo by to být uděláno tak, že následující díra bude pootočena např o 110 stupňů a o cca 3 mm výše.

- [x] Mezi prvním a druhým dílem předního podvozku (tam, kde se podvozek otáčí) je potřeba do horního dílu zapustit podložku. To má za cíl zvětšit plochu, přes kterou se přenáší síla a díky zapuštění nebude mezi díly taková mezera. A při větší síle se styčné plochy těchto dílů o sebe opřou a nebudou tolik vylamovat osu.

Tyto body jsou znázorněny na následujícím nákresu:
![20191029_230917](https://user-images.githubusercontent.com/5196729/67813824-d794a600-faa2-11e9-95cd-eb79f9634f07.jpg)
Na prvním obrázku je vidět vnitřní struktura dílu. Na druhém je pak řez při pohledu z boku.

- [x] Zarážky, které zamezují přetočení kolečka udělat širší.

**Comment by kaklik** [comment]
Alternativní možností, jak držák kolečka zpevnit je udělat ho žebrovaný. Podobně, jako byl [zpevněn krček rotorové desky](https://github.com/ThunderFly-aerospace/TF-G1/blob/f3a17a0dad45fde1ed40cace4f3c18f7caf67669/STL/888_1020_plastick_neck.stl).

**Comment by kaklik** [comment]
Šrouby držící horní díl předního kolečka musí mít matky až pod kapsou pro matku hlavní osy kolečka. Cílem je aby v žádné části dílu nebyly síly přenášeny tahem za vrstvy ale, tlakem. 

Nejdelší M4 šrouby, které aktuálně máme jsou M4x55 mm dellší by bylo nutné koupit.

**Comment by roman-dvorak** [comment]
No, aktuálně tam jsou použity šrouby M4x55.

**Comment by kaklik** [comment]
Také je potřeba, aby model byl uzpůsoben na kratší páku serva. Nově bych tam dal páku 25mm.
