### ISSUE TITLE
Zvětšení odolnosti serv směrovky proti poškození rotorem

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#267]
Vzhledem k minulým poškozením se ukazuje jako výhodné, kdyby pohyblivé části směrovky mohly být v modelu umístěny blíže ke spodní straně pevné části.  (posunuty dále od místa spojení levé a pravé směrovky). 
Taková úprava by zároveň vyřešila potíž s možnou kolizí pohyblivých částí v horní části směrovky při výrazném potlačení.

**Comment by taury55** [comment]
Nevím, jestli to bylo myšleno takhle, ale posunul jsem pobyblivou část směrovky níže.

**Comment by kaklik** [comment]
ano, takhle to bylo myšlený.
