### ISSUE TITLE
Umístění Pitotovo trubice

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#27]
Úpravou dílu 666_1014 je potřeba vytvořit držák "airspeed" senzoru na zadní podvozkovou nohu. 
Snímač vypadá takto
![pixhawk-px4-differential-airspeed-head-pitot-tube-pitot-tube-airspeedometer-for-px4-autopilot-flight-controller jpg_640x640](https://user-images.githubusercontent.com/1194177/38755871-ad80fca8-3f67-11e8-984b-cd6c2372374a.jpg)

A jeho úkolem je měřit rychlost proudění vzduchu.  K tomu je potřeba, aby měřící trubice směřovala dopředu proti ose letu.

**Comment by kaklik** [comment]
Aby se tenhle úkol také pohnul, tak jsem vymyslel ještě alternativní, možná jednodušší řešení, že by se pitotova trubice dala do vrchní části krytu 666_1032. Do úrovně rotorové hlavy. 
V krytu by bylo možná jednodušší vytvořit potřebný otvor a místo se šroubem kterým se pitotova trubice přišroubuje. 

Výhodou tohoto řešení je, že by vstupní otvory byly lépe chráněny před znečištěním.

**Comment by Elizaa62** [comment]
Já si asi nedokážu pořádně představit, jak to myslíš...  protože když na dílu 666_1032 udělám otvor pro šroub pro připevnění trubice, tak mi ten díl pod tíhou šroubového spojení praskne nebo se ohne..

Nebo tam vytvořím nějakou výztuhu..

**Comment by kaklik** [comment]
Teď mi došlo, že jsi ten díl asi zřejmě neviděla. Protože on tak chatrný není. Jediný problém je s tím, že momentálně za nic pevně nedrží. Což by mohl být problém, když se na něj má něco přidělávat.  Správně by asi měl držet za tu vertikální trubku.  Nebo se na spojku 666_1026 musí doplnit nějaké výstupky na které se přišroubuje. 
 Bude spíš potíž v tom vymyslet to tak, aby se to dobře montovalo.  

Napadá mě ten kryt rozdělit na přední a zadní část s tím, že tyhle dvě části by se šroubovaly k sobě.  Pod předním krytem pak může být držák Pitotovo trubice přímo na vertikální trubce.

**Comment by kaklik** [comment]
Tady jsem zkusil změřit některé významné rozměry té sestavy trubice. 

Vnější průměr trubky
![20180416_182340](https://user-images.githubusercontent.com/1194177/38824894-085a427a-41ab-11e8-970b-adc23d08d2f2.jpg)


Vzdálenost okraje trubky k hraně díry pro připevnění.
![20180416_182751](https://user-images.githubusercontent.com/1194177/38825082-a468b516-41ab-11e8-8280-2e12445eb354.jpg)

**Comment by Elizaa62** [comment]
Vytvořeno připevnění k dílu 666_1032.

**Comment by kaklik** [comment]
Ano, tak nějak by to mohlo být. 

- Bylo by ale potřeba tu trubici vysunout co nejvíc dopředu.  Protože na ty dva vývody se připojují hadičky. A takhle tam bude málo místa na ohyb. 
- Šroub pro uchycení je umístěný v jiné úrovni, než samotná trubka. Viz poslední fotografie v mém komentáři.

**Comment by kaklik** [comment]
Tak myslím, že ten nápad funguje docela dobře. :) 

Potenciální problém vidím v ostrém ohybu hadičky. Ale zatím to tak necháme. 

![20180427_213118](https://user-images.githubusercontent.com/1194177/39382848-44e5d6ea-4a67-11e8-89a9-e7121f6da915.jpg)
