### ISSUE TITLE
Automatické slicování modelů přes makefile

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#270]
Aktuálně slicer vypusuje tuto chybu: 

```
slicing/generic/basic_part.ini
   Slice STL/888_1016.stl with ./utils/slicer/PrusaSlicer-2.1.0.AppImage    slicing/888_1016.ini   
./utils/slicer/PrusaSlicer-2.1.0.AppImage: 1: ./utils/slicer/PrusaSlicer-2.1.0.AppImage: version: not found
./utils/slicer/PrusaSlicer-2.1.0.AppImage: 2: ./utils/slicer/PrusaSlicer-2.1.0.AppImage: oid: not found
size: '57700328': No such file
   Error in slicing
```

Je však potřeba ještě 

- [x] Připravit unifikované nastavení sliceru pro většinu modelů
- [x] Vytvořit specifické konfigurace pro některé díly

**Comment by kaklik** [comment]
Problém se spuštěním spočíval v nenakonfigurovaném [git lfs](https://git-lfs.github.com/).

**Comment by kaklik** [comment]
Vypadá to, že aktuálně generované g-kódy neobsahují inicializační sekvenci 

`;D3D:START:START
T0
M104 S215
G21
G90
M107
T0
G28
G29
M109 T0 S215
G0 F3000
M107
T0
G92 E0
G0 X0 Y149 Z0.1 F3600
G1 Y49 E6.5 F1200
G0 Z1
G92 E0
`

Navíc některé nepovnostní díly jako například lem krytu, mají více než jeden perimetr. Výplň dílů je také zřejmě typu zig-zag a není kubická.

**Comment by roman-dvorak** [comment]
No, to se asi díváš na staré soubory. Protože nové (od cca poledne) to už obsahují. To samé platí i o infillu. Tento výchozí profil jsem přepsal z S3D profilu. Zřejmě bude potřeba udělat nějaké další úpravy konfigurace.

Co se týče dílů krytu, tak tam se předpokládá, že pro ně bude nějaký specifický profil sliceru.

**Comment by kaklik** [comment]
Aktuálně slicování funguje.
