### ISSUE TITLE
Získání translací z Slic3r při slicování do gcodu.

### ISSUE THREAD

**Issue by roman-dvorak** [Elizaa62/Components#279]
Dosavadní makefile generoval pouze stl soubory. Tyto soubory se pak využívaly k tisku a využívaly se v sestavách.

U některých modelů (např tištěný rotor) by bylo vhodné mít možnost používat modifikátory k automatizování používání modifikatorů je potřeba právě AMF (více o tom v #278)

Dále by to chtělo prozkoumat, jestli je potřeba generovat i STL. Nebo jestli dokážeme STL plně nahradit s AMF. Popřípadě jak by taková konverze měla vypadat.

**Comment by kaklik** [comment]
@JanKott  Podíval by ses na to?

**Comment by JanKott** [comment]
Nějak nerozumim o co jde. Můžete mi to trochu rozvést?

**Comment by roman-dvorak** [comment]
Jo, v tomto issue není přesně popsáno, co by bylo potřeba.

K slicování dílů používáme Slic3r. Ten byl vybrán z důvodu, že jako jediný umí nějakým způsobem pracovat s konfiguračními soubory a parametry z přikazové řádky. 

Při slicování s modelem udělá dvě zásadní věci a to, že ho přesune v ose Z tak, aby přesně seděl na podložku a pak model vycetruje v X, Y. Hodnoty těchto translací se během generování g-kódu ztratí.

Bylo by ideální aby se tyto informace ukládaly přimo do gcodu. Znalost této translace je potřebná třeba při výpočtu těžiště modelu z gcodu. Pokud je infill velmi řídký, tak se těžiště plného tělesa (STL/AMF) může o dost lišit oproti těžišti gcodu. 

Dokud jsme používali STL, tak jsem udělal skript, který si určil hranice STL souboru. Následně to porovnal s gcodem a podle toho odhadl všechny tři posuvy. Ale s použitím AMF to zatím neumím a je to strašně nesystémové řešení. Proto by to bylo nejlepší upravit zdrojový kód Slic3eru tak, aby hodnoty translací zapsal do gkódu.

**Comment by JanKott** [comment]
Zkusim se kouknout do zdrojáků, ale jen tak cvičně - tohle by nestačilo:

--export-gcode will center the model around the centroid point of the configured print bed (**unless the --dont-arrange option is supplied: original coordinates will be used in that case**) ?

**Comment by roman-dvorak** [comment]
Ano, zarovnání okolo středu - tak to je výchozí nastavení. A tam právě vznikají ty tři neznámé transformace. 

Vypnutí posuvu je také možné. Tam je však velmi slžité zajistit v modelech, že jsou umístěné nějakých 7.5 a 7.5cm mimo počátek souřadnic. A 0mm v ose Z. Naopak většina modelů se modeluje v počatku souřadnic (není to pravidlo).

Na základě těchto předpokladů právě funguje ten můj skript pro STL, který tu transformaci odhadoval. Pak je další věc, když se bude tisknout na více různých tiskárnách. Jedna má podložku 15x15, další 18x18 a pak 20x20 či více. A bylo by fajn, aby to bylo vždy ve středu. (tohle je ostatně také trochu nedořešené z pohledu generování gcodu, kde se využívá pouze jeden konfigurák pro všechny.

**Comment by kaklik** [comment]
Těch konfiguráků pro tisk si dovedu představit, že bude více. Každopádně je ale nežádoucí, aby se při tisku na jiné tiskárně muselo šahat do modelu.

**Comment by kaklik** [comment]
Tady je testovací příklad (AMF a STL), který vygeneruje kostku spodní stranou 100mm nad podložkou v počátku souřadnic. 
Další alternativní posuvy je třeba dodatečně vyzkoušet: 


[test.zip](https://github.com/ThunderFly-aerospace/TF-G1/files/4160973/test.zip)


![image](https://user-images.githubusercontent.com/1194177/73860659-2be6b900-483c-11ea-9ace-83797f653007.png)


Spuštění příkladu se provede následujícím příkazem, kde je potřeba použít absolutní cesty ke všem souborům. 

```
kaklik@popelnice:~/tmp/slicer_test$ ./slic3r.AppImage --load /home/kaklik/tmp/slicer_test/default.ini -o kaklik/tmp/slicer_test/tmp_kostka.gcode  --no-gui -j 3 /home/kaklik/tmp/slicer_test/tmp_cube.stl 
=> Infilling layers
=> Generating brim
=> Exporting G-code to kaklik/tmp/slicer_test/tmp_kostka.gcode
Failed to open kaklik/tmp/slicer_test/tmp_kostka.gcode.tmp for writing
kaklik@popelnice:~/tmp/slicer_test$ 
```
Pro vstupní formát AMF platí stejné parametry.

Binárka sliceru je [odsud](https://github.com/ThunderFly-aerospace/TF-G1/raw/improved_suspension/utils/slicer/Slic3r-1.3.1-dev.AppImage).
Výsledkem je gcode posunutý tak, aby tisk začínal na podložce a byl v jejím středu. Úkolem je binárku sliceru nahradit verzí, která do gkódu přidá jako komentář informaci o použitých posuvech ve všech třech osách.

Formát posuvů zapsaných v g-kódu může zachovávat stávající formát slic3ru pro parametry v gkódu. Tady: 
```
; <název> = <hodnota>
```

**Comment by JanKott** [comment]
Doplnil jsem zapisování posunu a rotace do gcode souboru. Na příkladu to funguje, až to zkusíte na něčem složitějším, dejte vědět.
