### ISSUE TITLE
Misto pro převoz listů v TF-R1

### ISSUE THREAD

**Issue by roman-dvorak** [Elizaa62/Components#280]
V návaznosti na #274 pro převoz listů v TF-R1 by bylo možné udělat háčky (/poličky) na listy do kufru. Takové háčky mohou být zavěšeny za hlavové opěrky zadních sedadel. Listy by se do nich pouze položily. 

Je potřeba přeměřit rozměry v autě.

**Comment by kaklik** [comment]
Myslím že tohle je aktuálně vyřešeno umístěním listů za klabice v kufru.
