### ISSUE TITLE
Rozdělení horizontální osy mezi písty předního kolečka

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#282]
V současné konstrukci je horní uchycení pístů realizováno relativně dlouhou závitovou tyčí, která je horizontálně prostrčena ložisky v prostředním otočném dílu. Na tuto závitovou tyč jsou z obou stran nasazeny držáky svislých pneumatických tlumičů.

Tato konstrukce je nevýhodná, neboť vyžaduje při dotahování/povolování použití nejméně dvou plochých klíčů zároveň (aby se zabránilo protáčení matice na druhé straně).

Vhodnější by bylo ložiska přesunout do držáků válců, případně kuličková ložiska úplně zrušit a nahradit je pouze kluznou vložkou, která bude přes podložky přitažena šroubem k prostřednímu otočnému dílu kolečka. 

Pro uchycení pneumatických válců můžou být klidně použity šrouby průměru M3  (pro každý pneumatický válec jeden) zašroubované do matek v kapsách otočného dílu. 

Kluzná pouzdra, která máme k dispozici jsou následující: 

![image](https://user-images.githubusercontent.com/1194177/73751612-b9081000-475f-11ea-9a12-536a18c0eff3.png)

Rozměry kovových pouzder jsou 6x7mm a plastového pouzdra 6x18mm.  Preferované  řešení je použití kratšího kovového pouzdra. Za tímto účelem je pravděpodobné, že bude nutné osu pneumatického válce posunout blíže ke kolu. To lze zajistit změnou uchycení spodního kulového Igus čepu tak, aby byl uchycen ve vidlici z obou stran. Pak místo jeho uchycení nebude závislé na šířce vidlice, ale pouze na šířce kola.

**Comment by roman-dvorak** [comment]
Nákres řešení rozdělení horní horizontální osy předního podvozku z použitím kluzné vložky.
 
![84011186_478496809707786_104108160419102720_n](https://user-images.githubusercontent.com/5196729/73751150-ca045180-475e-11ea-9a25-c18c8b7f47d7.jpg)

**Comment by raska-vilem** [comment]
šel by tam použít i lícovaný šroub?

**Comment by kaklik** [comment]
Lícovaný šroub nemáme takhle krátký, museli bychom ho koupit. Proč? Zdá se ti to v něčem lepší?

**Comment by raska-vilem** [comment]
lícovaný šroub by lépe rozkládal sílu na díl připevněný k pístu

**Comment by kaklik** [comment]
> lícovaný šroub by lépe rozkládal sílu na díl připevněný k pístu

Jak to? Lícovaný šroub o průměru 6mm bude rozkládat sílu úplně stejně jako mosazná vložka s průměrem 6mm, ne?

**Comment by roman-dvorak** [comment]
Rozklad sil na díl připevněný k pístu by právě neměl být moc rozdílný. Protože pouzdro má stejný vnější průměr.

Navíc tady, když se z obou stran pouzdra dají podložky, tak ten díl nad pístem se bude moct na ose volně otáčet. Což je výhoda. 

A jestli se Ti to zdá málo robustní.. :) Tak na druhé straně (u igus ložiska) je to připevněné pomocí M3 šroubu.

**Comment by roman-dvorak** [comment]
@cesilko1 vidím nové commity? Je to už podle Tebe nějak vyřešené? (jako že si to mám prohlédlout :) ) Nebo na tom ještě plánuješ pracovat?

**Comment by raska-vilem** [comment]
Mrkni na to ;)

**Comment by kaklik** [comment]
Nově upravený díl při tisku neleží na podložce. 

![image](https://user-images.githubusercontent.com/1194177/74454013-8eb30280-4e83-11ea-99b1-fc05e451bf0d.png)

**Comment by raska-vilem** [comment]
v [888_2024.scad](https://github.com/ThunderFly-aerospace/TF-G1/blob/improved_suspension/src/888_2024.scad) stačilo na konci přidat parametr `888_2024(1);`

**Comment by kaklik** [comment]
Dobře, ale proč to není, nebo nefunguje v tiskové  sestavě? 
https://github.com/ThunderFly-aerospace/TF-G1/blob/improved_suspension/src/4printing/print_plate_888_2024.scad

Ten gkód ze kterého je generován obrázek výše vzniknul standardním procesem  (spuštěním make)  A jeho výsledek není dobrý, což znamená, že někde pocestě něco nefuguje..

**Comment by roman-dvorak** [comment]
Já to tam teď vidím v pořádku. (tedy v scad souboru)

**Comment by raska-vilem** [comment]
už jsem posunul ty písty

**Comment by roman-dvorak** [comment]
Nové kolečko vypadá fakt dobře! Ještě je tam trochu problém s délkou dílů. Více v #269
