### ISSUE TITLE
Připevnění ventilu předních pístů

### ISSUE THREAD

**Issue by roman-dvorak** [Elizaa62/Components#284]
Ještě bych Tě chtěl @cesilko1 poprosit o jednu úpravu středního podvozkového dílu. A to přimodelování držáčku na ventil od pístů. Důvod této úpravy je, aby tam ventil nějak moc nevlál popřípadě se nedřel o kolečko. 

Přibližné umístění je vidět na následujícím obrázku. Předpokladám,  že by se připevnil dvojicí M3 šroubů do otvoru, který by byl ve středu toho dílu. taková díra by měla zároveň celý díl vystužit. Matka by měla být zapuštěna z horní strany. Rozteč děr pro šrouby na ventilu je 16.5 mm. 

![20200216_211635](https://user-images.githubusercontent.com/5196729/74641586-d8486980-5171-11ea-8622-78098064394d.jpg)

**Comment by kaklik** [comment]
@roman-dvorak  je tohle stále aktuální?

**Comment by roman-dvorak** [comment]
Tohle issue bych teď ukončil. S upraveným podvozkem a obráceně umístěnými písty by to připevnění mělo vypadat o dost jinak. Teď bych to však vyřešil sdrhovací páskou.
