### ISSUE TITLE
Dělení horního krytu 666_1025

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#30]
Při tisku tohoto dílu: https://github.com/kaklik/Components/blob/master/STL/print_plate3.stl jsem zjistil, že držák krytu vertikální trubky je ve skutěčnosti horizontální převis a kazí se tím kvalita tisku. 

Řešením by bylo posunout dělení částí krytu tak, aby držák začínal na podložce a tisková podložka ho tak od začátku tisku podpírala.

**Comment by Elizaa62** [comment]
Mě ten odkaz nejde otevřít..

**Comment by Elizaa62** [comment]
Není toto už náhodou vyřešené?

**Comment by kaklik** [comment]
Omlouvám se za nefungující odkaz, soubor jsem smazal a neuvědomil si to. Odkaz nyní funguje.  Vyřešené to ale není, neboť díl vypadá takhle: 

![image](https://user-images.githubusercontent.com/1194177/34253780-5570d7b2-e649-11e7-88c3-21bee749f94d.png)

Tím pádem se začátek držáku krytu pylonu stále tiskne do vzduchu.

**Comment by Elizaa62** [comment]
Vyřešeno rozdělením tohoto kusu na díl B a BB a přidání lemu ke každému kusu.

**Comment by kaklik** [comment]
Ano, je to vyřešeno skoro úplně.  Teď akorát vznikla nová potíž s tím, že vnikl díl, který se při tisku rozpadne na dvě samostatné poloviny.  Na screenshotu uprostřed: 
![image](https://user-images.githubusercontent.com/1194177/34341297-596d090e-e995-11e7-8c46-dd5c34cc57d1.png)

Řešením je dělení krytu poposouvat tak, aby po vytištění byly obě části spojené a zároveň aby se délka mezi děleními vešla do maximálního tiskového rozměru. Tiskárny edee: https://www.ysoft.com/cs/edee/edee-printer/edee-printer-detail

**Comment by Elizaa62** [comment]
![vystrizek](https://user-images.githubusercontent.com/31339298/34388651-3cf7128c-eb35-11e7-9ae0-faa3563b212f.PNG)

**Comment by Elizaa62** [comment]
Takhle by to dělení už mohlo být?
Ptám se protože se mi nechce stokrát vše předělávat. Část B je dlouhá 100 mm, část BB 150 mm a část C 75, část D je ten zbytek.

**Comment by kaklik** [comment]
ano, takhle to být může. :) 
Tomu stokrát předělávání se dá vyhnout i tak, že místo toho dělení bude nastavitelné. 
Ale rozdělení z obrázku mi momentálně bude stačit.

**Comment by Elizaa62** [comment]
Přestávám tě mít ráda a začínám se propadat do další deprese...

**Comment by Elizaa62** [comment]
Zavedení nové proměnné pro dělení, proměnná zakomponována v rozdělení pro tisk a v umístění šroubů, rantlů a zámků.

**Comment by kaklik** [comment]
Ta změna na parametrické dělení je úplně parádní. Rovnou jsem to i využil a snížil jsem o jeden počet dílů krytu tím, že jsem posunul dělení tak, aby lépe vycházela do tiskového rozměru. 

![image](https://user-images.githubusercontent.com/1194177/34425478-8edd46e6-ec2c-11e7-8a73-2a99680592d6.png)
