### ISSUE TITLE
Tloušťka podložky 666_1027

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#33]
Tloušťka podložky 666_1027 by se měla odvíjet od parametru main_tube_diameter.

**Comment by Elizaa62** [comment]
Intersection pomocí cube ve velikosti v ose y -> main_tube_diameter

**Comment by kaklik** [comment]
Z důvodu snížení hmotnosti by zřejmě šlo na mnoha místech podložky odečíst kvádry, aby nebyl žádný materiál na místech, kde to není potřeba.  To by zřejmě bylo vhodné udělat jak ve svislém, tak i v podélném i v příčném směru.  Hmotnost současného modelu podložky je cca 260g.

**Comment by kaklik** [comment]
Vytvořil jsem první pokus o odlehčení podložky. 

![image](https://user-images.githubusercontent.com/1194177/34412326-de537cea-ebdc-11e7-9677-02bb09becdbb.png)

**Comment by kaklik** [comment]
Tady teď asi ještě vznikla potíž tím, že jsem odebral zakulacení hran podložky. Tím se změnila celkové tloušťka. 
Zřejmě by to díky tomu chtělo znovu nastavit tloušťku podložky tak, aby spojky na hlaví trubce byly zároveň s rovinou podložky. A aby spodní plocha podložky právě dosedala shora na trubky od podvozkových nohou.

**Comment by kaklik** [comment]
Tak tloušťku spojky jsem změnil tak, aby kopírovala parametry spojky 1004.
