### ISSUE TITLE
Vytvořit spojku pro akumulátor pro připevnění k 666_1027

### ISSUE THREAD

**Issue by Elizaa62** [Elizaa62/Components#35]
Vytvořit účkovou spojku ve tvaru kvádříku pro připevnění akumulátoru k dílu 666_1027. Společně s vytvořením této spojky udělat díry pro šrouby a otvory pro matky v dílu 666_1027. Spojky by měly nejspíše dvě pro upevnění každého akumulátoru.

**Comment by Elizaa62** [comment]
Spojka je vytvorena pod nazvem 888_1001. Diry pro upevneni v dilu 666_1027 nejsou zatim hotove.

**Comment by kaklik** [comment]
Ano, konstrukce třmenu pro přitažení akumulátorů vyhovuje.  Jenom bych navrhoval zvětšit tloušťku částí s dírami na šrouby, aby byla stejná, nebo větší než v ostatních místech.

**Comment by Elizaa62** [comment]
Zvětšeno parametrem height_cube
