### ISSUE TITLE
Připevnění horizontální trubky k dílu 666_1027

### ISSUE THREAD

**Issue by Elizaa62** [Elizaa62/Components#36]
Původně jsem myslela, že by se ta trubka dala k podložce připevnit účkovou spojkou, které by se ale musela připevňovat šrouby, což je váha navíc. Ale jelikož trubka je v té podložce položená hluboko, tak mě napadlo, že když plast, ze kterého se tisknou veškeré věci, je ohebný, tak by se mohly vytisknout takové podložky (viz díl 888_1002.scad), které by fungovali na principu připevňování horního a spodního dílu krytu. Jakoby by se zacvakly do připravených děr v otvoru na horizontální trubku. V dílu 666_1027 jsem otvory na tyto spojky znázornila. Jsou pod bodem //připevnění k horizontální trubce. Mohl by ses prosím vyjádřit k tomu, zda by to fungovalo?

**Comment by kaklik** [comment]
Nerozumím tomu, jak to má fungovat. V dílu 666_1027 otvory nevidím. Vidím jenom tohle: 

![image](https://user-images.githubusercontent.com/1194177/33965220-5a3e9e58-e05b-11e7-8e33-450e4eeea7dd.png)

**Comment by kaklik** [comment]
Asi bych navrhoval řešení, že se díl připojí ke trubce podobně jako jiné vytištěné spojky.  A to tak, že se zboku do trubky provrtá otvor třeba na 50mm dlouhé M3 šrouby. Které budou zapuštěné v podložce.  Počet šroubů nemusí být velký mohl by stačit jeden do každého  tištěného segmentu podložky.

**Comment by Elizaa62** [comment]
Vytvořila jsem tam otvory zároveň pro šroub a matku v každé dělené části v hloubce main_tube_outer_diameter/2.

**Comment by kaklik** [comment]
Umístění šroubů je úplně tak jak jsem to myslel.  Jenom vidím, že šrouby zrovna protínají místa plastových spojek na trubkách a také jsou ze spodní strany odkryté:
![image](https://user-images.githubusercontent.com/1194177/34341160-b3d68036-e991-11e7-8f0d-cf6ab226ba82.png)

Myslím, že by bylo lepší, kdyby šrouby byly zapuštěné podobným způsobem jako šrouby pro připevnění třmenu akumulátoru.

**Comment by Elizaa62** [comment]
Už neprotínají plastové spojky, posunula jsem je. A jak tam chceš teoreticky vůbec ten šroub vložit, když ze spodní strany bude zakrytý?

**Comment by kaklik** [comment]
Vložení šroubu bude z boku šetihrannou dírou. Z druhé strany se vloží matka. Udělal jsem vzorovou úpravu na předním dílu.

**Comment by Elizaa62** [comment]
Opraveno dle tvého způsobu.

**Comment by kaklik** [comment]
Jo tak jsem si to představoval.  Jenom teď bude potřeba vymyslet, jak to ještě zkombinovat s odlehčením podložky.  
Zřejmě v těch místech šroubů bude potřeba po odlehčení přidat materiál, tam kde je potřeba. 

Jinak tohle issue nedovedu zavřít, protože není moje a nemám tlačítko "close"
