### ISSUE TITLE
Velikost prostoru pro akumulátory

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#44]
Výška třmenu pro připevnění akumulátorů zřejmě nepočítá s částečným zapuštěním akumulátoru do podložky. 

![dsc09666](https://user-images.githubusercontent.com/1194177/34338443-15337632-e969-11e7-905b-a96accd59b91.JPG)

Zároveň skutečné rozměry akumulátoru jsou zřejmě jiné než deklarované v dokumentaci. Liší se zejména délka akumulátoru. Délku zahloubení pro akumulátor by proto bylo potřeba zkrátit na skutečný rozměr, aby se akumulátor nemohl posunout a tím změnit těžiště. 

![20171223_100902](https://user-images.githubusercontent.com/1194177/34338183-5404a050-e966-11e7-9bae-98d3022d09ad.jpg)
![20171223_100949](https://user-images.githubusercontent.com/1194177/34338184-59bb24c4-e966-11e7-92d2-64bd767c407f.jpg)
![20171223_101015](https://user-images.githubusercontent.com/1194177/34338187-5fdc419e-e966-11e7-922d-398e47156e3f.jpg)

**Comment by Elizaa62** [comment]
Rozměry otvorů pro akumulátory jsem dala přesně takové jaké jsou zobrazeny na posuvce.

**Comment by Elizaa62** [comment]
Rozměr spojky nevím proč nepočítal nepočítal se zahloubením, ale už by to mohlo snad fungovat.

**Comment by kaklik** [comment]
Díval jsem se, že rozměry akumulátorů jsou nastaveny jednak v module 888_1001() a pak také v module 666_1027(). Aby se správně počítalo zahloubení, tak je potřeba, aby parametry byly nastavené jenom na jednom společném místě a to nejspíše v souboru Parameters.scad. 
Chtěl jsem to přesunout, ale nevím co je proměnná "okraj" takže jsem to nechtěl rozvrtat.

**Comment by Elizaa62** [comment]
Všechny parametry týkající se akumulátoru jsem přesunula do parameters.scad. Jsou tam nominální rozměry akumulátoru, jeho posunutí na podložce a výška zahloubení.

**Comment by kaklik** [comment]
Takže vyřešené.
