### ISSUE TITLE
Zub na lemu krytu

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#45]
Na horním krytu vznikl během úprav zub, který je mezi spodním lemem patřícím do drážky v podložce  původním krytem bez lemu: 
![image](https://user-images.githubusercontent.com/1194177/34341285-dd2ed868-e994-11e7-889f-982da8a1b6b7.png)

**Comment by Elizaa62** [comment]
Nerozumím...

**Comment by kaklik** [comment]
Na přiloženém obrázku je vidět, že spodní lem nenavazuje hladce na stěnu, ale je tam zub.  Domnívám se, že je to způsobené tím, že spodní lem je nějak doplněný na předtím již zakulacené zakončení stěny. 
![image](https://user-images.githubusercontent.com/1194177/34380776-41ad7766-eb04-11e7-8dd8-94c302484479.png)


Řešením by například bylo, kdyby lem nebyl "další přidaný materiál", ale kdyby vznikal už z původního tvaru kapky.

**Comment by Elizaa62** [comment]
Ale jak to mám udělat?

**Comment by Elizaa62** [comment]
Vypadá, že ten zub nezpůsobuje ten lem.

**Comment by Elizaa62** [comment]
Tak jsem tam nechala ten můj způsob. Jen jsem změnila odečítací kapku. Tak jak jsi to chtěl udělat ty, tak mi to nešlo.

**Comment by kaklik** [comment]
Nevím co přesně se změnilo, ale nyní je zub na přechodu stěny a lemu v přední části krytu: 
![image](https://user-images.githubusercontent.com/1194177/34385830-c573ae64-eb25-11e7-93eb-0ec85d64a515.png)

Na lemu zub ale už nevidím. :)

**Comment by Elizaa62** [comment]
Tak změnil se ten zub z těch předchozích obrázků.

**Comment by kaklik** [comment]
Ano, ten tam už není. Myslel jsem to tak, že nevím co způsobilo, že je tam tenhle nový zub, který tam myslím nebyl.

**Comment by Elizaa62** [comment]
Už by tam ten zub být neměl.
