### ISSUE TITLE
Symetrie podložky 1027

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#47]
Některé části položky mi připadají nesymetricky vzdálené od středu. Například se to teď projevilo na pozici akumulátorů a otvorů pro matky.  Něco z toho je posunuté asymetricky. Viz následující obrázky: 

![image](https://user-images.githubusercontent.com/1194177/34385524-b9af8fe6-eb23-11e7-8f31-9a331abd580b.png)

![image](https://user-images.githubusercontent.com/1194177/34385543-cbefcacc-eb23-11e7-8de2-77bb69853153.png)

**Comment by kaklik** [comment]
Tahle záležitost se vyřeší použitím funkce mirror na union otvorů na jedné polovině podložky.

**Comment by Elizaa62** [comment]
Vyřešeno funkcí "mirror" jak pro horní kryt, tak pro spodní kryt.
