### ISSUE TITLE
Vytvořit otvory pro trubky od podvozku v 666_1027

### ISSUE THREAD

**Issue by Elizaa62** [Elizaa62/Components#50]

**Comment by kaklik** [comment]
Tady nerozumím co se tím myslí.

**Comment by Elizaa62** [comment]
myslí se tím to, že si myslím, že jelikož se dělají díry do spodního krytu na trubky a ten spodní kryt zasahuje až do půlky té podložky, tak v té podložce budou taky potřeba otvory na ty podvozkové trubky.

**Comment by kaklik** [comment]
Takhle jak to je nakreslené, tak když se podložka nasadí na středovou trubku, tak přesně dosedá jak na středovou trubku, tak i na shora příčné trubky k podvozkovým nohám. Myslel jsem, že je to tak záměr.

**Comment by Elizaa62** [comment]
Asi je. Nekoukala jsem, jak to tam vychází.

**Comment by kaklik** [comment]
V tom případě si myslím, že to vychází dobře a prozatím se to může uzavřít, aby to neodvádělo pozornost od důležitějších úkolů.
