### ISSUE TITLE
Kabelový prostup do spodní části krytu

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#51]
K opticalflow senzoru a k tlakovému snímači pitotovo trubice, které budou umístěny v zadní části spodního krytu je potřeba přivést kabely. Proto je nutný kabelový prostup o rozměrech minimálně 5x10mm z horní plochy podložky 1027 do spodní.

**Comment by Elizaa62** [comment]
Kde by ten prostup měl být utvořen? Prostředek? Bok?

**Comment by kaklik** [comment]
Došlo mi, že když se udělá to odlehčení podložky, co jsem navrhoval, i v zadní části. Tak  tohle bude vyřešené. Protože ty vodiče půjde protáhnout některým z otvorů. :)
