### ISSUE TITLE
Změnit umístění šroubů z 666_1025 v 666_1027.

### ISSUE THREAD

**Issue by Elizaa62** [Elizaa62/Components#54]

**Comment by Elizaa62** [comment]
Objevil se mi problém, že když zobrazím šrouby v části A v dílu 666_1025, tak vůbec nejsou v tom daném dílu, ale otvory pro šrouby v té části jsou.

**Comment by kaklik** [comment]
Přišel jsem na to, ze ta díra byla ve skutečnosti způsobená kódem popsaným jako "//část B":

https://github.com/Elizaa62/Components/blob/8a4e3cbbc8ae1a911703db10ebae8d3879345e44/src/666_1025.scad#L148-L150

Zakomentoval jsem to původně zamýšlené válce pro otvory na šrouby jsem posunul a vytvořil pull-request se změnami.

**Comment by Elizaa62** [comment]
Otvory pro šrouby jsou snad již s právně jak v dílu 666_1025 tak pak v dílu 666_1027.

**Comment by kaklik** [comment]
Dobře, myslim že se to může uzavřít.
