### ISSUE TITLE
666_1029

### ISSUE THREAD

**Issue by Elizaa62** [Elizaa62/Components#56]
Vytvořila jsem pro dělení spodního krytu globální parametry jako jsou pro hodní kryt. Zde je to proměnná "bottom_cover_division". Požadoval jsi dělení za přední podvozkovou nohou a před zadní podvozkovou nohou. Jelikož umístění podvozkových noh mám určené zdlouhavým vzorcem, tak jsem si hodnotu spočítala podle jmenovitých hodnot a dělení provedla přibližné, aby to vycházelo. Mám akorát strach v části D, kde je před zadní podvozkovou nohou zbývá malé množství materiálu, aby nedocházelo k ulamování. Důvodem tohoto malého množství materiálu je to, že kdybych dělení posunula, tak by musela vzniknout nová část, protože maximální tisknutelný rozměr by nepojmul celou zbylou část dělenou před zadní podvozkovou nohou až do konce krytu.

Dále podle této globální proměnné pro dělení jsem vytvořila umístění šroubů a rantlů. 

Zámky zatím hotové nejsou.

V části B a C jsem tloušťku rantlu udělala 4*hull_wall_thickness. Důvodem je vytvoření otvoru pro šroub a matku pro spojení těchto dvou částí. Zatím jsou zde jen dva šrouby. Mám případně ještě doplnit dva šrouby do spodní části rantlů?

**Comment by kaklik** [comment]
Podíval jsem se na to, myslím že řešením je to, že poslední koncový díl teď ve skutečnosti není dlouhý přes celý tiskový rozměr. Protože jeho délka se počítá z délky celé kapky, ale reálně je to pouze menší část vyříznutá ze spodní strany, nikoli z celé délky. 
Takže to dělení se může určitě posunout. Minimálně tak, aby to bylo symetrické s tím předním dílem. 

Reálná tisková délka jde poměrně snadno zkontrolovat tak, že se ten díl uzavře do kvádru o maximálních tiskových rozměrech a ověří se, že nepřečnívá.

**Comment by kaklik** [comment]
Všiml jsem si, že část B a C jsou spojeny tak, že sešroubován rantl na vnitřní straně.  Tento způsob spojení ale nepůjde použít, protože ke šroubu nebude možné se dostat. 
Části B a C mají tvořit uzavřený kontejner, kde budou zakryty všechny strany. Je proto potřeba použít nějaký typ spojení, který bude přístupný zvenku.  Jeden možný způsob jsem již navrhoval v #37 .

**Comment by Elizaa62** [comment]
Maximální tisknutelný rozměr je 150 x 150 mm. Tím, že jsem si tam zobrazila kvádr o těchto maximálních tisknutelných rozměrech, se mi zobrazilo, že ten konec musím rozdělit na dvě menší části, abych před tou zadní podvozkovou trubkou měla více materiálu. Ale o tom jsem psala už nahoře myslím.

**Comment by Elizaa62** [comment]
Jak myslíš to, že na dílu B a C budou plné stěny včetně stropu?

**Comment by kaklik** [comment]
Aha, dobře už to vidím taky, ta rezerva je tam zanedbatelná.

![image](https://user-images.githubusercontent.com/1194177/34492364-87800780-efe7-11e7-8591-7e3aabff3f07.png)

Takže bude asi nutné to rozdělit na dva díly.  Protože jinak se tam zřejmě nevejde ani ten držák OpticalFlow senzoru. 

Plnými stěnami myslím to, že ten díl bude dutý ale zvenku všude zakrytý. Prostě hermeticky uzavřená nádoba.

**Comment by Elizaa62** [comment]
Poslední část rozdělena na dvě. Dále vytvořeny otvory pro šrouby pro připevnění k podložce. Otvory jsou v části A, D a E. Otvory pro spojení částí B a C zatím nejsou vytvořené.
