### ISSUE TITLE
Spasování lemu na krytu a drážky na podložce

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#58]
Lem na krytu nezapadne do drážky v podložce, protože tomu brání vnitřní lemy na spojích krytu. 

![dsc09967](https://user-images.githubusercontent.com/1194177/34748013-f045c544-f59a-11e7-8595-3597f2927a18.JPG)

![dsc09970](https://user-images.githubusercontent.com/1194177/34748037-042d5036-f59b-11e7-8ebe-282a4c5482df.JPG)

 Je potřeba aby na výšku podložky bylo  na krytu více místa a nebo lem na podložce posunout.

**Comment by Elizaa62** [comment]
Co jsem pochopila, tak podložka je nahoru zvětšena o coupling_wall_thickness, tudiž jsem rantly posunula též o tuto hodnotu a plus jsem přidala 2*global_clearance.

**Comment by kaklik** [comment]
Je tam v nějakém modelu provedený test toho, že to do sebe pasuje?

**Comment by Elizaa62** [comment]
Zkoumala jsem to akorát tak, že v souboru 666_1027 jsem si zobrazila horní kryt a detailně jsem na to koukla.

**Comment by kaklik** [comment]
Dobrá, zřejmě je  ještě potřeba posunout pozici zámků: 

![image](https://user-images.githubusercontent.com/1194177/35441919-abf1fb48-02a5-11e8-9df9-a0f710b87f24.png)

**Comment by Elizaa62** [comment]
Mělo by být opraveno.
