### ISSUE TITLE
Zavedení podélných lemů pro výztuhu krytů

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#64]
Velké kryty se při tisku kroutí a vlní. Tato záležitost by se dala zřejmě odstranit zavedením podélných výztuh. Výztuhy by měly být zřejmě pravidelně po celém obvodu krytu. Zejména důležité je to u rovných částí krytu.

**Comment by kaklik** [comment]
Vytvořil jsem první podélnou výztuhu v horní části krytu: 

![image](https://user-images.githubusercontent.com/1194177/35147810-3b7a9766-fd10-11e7-9ebe-a57a2c293943.png)

Podélná výztuha je přidána zde: 
https://github.com/Elizaa62/Components/blob/e18dd2d1f51a7a4a78a829243df8391390074985/src/666_1025.scad#L263-L266

**Comment by Elizaa62** [comment]
Má se jich tam teda doplnit více?

**Comment by kaklik** [comment]
Po zkušenosti z testovacího výtisku to vypadá, že to není potřeba a může se tenhle úkol uzavřít. :)
