### ISSUE TITLE
nekonzistence modelu 888_1001

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#65]
Model přestal fungovat po změně rozměrů. Snažil jsem se to trochu opravit, ale zatím se mi to moc nepovedlo. Současný stav vypadá takhle: 

![image](https://user-images.githubusercontent.com/1194177/35435493-2f923226-028b-11e8-9dda-fc3a94ef7499.png)

**Comment by Elizaa62** [comment]
Co jsi s tím udělal? Vždyť to fungovalo..

**Comment by kaklik** [comment]
Změnil jsem trochu parametry rozměrů, přestalo to fungovat a pak jsem se to snažil opravit.

**Comment by Elizaa62** [comment]
Už by to mělo fungovat.
