### ISSUE TITLE
Neznámé parametry v sestavě 666_2000

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#66]
Pokusil jsem se vyrenderovat novou celkovou sestavu 666_2000.  Zjistil jsem, že tam je použita proměnná "okraj", která ale  zřejmě nikde není definovaná.

    openscad -m make -o STL/666_2000.stl src/666_2000.scad
    ECHO: 2.92971
    WARNING: Ignoring unknown variable 'okraj'.
    WARNING: Ignoring unknown variable 'okraj'.
    WARNING: Ignoring unknown variable 'okraj'. 
    WARNING: Ignoring unknown variable 'okraj'.
    WARNING: Ignoring unknown variable 'okraj'.

**Comment by Elizaa62** [comment]
Tento problém jsem odstranila. Byl problém v tom, že jak se měnily názvy proměnných u té spojky 888_1001, tak v dílu 666_1027 byly špatné názvy. Akorát teď mám problém v tom, že mě ten model nefunguje.

**Comment by Elizaa62** [comment]
Tys to nějak měnil? Mám tam ty osy naopak.. i díl 666_1027 je vložen špatně.

**Comment by kaklik** [comment]
Ne osy jsem neměnil. Možná jsem akorát zase zapnul to nastavení pohledu v Openscadu.

**Comment by kaklik** [comment]
Myslím, že to celé nefunguje správně díky tomu, že v souboru 666_1027 je použita proměnná "okraj", která ale nikde nemá nastavenou hodnotu:
![image](https://user-images.githubusercontent.com/1194177/35486269-d1e78be8-046b-11e8-84da-af4be942d734.png)

**Comment by Elizaa62** [comment]
Opraveno, ale stejně je ten soubor nějaký vadný.

**Comment by kaklik** [comment]
Já nějak nevidím žádnou změnu. Možná jsi to sem nenahrála.

**Comment by Elizaa62** [comment]
Já to sem píšu, abych na to nezapomněla. Nahraju to pak večer až pro dnešek skončím.

**Comment by Elizaa62** [comment]
Nahráno a stále to nefunguje, jak má.

**Comment by kaklik** [comment]
Já myslím že to funguje tak, jak je tam napsáno.   Pro vložení podložky 1027 je potřeba, aby tam byla správně nastavená rotace tj. 
	rotate([90,0,0])	
		666_1027();

místo  
	rotate([0,0,0])	
		666_1027(); 

A potom je ještě potřeba, aby podložka byla  ve svém souboru správně posunutá. Teď se po jejích úpravách stalo, že je moc nízko, takže to nefunguje správně.

**Comment by kaklik** [comment]
Řekl bych, že tohle je už taky vyřešené.
