### ISSUE TITLE
Díry na šrouby v držáku 888_1001

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#67]
Do takhle nastaveného modelu nepůjde vložit matka: 

![image](https://user-images.githubusercontent.com/1194177/35567892-eedfd244-05c6-11e8-9d6d-f066c2f51e72.png)

**Comment by Elizaa62** [comment]
Vím, že tam matka nepůjde vložit.. ale ty sis to tak nastavil :D

**Comment by kaklik** [comment]
Tak to mám přenastavit jinak?  Aby to pak zas  nebylo na mě, že jsem to rozbil. :)

**Comment by Elizaa62** [comment]
Jak chceš :) podle mě stačí přenastavit jeden parametr a to šířku toho čtverečku a bude to fungovat :)

**Comment by Elizaa62** [comment]
Zvětšila jsem to.

**Comment by kaklik** [comment]
Vyřešeno. :)
