### ISSUE TITLE
Soubor 666_1025

### ISSUE THREAD

**Issue by Elizaa62** [Elizaa62/Components#70]
Horní kryt opraven, základní kapka vytvořena v souboru 888_1000. Pokud bude vše správně fungovat pro tisk, tak se issue uzavře.

**Comment by kaklik** [comment]
Zjistil jsem, že zámky na horním krytu jsou zřejmě delší než otvory v protikusu. Ten rozdíl je malý, asi něco jako 0.3mm. Nicméně to způsobuje, že části nejdou sesadit až k sobě a musí se zámky trochu upilovat. 
Všiml jsem si, že tahle potíž existuje už dříve. Ale teď je ten tisk už tak dobrý, že je to zřejmé. 

Řešením je zavedení tolerancí v rozměrech zámků. Klidně se na to může požít existující proměnná "global_clearance".

**Comment by Elizaa62** [comment]
Ta proměnná je tam již použita. Tak já ji tam dám asi ještě jednou. 

Už jsem možná přišla na to, kde je problém. Ta proměnná je tam již zavedená. Ale já to v té ose y posunula o tu celou proměnnou a ne jen o půlku. Proto tolerance není i na druhé straně a nejde to sesadit dohromady.

Navíc jsem o tu proměnnou posunula i přidané zámky, čehož jsem si vůbec nevšimla.

Tak jsem to teď promazala a posunula vše jen o půlku tolerance.

**Comment by kaklik** [comment]
Jo, vypadá to, že jsi na to přišla.  :) Já jsem taky viděl, že ta tolerance tam už nějak je. Ale myslel jsem si, že asi není použitá správně, nebo ve správné ose.

**Comment by Elizaa62** [comment]
takže zavírám :)
