### ISSUE TITLE
Šrouby pro připevnění krytů k podložce

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#73]
Díval jsem se na to, jak jsou vyřešené kapsy na matky pro přišroubování krytů v podložce. 

![obrazek](https://user-images.githubusercontent.com/1194177/36071592-a64afb78-0f10-11e8-9abf-51fe72e8a156.png)

Moc se mi nezdá to, že jsou hrůzně daleko od stěny. Byl bych totiž asi raději, kdyby bylo možné spodní i horní kryt přišroubovat stejnou délkou šroubů.

**Comment by Elizaa62** [comment]
Udělala jsem to tak, že vždycky za tou dírou pro matku je díra ještě 10 mm pro šroub.

**Comment by kaklik** [comment]
Viděl jsem že teď je to tam tak, že matky jsou přibližně stejně daleko od okraje, takže je to myslím vyřešené. :)
