### ISSUE TITLE
Nastavení výšky krytu pylonu (díl 666_1032)

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#74]
Líbilo by se mi, kdyby kryt pro pylon 666_1032 byl vyřešený tak, že se jeho výška dopočítá automaticky, z délky vertikální středové trubky (pylonu).

Pak by bylo možné uříznout definovaně dlouhou vertikální trubku a vytisknout kryt, který k ní bude pasovat.  Poměrně výrazně to pomůže pro jednodušší nastavení polohy těžiště.

**Comment by Elizaa62** [comment]
Myslím si, že jsem to vyřešila.

**Comment by Elizaa62** [comment]
Máš to i s komentem.

**Comment by kaklik** [comment]
Zkoušel jsem to použít a je to skoro dobře :) 

![image](https://user-images.githubusercontent.com/1194177/36142547-baea4964-10a8-11e8-98e6-f60b51b51487.png)

Akorát to myslím nezohledňuje výšku držáku krytu a kryt je tak přibližně o výšku držáku kratší. 

![image](https://user-images.githubusercontent.com/1194177/36145219-fabb8e42-10b0-11e8-8b14-a410243e84eb.png)

**Comment by Elizaa62** [comment]
Teď asi nerozumím, co mám přesně opravit..

**Comment by kaklik** [comment]
Myslím, že k tomu může pomoc horní obrázek, který jsem sem přidal.  Je na něm vidět, že kryt pylonu má pod horní spojkou která se nasazuje na trubku vůli.  To je úplně v pořádku. 
Ale zároveň pod krytem dole, je mezi kapkovitým horním krytem a krytem pylonu mezera. Což znamená, že když by se kryt pylonu nasadil na držák, který je na horním krytu kapky, tak jak bude reálně nasazený.  Tak kryt pylonu bude moc krátký.
Mezi spojkou na konci vertikální trubky a krytem pylonu vznikne myslim si až zbytečně velká mezera. Která tam jinak nemusí být skoro žádná, až na tolerance tisku.

**Comment by Elizaa62** [comment]
Je mi divné, že mezi držákem na horním krytu a krytem pylonu je taková mezera. Myslela jsem, že výška toho držáku na horním krytu vůbec s ničím nesouvisí.

**Comment by Elizaa62** [comment]
A dělal jsi to v té sestavě 888_1005?

**Comment by kaklik** [comment]
Výška držáku na horním krytu je myslím doplněním do kvádru, kterým se ořezává kapka.   Konečná pozice krytu pylonu by měla myslím být taková, že bude nasazením přes držák doléhat až na horní stěnu horní kapky. 
Dělal jsem to v sestavě 666_2000, ale to by mělo být jedno, protože ta výška krytu pylonu se skutečně mění a to je to, co jsem chtěl ověřit.

**Comment by Elizaa62** [comment]
Výška vyřešena.

**Comment by kaklik** [comment]
Ano, připadá mi, že to funguje.

**Comment by kaklik** [comment]
Tak se mi zdá, že výpočet výšky krytu zanedbává posun vertikální trubky pylonu nad centrální trubku. 
Podle mě je v modelu 1017 tahle vzdálenost tvořena součtem width/2 + (- global_clearance*2), chtělo by o věřit v nějaké celkové sestavě, že ta délka trubky je vážně vypočítána správně. 

![image](https://user-images.githubusercontent.com/1194177/36698767-fa81f606-1b4a-11e8-8142-d8d472140a4d.png)

Přišel jsem na to tak, že v Parameters.scad mám délku trubky nastavenou asi o 3mm kratší, než je reálná změřená.  Kryt by tak měl mít vůli ty 3mm.  Reálně je ale přesně na těsno.

**Comment by Elizaa62** [comment]
Délku vertikální trubky máš v Parameters nastavenou, tak jak jsi chtěl. Tzn. 195 mm. A tady o tom posunu jsem ti psala, že si nejsem jistá, že je to správně nastavené. 

Ale pokusím se to dát nějak dohromady.

**Comment by kaklik** [comment]
Udělal jsem pull-request, kde jsem to nastavení délky změnil.  Ono je to skoro dobře.  Jenom ten model krytu nepočítá s tím, že trubka pylonu je trochu výše, díky tomu, že nezačíná úplně přesně na stěně té horizontální trubky.

**Comment by Elizaa62** [comment]
Výška dílu 666_1017 je konstantní, v kódu je nastaveno 70 mm. Mezeru mezi trubkami jsem nastavila na coupling_wall_thickness. Tím pádem si vytiskni díl 666_1017 znovu a už by to mělo sedět.

**Comment by kaklik** [comment]
Dobře, ještě jsem to upravil tak, aby mezera mezi trubkami byla podle existující proměnné "thickness_between_tubes", která je pro tenhle rozměr myslím vhodnější. 
Na to, abych to otestoval musím přetisknout jak spojku, tak kryt, takže se to dám do tiskového plánu.
