### ISSUE TITLE
Díry pro připevnění podložky k hlavní trubce

### ISSUE THREAD

**Issue by Elizaa62** [Elizaa62/Components#75]
Vytvořila jsem ty otvory pomocí union, kdy jsem připojila  k podložce kvádry v určité šířce. Nejsem si ale jistá, zda to bude fungovat přesně, jak požaduješ, že se tam opravdu přidá materiál. Je to vytvořené hned v začátku hned za sloupky pro GPS. Tak na to prosím koukni.

**Comment by kaklik** [comment]
Může to být dobře a nemusí.  Záleží na tom, jak se pak provede to odlehčení.  Protože odlehčení je pak potřeba provést tak, aby se neodečítalo od těhle připojovacích/vyztužovacích kvádrů.

**Comment by kaklik** [comment]
Není tohle už tohle nějaké zastaralé issue?

**Comment by Elizaa62** [comment]
Je, ale stále není vyzkoušeno, zda to bude fungovat.

**Comment by kaklik** [comment]
Tak já to vyzkouším, když budu mít podle čeho vyvrtat ty díry. :)

**Comment by kaklik** [comment]
Zkoušel jsem přišroubovat podložku na hlavní podélnou trubku.  Díry jsem si provizorně vyznačil přes vytištěnou podložku. 
Nejdelší šrouby M3, které jsem sehnal jsou dlouhé 50mm a zjistil jsem, že nedosahují skrz podložku tak, aby na druhé straně šla přitáhnout matka. 

Je zřejmě potřeba upravit hloubku otvorů tak, aby 50mm šrouby stačily.

**Comment by kaklik** [comment]
Tak jsem potřebnou délku šroubů pro připevnění podložky zkrátil na 50mm  a zavedl jsem nový globální parametr, který tuto délku šroubu definuje. 

poslední šroub v zadní části podložky jsem uměle zkrátil na 40mm, což je teď sice špatně, protože správně by šroub asi chtělo posunout tak, aby šla zachovat délka.  Ale nemáme čas na výrobu celého nového modelu včetně výměny hlavní trubky.

**Comment by Elizaa62** [comment]
Je u tohoto issue  něco, co mám opravit?

**Comment by kaklik** [comment]
Já jsem teď rozhodnutý postupně sestavit jeden další nový kus vírníku.  Z toho důvodu by zřejmě bylo vhodné opravit i tu poslední díru v podložce, ve které je teď kratší šroub. 
Oprava spočívá ve vhodném posunutí šroubu do širší části podložky.
