### ISSUE TITLE
Nefunguje správně parametr pro zapuštění akumulátorů do podložky

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#76]
Když se parametr "sink_of_accumulator" nastaví na 0 nebo skolo nula. Tak to udělá něco jako tohle:

![image](https://user-images.githubusercontent.com/1194177/36078983-2f172892-0f7e-11e8-9f61-493ffa965664.png)

Pokud se nastaví na -17, tak je akumulátor naopak skoro na povrchu podložky.

**Comment by Elizaa62** [comment]
Opraveno :)

**Comment by kaklik** [comment]
Ještě to možná způsobuje jinou chybu v tomhle modelu: 

![image](https://user-images.githubusercontent.com/1194177/36124471-7214a606-1050-11e8-8026-e11d34645229.png)

**Comment by Elizaa62** [comment]
Opraveno.

**Comment by kaklik** [comment]
Dobře, ještě ověřím, že když se vytiskne podložka a držák akumulátoru, tak že vyjde správně výška.  Pokud to tak bude, tak to zavřu. :)

**Comment by kaklik** [comment]
Tak výška akumulátoru mezi podložkou a držákem sedí. :)
