### ISSUE TITLE
Tloušťka stěny spodního krytu zřejmě není všude stejná

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#77]
Při nastavování tisku spodního krytu jsem zjistil, že v některých částech je vygenerovaný kryt děravý. Myslím, že je to způsobené tím, že stěna je v některých místech tak tenká, že ji nelze vytisknout. 

![tisk](https://user-images.githubusercontent.com/1194177/36096321-2eb171e6-0ff6-11e8-923f-6abf0498ddb7.png)

**Comment by Elizaa62** [comment]
Trochu dost nechápu, jak je to možné...

**Comment by kaklik** [comment]
Mám se pokusit tu příčinu najít? :)  Myslím, že to bude jedna z těchto dvou možností. 

1. Model je vygenerovaný příliš hrubě, protože není správně aplikována proměnná "draft"
2. Stěna je tenčí díky tomu, že se odečítá špatně posunutá kapka. V tomhle případě asi posunutá moc do spodní části modelu.

**Comment by kaklik** [comment]
Tak zřejmě to bylo skutečně způsobené příliš hrubým vykreslením zakulaceného povrchu, když jsem opravil v modelu několik drobných chyb a správně použil proměnnou "draft", tak se zdá, že model je zpracovaný, jak má být: 

![image](https://user-images.githubusercontent.com/1194177/36123903-8500e830-104e-11e8-82f2-e956da2f9c41.png)
