### ISSUE TITLE
Nízká tloušťka stěny u šroubového spoje spodního krytu

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#80]
Při přípravě tisku ve stěně vznikne díra, která je pravděpodobně způsobená nízkou tlouťkou stěny. 

![tisk_dira](https://user-images.githubusercontent.com/1194177/36146867-53303d5c-10b6-11e8-8a8c-e127bab5b2f8.png)

**Comment by Elizaa62** [comment]
Zvětšila jsem tloušťku zadní stěny šroubů.

**Comment by kaklik** [comment]
Už to jde vytisknout bez díry ve stěně.
