### ISSUE TITLE
Vyztužení dílů B a C spodního krytu 1029

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#81]
Při vytištění dílu B spodního krytu jsem zjistil, že vrchní stěna, která má být rovná se vlní.  Na fotografii to není až tak dobře viditelné.  Ale pomohlo by, kdyby žebra, která jsou teď na bočních stěnách byla i na horní stěně. 

Dále také přepážka, která odděluje díl B od dílu A není moc dobře vytištěná. Je vidět že na fotografii prosvítá.  To je zase tím, že přepážka při tisku není ničím podepřená a tiskne se do vzduchu.  Dalo by se to vyřešit tím, že žebra z horní stěny budou pokračovat až přes přepážku na protější zaoblenou stěnu.   Tím se stane, že při tisku se budou nejdříve tisknout žebra a pak teprve přepážka, která ale už bude podepřena vytištěnými žebry.

![20180214_112020](https://user-images.githubusercontent.com/1194177/36201557-9ddc7eb8-1180-11e8-8449-9c6dfc881498.jpg)

Stejná záležitost se symetricky týká i dílu C.

**Comment by Elizaa62** [comment]
Prozatím vyřešeno.

**Comment by kaklik** [comment]
Vytiskl jsem si zkrácené varianty dílů, abych viděl, co udělá mřížka pod přepážkou. Stalo se tohle: 

![20180216_160456](https://user-images.githubusercontent.com/1194177/36357540-c7e6c8bc-14ff-11e8-8ae1-5d0a80fd87b0.jpg)

Je to způsobené tím, že slicer při plánování tras tisku neplánoval tisk přepážek přes celou délku, ale jenom ve čtvercích. Takže se tahy vzájemně nespojily. 
Myslím, že jsem to vyřešil tím, že jsem odebral příčné výztuhy tak, aby tisk byl vždycky přes celý rozměr modelu.

![20180216_160512](https://user-images.githubusercontent.com/1194177/36357575-37a3b11a-1500-11e8-8488-8fcb6da25add.jpg)

Přepážky jsou sice trochu prověšené, ale konstrukční účel plní. :)
