### ISSUE TITLE
Optimalizace dílů A a D spodního krytu pro tisk

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#82]
Potíž s tiskem dílů, které mají otvory pro podvozkové nohy je taková, že pokud se díl tiskne v poloze "na lemu pro podložku" tj. takto: 

![image](https://user-images.githubusercontent.com/1194177/36246550-ae8dfc0e-1230-11e8-888e-016d38591021.png)

Tak  nedopadne dobře tisk kulaté části, která v takové  poloze tvoří převis. 

Pokud se díl otočí do této polohy 
![image](https://user-images.githubusercontent.com/1194177/36246630-f34bd99c-1230-11e8-8cd5-24d2d836d620.png)

Tak tisk z větší části dopadne dobře, až do chvíle než se začnou tisknout výřezy pro podvozkové nohy. Horní strana výřezu (v této poloze) se totiž zhroutí, protože není ničím podepřená. 

### Návrh na řešení 

- Doplnit výřez pro podvozkovou nohu tenkým čtvercem, o tloušťce stěny třeba 0.6mm.  Který bude sloužit k podepření horní strany výřezu během tisku. 
Tento čtverec se pak po vytištění modelu vystřihne, nebo vylomí. 
- Doplnit lem na spoj dílů C a D.   To z důvodu aby díl D při tisku lépe držel na podložce. 

V principu stejné úpravy se mohou udělat na dílu A.

**Comment by Elizaa62** [comment]
![image](https://user-images.githubusercontent.com/31339298/36249104-ee495e20-1239-11e8-9926-29151141a6ed.png)


Takto nějak?

**Comment by Elizaa62** [comment]
Na netu je další verze. Je to uděláno pomocí kapky. Ale nejsem si jistá tloušťkou těch výztuh.

**Comment by Elizaa62** [comment]
Doplněn i lem.

**Comment by kaklik** [comment]
Tak minimálně u předního krytu úprava pomohla :) A kryt je teď vytištěný dobře.  Ty další výztuhy, které jsou vidět na fotografii tak je tisková podpora, která taktéž přijde vylámat. 

![20180215_233658](https://user-images.githubusercontent.com/1194177/36305167-c0f763de-1312-11e8-9e94-6da055d717dd.jpg)
