### ISSUE TITLE
Tolerance bočních zámků na krytech

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#83]
Na horním krytu jsem zjistil, že tolerance bočních zámků nejsou výškově asi úplně správně.  Viz následující fotografie. 

![20180215_103545](https://user-images.githubusercontent.com/1194177/36250798-219a56e4-123f-11e8-8182-af20b7846c7f.jpg)

![20180215_103613](https://user-images.githubusercontent.com/1194177/36250804-26ef34b6-123f-11e8-83be-5b7595eb5da6.jpg)

Horní zámek ale vychází v pořádku, tak jak bych čekal :) 

![20180215_103505](https://user-images.githubusercontent.com/1194177/36250819-3424c786-123f-11e8-9b37-4ecd94740a08.jpg)

Konkrétně jsou tohle části D a E horního krytu.

**Comment by Elizaa62** [comment]
Měla jsem špatná znaménka u tolerancí. Nevšimla jsem si, že se výřez pro zámek zvětšuje nahoru a posunula jsem ho o půlku tolerance nahoru místo dolů. Takže by to mělo fungovat.

**Comment by kaklik** [comment]
Ano, potvrzuji, že je to vyřešené. :)
