### ISSUE TITLE
Dělení podložky 1027

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#84]
Při slepování vytištěných dílů podložky jsem přišel na tyhle záležitosti: 

- Pomohly by nějaké zámky, které zajistí, že díly se při slepování nemohou vzájemně posunout. Ani na výšku ani na šířku. 
- Pomohlo by, kdyby dělení podložky bylo nastavené tak, aby v dělící rovině nebyl žádný šroub, nebo nějaký jiný složitý tvar.

**Comment by Elizaa62** [comment]
Dělení jsem změnila. Otvory pro připevnění k horizontální trubce jsem posunula. Přidala jsem zámky. Koukni se, zda to může takto býti.

**Comment by kaklik** [comment]
Jo v principu to tak asi být může, jenom je ještě potřeba zjistit, jak se to snese s odlehčením podložky #78.
Zatím to ale zavřu.

**Comment by kaklik** [comment]
Tak jsem zjistil, že podložku v současné podobě nedovedu vytisknout, protože v tiskové sestavě mi vznikne neřešitelný problém s pozicí posledního dílu.  Který stojí na vystouplých zámcích, taktéž díl před ním by potřeboval, kdyby zámky mohly být otočené. 

https://github.com/kaklik/Components/blob/master/STL/print_plate_1027.stl

Zřejmě je to potřeba vyřešit tak, že zámky budou buď vypadat tak, že na nich jde vytisknout celý díl. A nebo bude existovat spojovací kus, který se zalepí do dílu, který by nešel se zámkem vytisknout.

**Comment by Elizaa62** [comment]
Dalo by se ty křížky vytisknout samostatně a pak by se vlepily do otvorů v podložce a pomocí nich by se ty díly podložky slepily k sobě?

**Comment by Elizaa62** [comment]
Hotovo.

**Comment by Elizaa62** [comment]
Existuje spojovací kus 888_1006, který se vlepí do připravených otvorů v dílu a pomocí druhého konce se spojí s druhým dílem.

**Comment by kaklik** [comment]
Vyzkouším to. Má ten díl nějakou toleranci, aby do toho otvoru šel vlepit?

**Comment by Elizaa62** [comment]
Díra má toleranci.

**Comment by kaklik** [comment]
Tiskne se to. Tisk podložky trvá 39 hodin.

**Comment by kaklik** [comment]
Tak výsledek není nic moc. 

![dsc00245](https://user-images.githubusercontent.com/1194177/37178178-fd78c306-2321-11e8-8476-9be61dd637ee.JPG)

Řekl bych, že těmi propojovacími křížky cesta nevede.  Je to náročné na kvalitu tisku. 

Navrhoval bych několik změn. 

1. Posunout dělení podložky tak, aby spodní strana tištěného dílu  byla vždycky plocha. 
2. Do podložky vytvořit podélné díry, které budou sloužit pro zasunutí vodícíchtrubek, jednak sloužících pro slepení a možná i pro vyztužení, pokud se v modelu nechají.

**Comment by kaklik** [comment]
Myslím, že jsem to vyřešil.  Pro sesazení dílů během lepení se prozatím použije stejná trubka, jako na podvozek.  
A dělení podložky jsem posunul tak, aby bylo zarovnané se stěnami spojek.
