### ISSUE TITLE
Vzdálenost otvorů v držáku akumulátorů nesedí se vzdáleností otvorů v podložce

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#85]
Držák akumulátorů má rozteč otvorů delší, než je rozteč v podložce.   Rozměry držáku na akumulátor ale sedí dobře :)

![20180216_074636](https://user-images.githubusercontent.com/1194177/36305784-5735f6d8-1315-11e8-92de-4bd3ad4e6b98.jpg)

**Comment by Elizaa62** [comment]
Změněna poloha šroubů v podložce.
