### ISSUE TITLE
Šroubový spoj dílů B a C spodního krytu

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#87]
Šroub se při pokusu o vložení do otvoru pro stažení dílů zkříží v díře oproti svojí hlavičce.

![sroubb](https://user-images.githubusercontent.com/1194177/36357681-c57ffd08-1501-11e8-87b0-f92e417e23cd.jpg)

Zřejmě je okolo otvoru pro šroub příliš malá tolerance pro hlavičku.  

Nevím jestli je dobře, že zapuštění není šestihranné a tím pádem nebude držet matku, která je na druhé straně. Zatím mi připadá, že matku tak nepůjde utáhnout.

**Comment by Elizaa62** [comment]
Ale to zapuštění jsem dělala šestihranné...

**Comment by Elizaa62** [comment]
Opraveno.. zapuštění opravdu nebylo šestrihranné.. teď už je, tak to prosím vyzkoušej, zda to funguje...

**Comment by kaklik** [comment]
Zapuštění je teď opravdu šestihranné, ale stejně to nefunguje.   Je potřeba, aby i díra pro šroub měla stejný úhel jako zapuštění a otvor na matku aby byl řešen stejně, jako jsou kapsy na podložce.

**Comment by Elizaa62** [comment]
Změnila jsem celý šroubový spoj. Díra je umístěna pod úhlem, na matku je vytvořena kapsa a celé je to umístěné v kvádru.
![vystrizek](https://user-images.githubusercontent.com/31339298/36646097-45027774-1a73-11e8-8462-97e158a75acd.PNG)

**Comment by kaklik** [comment]
Tak zatím jsem vytiskl jednu polovinu do otvoru na matku se nevejde matka, protože otvor na matku je nižší, než je výška matky. 
Je možné, že je to tiskem, neboť kapsa má trošku zborcený strop. nicméně tam není na to žádná rezerva. 

Jsou rozměry kapsy stejné jako u podložky?

**Comment by kaklik** [comment]
Ještě by bylo fajn, před tím než to budu tisknout přidat ten lem i na tu horní stěnu, kde teď jsou ta volná žebra.  Aby díl byl po celém obvodu při tisku chycený k podložce lemem.

**Comment by kaklik** [comment]
Tak šroub už tam pasuje. Akorát jeho hlava trochu vyčnívá z té díry pro zapuštění. :)  

![20180228_174719](https://user-images.githubusercontent.com/1194177/36814219-2c7c7388-1cd7-11e8-9197-62064deb89e9.jpg)

Na té fotografii je taktéž vidět, kde ještě není ten lem, aby byl okolo celého okraje.

**Comment by Elizaa62** [comment]
Lem přidán, otvor prohlouben, otvor na matku zvětšen z každé strany o global_clearance.

**Comment by kaklik** [comment]
Ta úprava kupodivu způsobila, že je šroub teď více utopený v modelu. Ale zatím nevadí, zkusím to vytisknout. 

![image](https://user-images.githubusercontent.com/1194177/36952340-eae5ee14-200e-11e8-9044-6257e2f46b8c.png)


To přidání 2*global_clearance na výšku matky M3 způsobilo, že je ten otvor náhodou stejně velký jako ty na podložce. Nevím ale, jestli by v tomhle případě nebylo lepší změnit hodnotu výšky matky.  A sjednotit to nastavení otvorů jak tady, tak i u podložky.

**Comment by Elizaa62** [comment]
Proč bys chtěl měnit výšku matky? Výška matky je pevně daná v Parameters. Ten otvor je stejně velký, protože v podložce přidávám na výšku matky 1 mm a tady 2*global_clearance, což náhodou vychází stejně.

**Comment by kaklik** [comment]
To vím, že je to náhodou stejné. Ale jenom zrovna při tomhle nastavení global_clearance, když se to změní, tak to tak už nebude. Proto by myslím bylo vhodné změnit výšku matky, aby se global_clearance využívala jenom na zarovnání nepřesností tisku, ne rozměrů matky.

**Comment by Elizaa62** [comment]
Proměnná global_clearance je u otvorů pro matky vyrušená. Je tam daná pevná hodnota a to hodnota 1.

**Comment by kaklik** [comment]
Tu hodnotu 1 je myslím potřeba všude smazat. A místo toho nastavit  Nut_height_M3 v Parameters.scad  na hodnotu 2.7, místo 1,7mm. 

Jinak šroub se teď už úplně schová dovnitř. :) 

![dsc00209](https://user-images.githubusercontent.com/1194177/37046254-2c2930c0-2168-11e8-8a46-2c5f38427e3a.JPG)

Nepasuje akorát protikus s matkou, protože na konci otvoru pro matku, je z nějakého důvodu nižší prostor. 
![image](https://user-images.githubusercontent.com/1194177/37046399-8e67fd48-2168-11e8-8337-b19daa83dff8.png)

**Comment by Elizaa62** [comment]
Nut_height_M3 zvýšen z 1,7 na 2,7 mm. Opraveno v Parameters i v podložce a spodním krytu. 

Dále u spodního krytu jsem změnila tu kostku pro ochranu spoje dílu 2 a 3 na spojení válce a kužele.

**Comment by kaklik** [comment]
Je tam určitě commitnutá správná verze? Protože mě připadá, že se to nezlepšilo.

![image](https://user-images.githubusercontent.com/1194177/37459748-5c0b632a-2849-11e8-93a8-fcdddc6a2e02.png)

**Comment by Elizaa62** [comment]
Máš pravdu.. v jedné části jsem to zapomněla opravit.

**Comment by kaklik** [comment]
Tak jsem zjistil, že přidaný kužel ve kterém je šroubový spoj zapuštěný, nepřechází plynule do stěny, jak by se asi dalo očekávat.  Místo toho trčí mimo.

![image](https://user-images.githubusercontent.com/1194177/37781227-9811aee0-2df0-11e8-8918-1ab4c427b4e9.png)

Myslím, že by se to dalo celé elegantně vyřešit tak, že by se sestava kužel - válec - kužel. Nahradila sestavou dvou šikmých válců skrz stěnu.  Není přece nutné, aby šroub byl palalelně se stěnou.

**Comment by Elizaa62** [comment]
Pozice spojení zavedena podle funkce "surface_angle" a "surface_distance". Obal spojení je pomocí válce s koulí na konci. Otvor pro hlavičku šroubu je válec.

Takto je vytvořeno spojení mezi díly C a D u horního krytu a u dílu 2 a 3 u spodního krytu.

**Comment by kaklik** [comment]
Ano s tímhle výsledkem jsem spokojený. Myslím že je to i docela pěkné :) 

![image](https://user-images.githubusercontent.com/1194177/37935628-8be01dc2-3152-11e8-8cff-d4769b41e73b.png)
