### ISSUE TITLE
Krátké zámky na spoji spodního krytu dílů D a E

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#88]
Zámky vedoucí do dílu E se mi zdají nějak neúměrně krátké oproti vykousnutí v dílu E. 

![20180219_184504](https://user-images.githubusercontent.com/1194177/36394268-c0d6079a-15b3-11e8-93c4-8fa6e2e355a4.jpg)

**Comment by Elizaa62** [comment]
Toto by mělo být také opraveno.

**Comment by kaklik** [comment]
Teď je to opravené tak, že tyhle zámky jsou kratší než všechny ostatní.  Považoval bych za správnější, kdyby všechny zámky byly stejně dlouhé. Klidně zas na společný parametr.

**Comment by Elizaa62** [comment]
Zaveden nový parametr "lock_length", který definuje délku zámku. Od této délky se poté v kódu odečítá posunutí "hull_wall_thickness", aby bylo zajištění připojení k dílu.

**Comment by kaklik** [comment]
Tohle tedy znamená, že to mám vytisknout? Já jsem totiž čekal, jestli náhodou stejným způsobem neupravíš i ostatní zámky. 
Ale asi to teď na těchto dvou dílech, mám vyzkoušet, že?

**Comment by Elizaa62** [comment]
Vyzkoušej to prosím :)

**Comment by kaklik** [comment]
Tak zámky pasují, ověřeno tiskem.  Jsou teď asi nejdelší ze všech modelů. :)
