### ISSUE TITLE
Špatná pozice výřezu na podvozkovou nohu v dílu 1029 E

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#89]
![20180219_202324](https://user-images.githubusercontent.com/1194177/36395211-4e156e62-15b8-11e8-9297-049c447ab1bb.jpg)

Výřez na podvozkovou nohu je ve spodním krytu zřejmě na špatném místě vůči podložce a spodní kryt tak díky tomu nejde úplně nasunout na podložku.

**Comment by Elizaa62** [comment]
Jak je to možné? V tom celkovém modelu mi to všechno krásně sedí..

**Comment by Elizaa62** [comment]
Nevím,co mám tady opravit, když mi to v tom modelu sedí..

**Comment by kaklik** [comment]
Pokud jde o model 888_1005.scad, tak tam bych neřekl, že to dokonale sedí.  Také v modelu vidím, že nesedí díry na šrouby v krytu s dírami na šrouby v podložce. 

![image](https://user-images.githubusercontent.com/1194177/36398872-6ecdfeb0-15c9-11e8-8b41-f81ccad86e50.png)

v modelu 666_2000 je tahle záležitost ještě markantnější, ale zase tam sedí díry na šrouby v podložce s dírami v krytu. 

![image](https://user-images.githubusercontent.com/1194177/36399094-9c2f1686-15ca-11e8-89f7-8bcd07e7e826.png)

**Comment by kaklik** [comment]
Když už se v tom vrtám, tak podobná nesrovnalost je v mnohem menším i u předního krytu. 

Tady je ukázka z modelu 888_1005:

![image](https://user-images.githubusercontent.com/1194177/36399933-6f704c6a-15ce-11e8-9e98-4aa38a976e19.png)


Podobně i sestava 666_2000:

![image](https://user-images.githubusercontent.com/1194177/36399806-e02ad17e-15cd-11e8-93d9-ac9dfcea8c13.png)

**Comment by Elizaa62** [comment]
Ty díry pro šrouby neseděly proto, protože jsem posunula horní i spodní kryt  v ose x o mínus hull_wall_thickness. Vymazala jsem to a teď by ti díry pro šrouby měly sedět.

**Comment by Elizaa62** [comment]
Koukni na to, ale myslím si, že díry pro podvozkové nohy by už měly sedět. Chyba vznikla tím, že jsem v zadní části díru posunula navíc ještě o tloušťku stěny spojky, neuvědomila jsem si, že tam tento rozměr nepatří.

**Comment by kaklik** [comment]
Ano, je to opravené. :)

**Comment by kaklik** [comment]
Ještě jsem zjistil, že v přední části by zřejmě bylo potřeba opravit tenhle zub: 

![image](https://user-images.githubusercontent.com/1194177/36505848-1126b1ac-1755-11e8-9fa1-5188fbef0b66.png)

A v zadní části taktéž opravit zub a posunout lem: 
![image](https://user-images.githubusercontent.com/1194177/36505924-61622476-1755-11e8-8733-347416898093.png)

Obecně by asi bylo fajn, kdyby se díra ve stěně a díra v lemu vytvářela najednou.

**Comment by Elizaa62** [comment]
Zub je odstraněný. Zmenšila jsem výšku výřezu. 

Tvorba lemu je posunuta do horní části kódu, tudíž s měnící se pozicí otvoru pro podvozkovou nohu se bude měnit i otvor v lemu.

**Comment by kaklik** [comment]
Ověřeno vytištěním.
