### ISSUE TITLE
Vyztužení ocasních ploch 666_1028

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#91]
Současná konstrukce ocasních ploch má příliš malou tuhost. Řešením je z dílu zrušit prořezy a nahradit je výztuhami v dutém prostoru profilu.  K tomu je potřeba díl nejdříve upravit jako dutý model.  Do vnitřního prostoru je pak potřeba vymodelovat výztuhy. 

Výsledek by pak bude vypadat podobně, jako tento řez křídlem: 
![20180221_225915](https://user-images.githubusercontent.com/1194177/36509230-4c115de4-175f-11e8-89cd-63353ec4e4d7.jpg)

**Comment by Elizaa62** [comment]
V   " //LOWER - od osy x do plus y" jsem udělala dutý profil a pokusila se vytvořit nějaké výztuhy. Koukni na to prosím... Jinak ostatní profily jsou vytvořeny zatím jen jako duté.

**Comment by kaklik** [comment]
Ano, tak nějak jsem si to představoval. 

![image](https://user-images.githubusercontent.com/1194177/36951944-d8809a44-2009-11e8-9170-4694900849cf.png)

Akorát mi není jasné, proč se zas děje to, že ten profil nemá všude stejně tlustou stěnu. Ale řekl bych, že to bude nějak souviset s tím, že parametr naca musí být vždycky celé číslo, takže třeba: naca = 0005. A to na řádku 7 tak není.

Jinak ty moje pokusy o výztuhy jak podélné, tak i ty prořezy se můžou dát pryč. Nefungují dostatečně dobře a kazí to tyhle tvoje nové výztuhy.

**Comment by Elizaa62** [comment]
Na tom řádku 7 to byl jen překlep, kterého jsem si nevšimla.

**Comment by Elizaa62** [comment]
Výztuhy jsem doplnila i do ostatních profilů, v řádku 7 jsem překlep opravila. Tvé výztuhy jsem vyrušila.

**Comment by kaklik** [comment]
Paráda :) 
Akorát mi teď došla ještě jedna věc a to, že ty nové výztuhy zřejmě nemůžou být při tisku vodorovně, protože by se všechny tiskly jako most a nedopadlo by to myslím dobře. Stačí to ale zřejmě vyřešit tak, že se natočí úhlopříčně.  Tady jsem se to pokusil načrtnout. 

![20180305_101339](https://user-images.githubusercontent.com/1194177/36966735-0ac45e2e-205e-11e8-8c8d-3dacfcfc11c7.jpg)

**Comment by Elizaa62** [comment]
Výztuhy vytvořeny úhlopříčně.

**Comment by kaklik** [comment]
Úhlopříčné výztuhy jsou vytvořeny úplně správně. 

Pokusil jsem se to vytisknout, abych zjistil, jestli to půjde a skončil jsem na tom, že model má u náběžné hrany profilu tenké stěny, které jsou pod minimální tisknutelnou tloušťkou. Domnívám se, že to způsobuje výpočet nebo posunutí rozměru vnitřní dutiny. 

![tenke_steny](https://user-images.githubusercontent.com/1194177/37032211-f2751bb2-2141-11e8-8732-19cacdc2803d.png)

Příliš tenká stěna je i na bočních stěnách profilů.

**Comment by kaklik** [comment]
Pokusil jsem se to opravit, ale zjistil jsem, že je potřeba vnitřní dutinu posunout nějak neúměrně moc daleko od náběžné hrany. Skoro to vypadá, že u takhle tenkých profilů nějak nefunguje ten použitý postup výpočtu zmenšené kapky.

**Comment by kaklik** [comment]
Tak myslím, že jsem to opravil, jenom ještě musím doladit nastavení pro tisk. :)
