### ISSUE TITLE
Otvory pro šrouby v zadní části horního krytu 1025

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#93]
Díly D a E horního krytu nemají otvory na stejných pozicích, jako jsou otvory pro šrouby v podložce.

**Comment by kaklik** [comment]
Podobný problém má i spodní kryt.  Zřejmě by bylo vhodné, aby se otvory na šrouby přebíraly z nějakého seznamu otvorů, podobně, jako  se to dělá s dělením.  Podrobněji jsem to už popisoval tady  #62.

**Comment by Elizaa62** [comment]
Jak je možné, že tam jsou otvory pro šrouby navíc? Dávala jsem si veliký pozor, aby šrouby přesně seděly na otvory v podložce..

**Comment by kaklik** [comment]
Já nevím jak se to stalo. Ale v tom modelu je to lepší než v realitě. V modelu vidím akorát dvě díry v krytu, které nemají díry v podložce.  Zřejmě mám vytištěné nekompatibilní verze krytů a podložky, takže to přetisknu.

Tady na obrázku je to ta nejvíc vpravo: 

![image](https://user-images.githubusercontent.com/1194177/36694467-c965f11e-1b3e-11e8-98e1-f824c1de3c50.png)

z druhé strany krytu je symetricky ta druhá..

Pak jsem se díval ještě na podložku. A tam to vypadá takhle: 
![image](https://user-images.githubusercontent.com/1194177/36694655-54a27df6-1b3f-11e8-9f49-f785f9b2235a.png)
Je zvláštní, že tam je ta slepá díra a kapsa na matku, která zasahuje do drážky pro lem.

**Comment by Elizaa62** [comment]
Řekla bych, že to bude tím, že máš špatnou podložku. Zkus když tak vytisknout jeden zadní díl podložky a vyzkoušet to. A já bych to pak případně opravila :)

**Comment by kaklik** [comment]
Ale ta jedna slepá díra je v tom modelu i teď. Takže to se přetištěním nezlepší.

**Comment by Elizaa62** [comment]
Pokusím se to nějak opravit.

**Comment by Elizaa62** [comment]
Šrouby od spodního a horního krytu jsem zavedla pomocí globálních proměnných. Ta díra na šroub navíc, co je vidět na obrázku výše, už by tam být neměla.

**Comment by Elizaa62** [comment]
Šrouby od spodního a horního krytu jsem zavedla pomocí globálních proměnných. Ta díra na šroub navíc, co je vidět na obrázku výše, už by tam být neměla.

**Comment by kaklik** [comment]
Díra navíc tam už skutečně není. 
Jenom se teď spojily kapsy na matky pro obě matky do jedné, takže se myslím, že horní matka bude spadávat do díry pro spodní matku. 

![image](https://user-images.githubusercontent.com/1194177/36951301-4bf0ca42-2002-11e8-9e18-e9eef33f8035.png)

**Comment by Elizaa62** [comment]
Díru od spodního šroubu jsem posunula.

**Comment by kaklik** [comment]
Souhlasím vyřešené.
