### ISSUE TITLE
Spojení dílů C a D horního krytu 1025

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#94]
Díly C a D horního krytu nemohou mít zámky. Mají pouze společný široký lem, kterým pasují k sobě. 
Při spuštění motoru se pod díl D ale dostává vzduch, který kryt strhává. Bylo by proto potřeba oba díly spojit. 
Řešením může asi být stejný šroubový spoj, jako je na nákladovém prostoru spodního krytu.

**Comment by Elizaa62** [comment]
Až vyzkoušíš šroubový spoj u spodního krytu a bude jisté, že funguje, udělám ho i tady.

**Comment by Elizaa62** [comment]
Přidala jsem stejné šroubové spojení jako je pro díl 2 a 3 u spodního krytu.

**Comment by kaklik** [comment]
Vidím, že ty přidané šroubové spoje jsou z boku.  Myslím že v tomhle případě je potřeba je mít v té horní zakulacené části.  Protože hlavním účelem šroubů, je zajistit, aby byly díly C a D spojené v místě, kde je teď nic nedrží. To znamená poblíž držáku krytu pylonu.

**Comment by Elizaa62** [comment]
Vytvořeno.

**Comment by kaklik** [comment]
Je tam zkopírovaná ta chyba ze spodního krytu, kde je špatná výška matky v díře stejně jako v případě issue #87

![image](https://user-images.githubusercontent.com/1194177/37335779-bd0d9904-26af-11e8-99e1-a49e6a046e91.png)

Obávám se také že to provedení zapuštění šroubu, které tam teď je neumožní šroub dobře utáhnout, protože tam nepůjde strčit imbus v ose šroubu, ale bude muset být nakloněný ven.

**Comment by Elizaa62** [comment]
Tak jsem se o něco pokusila, ale pochybuju, že ten můj způsob bude fungovat. Otvor pro zasunutí šroubu jsem zakončila pod větším úhlem.

**Comment by kaklik** [comment]
Tak zatím to dopadlo tak, že ta díra pro hlavičku šroubu je moc malá.  
![20180319_102612](https://user-images.githubusercontent.com/1194177/37587701-53ddfd92-2b60-11e8-942e-7a4043eb3bf3.jpg)

A asi bych měl nějaké nápady, jak to udělat celé lépe.  Zřejmě to ale bude potřebovat, abych připravil funkci, která vrátí úhel povrchu krytu v daném místě kapky.

**Comment by kaklik** [comment]
Tak už existuje funkce, která ti umožní zajistit, aby díra pro šroub byla pod definovaným úhlem vůči povrchu krytu.

**Comment by Elizaa62** [comment]
Díra pro šroub opravena funkcí "surface_angle".

**Comment by kaklik** [comment]
Mě by se ještě líbilo, kdyby ten válec ve kterém jsou zapuštěné šrouby z vnitřní strany postupně splýval s tím krytem. Takhle jak je tam ta špička, tak mi to připadá hodně divné.  Mě se docela líbilo to první řešení, kde byl šikmý válec skrz stěnu a postupně mizel do ztracena.  Pro šroub je to výhodné, protože válec pak může mít osu shodnou s osou šroubu. Na straně s matkou pak bude akorát díra na matku šikmo.

**Comment by kaklik** [comment]
Fajn, zatím tam necháme tyhle válce zakončené koulí. :)
