### ISSUE TITLE
Sražené hrany na dílu 1014

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#96]
Asi jsem už přišel na to, proč u toho dílu 666_1014 tak nevycházel symetrický tisk. Ono je sražení hran už v modelu zřejmě na každé straně jiné. 
Je to trochu vidět na tomhle pohledu: 

![image](https://user-images.githubusercontent.com/1194177/36645777-11196d78-1a6e-11e8-83f1-1acab8f2169b.png)

Taky je zajímavé, že teď není to dělení dílu přes celý díl, ale kousek rozdělený není a zároveň není dělený podle osy přesně uprostřed. To nevím co se mezitím stalo.

**Comment by Elizaa62** [comment]
Opraveno oboje.

**Comment by kaklik** [comment]
Souhlasím. Vidím, že jsi opravila i tu osu symetrie.
