### ISSUE TITLE
Šířka podložky 1027

### ISSUE THREAD

**Issue by kaklik** [Elizaa62/Components#98]
Zjistil jsem, že šířka podložky byla nastavená přesně na šířku trupu tj. 150mm. Jenomže má pasovat dovnitř horního krytu. To znamená, že musí být menší než kryty a to ještě navíc o toleranci. 
Podložku jsem zmenšil a přidal tolerance.  Jenže se stalo, že z bočních stěn začaly vylézat ještě nějaké další přidané hranoly, nevím kde v kódu jsou. 

![image](https://user-images.githubusercontent.com/1194177/36725124-8fe51218-1bb5-11e8-98cd-d03bc5db94af.png)

**Comment by Elizaa62** [comment]
Vyřešeno.

**Comment by kaklik** [comment]
Je fajn, že už tam ty výstupky nejsou. 
Nedovedu to ale ověřit tiskem, protože podložka nejde vytisknout díky současnému řešení zámků. Viz #84

**Comment by Elizaa62** [comment]
Výstupky nejsou a řešení zámků je též vyřešeno, viz #84 .

**Comment by kaklik** [comment]
Souhlasím, je to vyřešené.
